### PR TITLE
Fix compilation errors for simulator with TFT screen

### PR DESCRIPTION
**Pull request by jmz52**
### Description

Fix compilation errors for simulator with TFT_COLOR_UI caused by https://github.com/MarlinFirmware/Marlin/pull/24980
Improved portrait mode detection for 320x240 screen, https://github.com/MarlinFirmware/Marlin/pull/25253 is now obsolete

240x320

### Requirements

Simulator with TFT_COLOR_UI
or
Any 320x240 TFT screen with TFT_COLOR_UI in portrait mode

### CODE REVIEW

File: Marlin/src/lcd/tft_io/tft_orientation.h [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+#endif
+#ifndef TOUCH_CALIBRATION_Y
+  #define TOUCH_CALIBRATION_Y   0
+#endif
+#ifndef TOUCH_OFFSET_X
+  #define TOUCH_OFFSET_X        0
+#endif
+#ifndef TOUCH_OFFSET_Y
+  #define TOUCH_OFFSET_Y        0
+#endif
```
Comment (thisiskeithb) [inline Marlin/src/lcd/tft_io/tft_orientation.h:81]: These changes cause values in pins files to be ignored now.
