### ISSUE TITLE
BABY_STEP ? in 2.0

### ISSUE THREAD

**Issue by cdedwards** [MarlinFirmware/Marlin#8263]
Is babystepping working in 2.0? I have changed the value of increase to 100 in an attempt to see and when I attempted to use it, nothing really seemed to be working. neither up or down

**Comment by Tannoo** [comment]
Configs?

**Comment by Roxy-3D** [comment]
There was a problem where the Baby Step multiplier got set to 100.  It is back at a more reasonable number of 1 right now.    For my machines, 3 or 4 works well.

```cpp
  #define BABYSTEP_MULTIPLICATOR 1 // Babysteps are very small. Increase for faster motion.
```

**Comment by cdedwards** [comment]
I have mine set at 10. doesn't seem to move at all though.
[Marlin-config.zip](https://github.com/MarlinFirmware/Marlin/files/1444671/Marlin-config.zip)

**Comment by Tannoo** [comment]
I cannot open that zip file.

Try disabling `BABYSTEP_ZPROBE_OFFSET` in `Configuration_adv.h`.

**Comment by cdedwards** [comment]
it's a renamed rar file. sorry

**Comment by cdedwards** [comment]
```
from Marlin\src\HAL\HAL_AVR\watchdog_AVR.cpp:25:
Marlin\src\HAL\HAL_AVR\../../inc/SanityCheck.h:365:6: error: #error "BABYSTEP_ZPROBE_GFX_OVERLAY requires a BABYSTEP_ZPROBE_OFFSET."
#error "BABYSTEP_ZPROBE_GFX_OVERLAY requires a BABYSTEP_ZPROBE_OFFSET."
```

**Comment by Roxy-3D** [comment]
Aaaauurrgghhhh....   

Please turn off the BABYSTEP_ZPROBE_GFX_OVERLAY  until we get that problem cleared up.

**Comment by cdedwards** [comment]
yep. problem disappeared once GFX_OVERLAY was disabled.
