### ISSUE TITLE
[BUG] Unable to compile for BOARD_MKS_ROBIN

### ISSUE THREAD

**Issue by Exquisitism** [MarlinFirmware/Marlin#13489]
### Description

Atom with Platformio is unable to compile for BOARD_MKS_ROBIN

### Steps to Reproduce

1. Try to compile with BOARD_MKS_ROBIN set as motherboard.

**Expected behavior:** To compile successfully

**Actual behavior:** Doesn't compile.

#### Compile log

```
Processing STM32F1 (platform: ststm32@<4.4.0; board: genericSTM32F103RE; framework: arduino)

Verbose mode can be enabled via `-v, --verbose` option

CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F103RE.html

PLATFORM: ST STM32 > STM32F103RE (64k RAM. 512k Flash)

HARDWARE: STM32F103RET6 72MHz 64KB RAM (512KB Flash)

DEBUG: CURRENT(blackmagic) EXTERNAL(blackmagic, jlink, stlink)

Converting Marlin.ino

Library Dependency Finder -> http://bit.ly/configure-pio-ldf

LDF MODES: FINDER(chain) COMPATIBILITY(soft)

Collected 35 compatible libraries

Scanning dependencies...

Dependency Graph

|-- <LiquidCrystal> 1.3.4

|   |-- <Wire> 1.0

|-- <TMCStepper> 0.3.1

|   |-- <SPI> 1.0

|-- <30aa480>

|   |-- <Wire> 1.0

|-- <Arduino-L6470> 0.7.0

|-- <SailfishLCD> #c8ac22f

|-- <SailfishRGB_LED> #2426fa2

|   |-- <Wire> 1.0

|-- <SlowSoftI2CMaster> #3a18be5

|-- <Wire> 1.0

|-- <SPI> 1.0

|-- <STM32ADC> 1.0

|-- <EEPROM>

Compiling .pioenvs\STM32F1\src\src\Marlin.cpp.o

Compiling .pioenvs\STM32F1\src\src\feature\bedlevel\ubl\ubl.cpp.o

Compiling .pioenvs\STM32F1\src\src\feature\bedlevel\ubl\ubl_G29.cpp.o

Compiling .pioenvs\STM32F1\src\src\feature\bedlevel\ubl\ubl_motion.cpp.o

Compiling .pioenvs\STM32F1\src\src\feature\bltouch.cpp.o

Compiling .pioenvs\STM32F1\src\src\feature\caselight.cpp.o

Compiling .pioenvs\STM32F1\src\src\feature\closedloop.cpp.o

Compiling .pioenvs\STM32F1\src\src\feature\controllerfan.cpp.o

In file included from Marlin\src\inc/../pins/pins.h:420:0,

from Marlin\src\inc/MarlinConfig.h:32,

from Marlin\src\Marlin.h:24,

from Marlin\src\Marlin.cpp:31:

Marlin\src\Marlin.cpp: In function 'bool pin_is_protected(pin_t)':

Marlin\src\inc/../pins/pins_MKS_ROBIN.h:68:28: error: 'PG15' was not declared in this scope

#define Y_STEP_PIN         PG15

^

Marlin\src\pins/sensitive_pins.h:92:17: note: in expansion of macro 'Y_STEP_PIN'

#define _Y_PINS Y_STEP_PIN, Y_DIR_PIN, Y_ENABLE_PIN, _Y_MIN _Y_MAX _Y_MS1 _Y_MS2 _Y_MS3 _Y_CS

^~~~~~~~~~

Marlin\src\pins/sensitive_pins.h:523:11: note: in expansion of macro '_Y_PINS'

_X_PINS _Y_PINS _Z_PINS _X2_PINS _Y2_PINS _Z2_PINS _Z3_PINS _Z_PROBE \

^~~~~~~

Marlin\src\Marlin.cpp:261:49: note: in expansion of macro 'SENSITIVE_PINS'

static const pin_t sensitive_pins[] PROGMEM = SENSITIVE_PINS;

^~~~~~~~~~~~~~

Marlin\src\inc/../pins/pins_MKS_ROBIN.h:68:28: note: suggested alternative: 'PC15'

#define Y_STEP_PIN         PG15

^

Marlin\src\pins/sensitive_pins.h:92:17: note: in expansion of macro 'Y_STEP_PIN'

#define _Y_PINS Y_STEP_PIN, Y_DIR_PIN, Y_ENABLE_PIN, _Y_MIN _Y_MAX _Y_MS1 _Y_MS2 _Y_MS3 _Y_CS

^~~~~~~~~~

Marlin\src\pins/sensitive_pins.h:523:11: note: in expansion of macro '_Y_PINS'

_X_PINS _Y_PINS _Z_PINS _X2_PINS _Y2_PINS _Z2_PINS _Z3_PINS _Z_PROBE \

^~~~~~~

Marlin\src\Marlin.cpp:261:49: note: in expansion of macro 'SENSITIVE_PINS'

static const pin_t sensitive_pins[] PROGMEM = SENSITIVE_PINS;

^~~~~~~~~~~~~~

Marlin\src\inc/../pins/pins_MKS_ROBIN.h:69:28: error: 'PG10' was not declared in this scope

#define Y_DIR_PIN          PG10

^

Marlin\src\pins/sensitive_pins.h:92:29: note: in expansion of macro 'Y_DIR_PIN'

#define _Y_PINS Y_STEP_PIN, Y_DIR_PIN, Y_ENABLE_PIN, _Y_MIN _Y_MAX _Y_MS1 _Y_MS2 _Y_MS3 _Y_CS

^~~~~~~~~

Marlin\src\pins/sensitive_pins.h:523:11: note: in expansion of macro '_Y_PINS'

_X_PINS _Y_PINS _Z_PINS _X2_PINS _Y2_PINS _Z2_PINS _Z3_PINS _Z_PROBE \

^~~~~~~

Marlin\src\Marlin.cpp:261:49: note: in expansion of macro 'SENSITIVE_PINS'

static const pin_t sensitive_pins[] PROGMEM = SENSITIVE_PINS;

^~~~~~~~~~~~~~

Marlin\src\inc/../pins/pins_MKS_ROBIN.h:69:28: note: suggested alternative: 'PC10'

#define Y_DIR_PIN          PG10

^

Marlin\src\pins/sensitive_pins.h:92:29: note: in expansion of macro 'Y_DIR_PIN'

#define _Y_PINS Y_STEP_PIN, Y_DIR_PIN, Y_ENABLE_PIN, _Y_MIN _Y_MAX _Y_MS1 _Y_MS2 _Y_MS3 _Y_CS

^~~~~~~~~

Marlin\src\pins/sensitive_pins.h:523:11: note: in expansion of macro '_Y_PINS'

_X_PINS _Y_PINS _Z_PINS _X2_PINS _Y2_PINS _Z2_PINS _Z3_PINS _Z_PROBE \

^~~~~~~

Marlin\src\Marlin.cpp:261:49: note: in expansion of macro 'SENSITIVE_PINS'

static const pin_t sensitive_pins[] PROGMEM = SENSITIVE_PINS;

^~~~~~~~~~~~~~

Marlin\src\inc/../pins/pins_MKS_ROBIN.h:72:28: error: 'PD3' was not declared in this scope

#define Z_STEP_PIN         PD3

^

Marlin\src\pins/sensitive_pins.h:125:17: note: in expansion of macro 'Z_STEP_PIN'

#define _Z_PINS Z_STEP_PIN, Z_DIR_PIN, Z_ENABLE_PIN, _Z_MIN _Z_MAX _Z_MS1 _Z_MS2 _Z_MS3 _Z_CS

^~~~~~~~~~

Marlin\src\pins/sensitive_pins.h:523:19: note: in expansion of macro '_Z_PINS'

_X_PINS _Y_PINS _Z_PINS _X2_PINS _Y2_PINS _Z2_PINS _Z3_PINS _Z_PROBE \

^~~~~~~

Marlin\src\Marlin.cpp:261:49: note: in expansion of macro 'SENSITIVE_PINS'

static const pin_t sensitive_pins[] PROGMEM = SENSITIVE_PINS;

^~~~~~~~~~~~~~

Marlin\src\inc/../pins/pins_MKS_ROBIN.h:72:28: note: suggested alternative: 'D3'

#define Z_STEP_PIN         PD3

^

Marlin\src\pins/sensitive_pins.h:125:17: note: in expansion of macro 'Z_STEP_PIN'

#define _Z_PINS Z_STEP_PIN, Z_DIR_PIN, Z_ENABLE_PIN, _Z_MIN _Z_MAX _Z_MS1 _Z_MS2 _Z_MS3 _Z_CS

^~~~~~~~~~

Marlin\src\pins/sensitive_pins.h:523:19: note: in expansion of macro '_Z_PINS'

_X_PINS _Y_PINS _Z_PINS _X2_PINS _Y2_PINS _Z2_PINS _Z3_PINS _Z_PROBE \

^~~~~~~

Marlin\src\Marlin.cpp:261:49: note: in expansion of macro 'SENSITIVE_PINS'

static const pin_t sensitive_pins[] PROGMEM = SENSITIVE_PINS;

^~~~~~~~~~~~~~

Marlin\src\inc/../pins/pins_MKS_ROBIN.h:73:28: error: 'PG14' was not declared in this scope

#define Z_DIR_PIN          PG14

^

Marlin\src\pins/sensitive_pins.h:125:29: note: in expansion of macro 'Z_DIR_PIN'

#define _Z_PINS Z_STEP_PIN, Z_DIR_PIN, Z_ENABLE_PIN, _Z_MIN _Z_MAX _Z_MS1 _Z_MS2 _Z_MS3 _Z_CS

^~~~~~~~~

Marlin\src\pins/sensitive_pins.h:523:19: note: in expansion of macro '_Z_PINS'

_X_PINS _Y_PINS _Z_PINS _X2_PINS _Y2_PINS _Z2_PINS _Z3_PINS _Z_PROBE \

^~~~~~~

Marlin\src\Marlin.cpp:261:49: note: in expansion of macro 'SENSITIVE_PINS'

static const pin_t sensitive_pins[] PROGMEM = SENSITIVE_PINS;

^~~~~~~~~~~~~~

Marlin\src\inc/../pins/pins_MKS_ROBIN.h:73:28: note: suggested alternative: 'PC14'

#define Z_DIR_PIN          PG14

^

Marlin\src\pins/sensitive_pins.h:125:29: note: in expansion of macro 'Z_DIR_PIN'

#define _Z_PINS Z_STEP_PIN, Z_DIR_PIN, Z_ENABLE_PIN, _Z_MIN _Z_MAX _Z_MS1 _Z_MS2 _Z_MS3 _Z_CS

^~~~~~~~~

Marlin\src\pins/sensitive_pins.h:523:19: note: in expansion of macro '_Z_PINS'

_X_PINS _Y_PINS _Z_PINS _X2_PINS _Y2_PINS _Z2_PINS _Z3_PINS _Z_PROBE \

^~~~~~~

Marlin\src\Marlin.cpp:261:49: note: in expansion of macro 'SENSITIVE_PINS'

static const pin_t sensitive_pins[] PROGMEM = SENSITIVE_PINS;

^~~~~~~~~~~~~~

Marlin\src\inc/../pins/pins_MKS_ROBIN.h:71:28: error: 'PD7' was not declared in this scope

#define Z_ENABLE_PIN       PD7

^

Marlin\src\pins/sensitive_pins.h:125:40: note: in expansion of macro 'Z_ENABLE_PIN'

#define _Z_PINS Z_STEP_PIN, Z_DIR_PIN, Z_ENABLE_PIN, _Z_MIN _Z_MAX _Z_MS1 _Z_MS2 _Z_MS3 _Z_CS

^~~~~~~~~~~~

Marlin\src\pins/sensitive_pins.h:523:19: note: in expansion of macro '_Z_PINS'

_X_PINS _Y_PINS _Z_PINS _X2_PINS _Y2_PINS _Z2_PINS _Z3_PINS _Z_PROBE \

^~~~~~~

Marlin\src\Marlin.cpp:261:49: note: in expansion of macro 'SENSITIVE_PINS'

static const pin_t sensitive_pins[] PROGMEM = SENSITIVE_PINS;

^~~~~~~~~~~~~~

Marlin\src\inc/../pins/pins_MKS_ROBIN.h:71:28: note: suggested alternative: 'D7'

#define Z_ENABLE_PIN       PD7

^

Marlin\src\pins/sensitive_pins.h:125:40: note: in expansion of macro 'Z_ENABLE_PIN'

#define _Z_PINS Z_STEP_PIN, Z_DIR_PIN, Z_ENABLE_PIN, _Z_MIN _Z_MAX _Z_MS1 _Z_MS2 _Z_MS3 _Z_CS

^~~~~~~~~~~~

Marlin\src\pins/sensitive_pins.h:523:19: note: in expansion of macro '_Z_PINS'

_X_PINS _Y_PINS _Z_PINS _X2_PINS _Y2_PINS _Z2_PINS _Z3_PINS _Z_PROBE \

^~~~~~~

Marlin\src\Marlin.cpp:261:49: note: in expansion of macro 'SENSITIVE_PINS'

static const pin_t sensitive_pins[] PROGMEM = SENSITIVE_PINS;

^~~~~~~~~~~~~~

compilation terminated due to -fmax-errors=5.

*** [.pioenvs\STM32F1\src\src\Marlin.cpp.o] Error 1

 [ERROR] Took 7.56 seconds 




 [SUMMARY] 

Environment megaatmega2560      	[SKIP]

Environment megaatmega1280      	[SKIP]

Environment at90usb1286_cdc     	[SKIP]

Environment at90usb1286_dfu     	[SKIP]

Environment DUE                 	[SKIP]

Environment DUE_USB             	[SKIP]

Environment DUE_debug           	[SKIP]

Environment LPC1768             	[SKIP]

Environment LPC1769             	[SKIP]

Environment melzi               	[SKIP]

Environment melzi_optiboot      	[SKIP]

Environment rambo               	[SKIP]

Environment sanguino_atmega644p 	[SKIP]

Environment sanguino_atmega1284p	[SKIP]

Environment STM32F1             	[ERROR]

Environment STM32F4             	[SKIP]

Environment ARMED               	[SKIP]

Environment mks_robin           	[SKIP]

Environment teensy35            	[SKIP]

Environment malyanm200          	[SKIP]

Environment esp32               	[SKIP]

Environment fysetc_f6_13        	[SKIP]

Environment linux_native        	[SKIP]

 [ERROR] Took 7.56 seconds 


Board name: BOARD_MKS_ROBIN
Build type: build
Environment used: STM32F1
2019-03-25 11:46:43.365000
```

**Comment by dekra54** [comment]
Would be interesting to see a solution for this problem.
I have similar issues with the stm32h743 i'm working on.

**Comment by Injineers** [comment]
I think all STMs are broken atm w/ the newest in platformio/.

some have said they were able to get it to run using ver 4.x of the STM, but i didnt have any luck

I am trying to compile for the Malyan/MP Select mini board & get a atomic.h or a boards.h error...

**Comment by zillarob** [comment]
Watching like a hawk also.

The hacked up version of Marlin that MKS has locked down for Robin is just a crippled mess. And it looks like its an older version also.

![mkswtf](https://user-images.githubusercontent.com/42916376/54957519-6481ea80-4f29-11e9-9d76-d2afc82ce2ac.JPG)

**Comment by pinchies** [comment]
I have a working marlin 2.0 build on STM32F103ZET6, for a JGAurora board, that is very very similar in architecture to the MKS Robin board.

To compile at the moment (with LCD support), you need to do these things:

Change the platform in "platformio.ini" for the mks_robin enviroment:
"**platform      = ststm32@5.1.0**"

Also in that section of the file, insert a new line _after_ "build_flags   = !...":
" **-DSTM32_XL_DENSITY "**

In the file "/Marlin/src/HAL/HAL_STM32F1/fastio_STM32F1.h", change the line:
"**#define PWM_PIN(P)              digitalPinHasPWM(P)**"
to
"**#define PWM_PIN(P)              1 //digitalPinHasPWM(P)**"

That should get you a working build 👍  Let me know how you go!

**Comment by pinchies** [comment]
Trying to build with STSTM32 5.2 or newer fails for me when including the LCD due to this [unresolved C/C++ compiler issue with the U8glib library](https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/164):
**"wirish_math.h:50:6: error: conflicting types for 'random'"**

If you disable ALL the U8glib library references, then following the above steps will also work on STSTM32 5.2.0, 5.2.0 **and the latest STSTM32 build**, which you can access with:
platform = https://github.com/platformio/platform-ststm32.git

**Comment by jmz52** [comment]
@zillarob 
Firmware you were looking at is for new MKS Robin2 board based on STM32F407ZET6.
It will not run on MKS Robin v2.x boards based on STM32F103ZET6.
Original firmware for MKS Robin v2.x is based on Repetier firmware, not on Marlin.

**Comment by zillarob** [comment]
@jmz52 
Robin Nano F103VET6 Iirc.

Been following your work and hoping that someday that board can run a legit fw.
I see the board your are working on has the same chip so hoping something in there is compatible and makes this a lil easier. New to the 32bit stuff and much of the behind the scenes stuff is just over my head =D

ETA Bummer, just realized yours is not an F103. Hopes and dreams, dashed on the rocks lol

**Comment by pinchies** [comment]
@zillarob I wouldn't worry - VET6 should be well supported in the (perhaps near?) future. Both [Geeetech's GTM32 and Alfawise/Longer3D Motherboards use VET6](https://samuelpinches.com.au/3d-printer/chinese-32-bit-3d-printer-motherboards/), both of those are currently actively work in progress.

**Comment by zillarob** [comment]
Great to hear Sam! Thank you for the heads up =)

**Comment by AlexanderAmelkin** [comment]
Why do we need the U8glib library at all? It appears that it's used whenever `REPRAP_DISCOUNT_SMART_CONTROLLER` is used in `Configuration.h`.
I thought U8glib was for matrix displays (TFTs and OLEDs) while RepRap Discount Smart Controller has a usual chargen HD44780-based display.

Anyway, that library is actively using C++ code in files ending with `.c` and `.h` which confuses VScode (and Atom as well), so they fail to compile complaining like `unknown type 'bool'` or `unknown type 'class'`. I'd say that's a bug in U8glib. So I'd prefer to completely get rid of that lib.

**Comment by jmz52** [comment]
@AlexanderAmelkin 
U8glib is needed to display 12864 UI (upscaled  to 256x128) on MKS Robin TFT display.
If you are using 2004 display you can add u8glib to lib_ignore list.

Marlin uses patched version of u8glib that can be compiled for STM32.
https://github.com/MarlinFirmware/U8glib-HAL/tree/dev
Note: you might have to wait until PR https://github.com/MarlinFirmware/U8glib-HAL/pull/6 is merged.

**Comment by jmz52** [comment]
@Exquisitism
One more thing - according to your logs you were using 'STM32F1' environment and 'genericSTM32F103RE' board.
MKS Robin has F103ZE MCU not the F103RE. F103RE does not have some of the pins used in pins_MKS_ROBIN.h file.
There is 'mks_robin' build environment pre-configured for MKS Robin board.

**Comment by AlexanderAmelkin** [comment]
@jmz52, that's because I'm not building for MKS Robin :)
I'm trying (without much success so far) to port Marlin to Geeetech Rostock 301 (GTM32_PRO_VB).

Oh, wait... you weren't addressing me. Nonetheless, the compilation problem affected me too.
