### PR TITLE
🩹 Fix FTM_DYNAMIC_FREQ build error with FTM_SHAPER_Z/E

### LINKED ISSUE #28548: [BUG] FTM_DYNAMIC_FREQ build error after PR #28509
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When defining `#define FTM_DYNAMIC_FREQ` together with `#define FTM_SHAPER_Z` and/or `#define FTM_SHAPER_E` Marlin is unable to build successfully. I think this error first appeared after PR #28509.

### Bug Timeline

Since PR #28509

### Expected behavior

Build successfully

### Actual behavior

Building Marlin fails with following Problems:
`'const ft_shaped_xy_float_t {aka const struct FTShapedAxesXY<float>}' has no member named 'Z'`
`'const ft_shaped_xy_float_t {aka const struct FTShapedAxesXY<float>}' has no member named 'E'`

And here is the Terminal output:
```
Processing mega2560 (board: megaatmega2560; platform: atmelavr@~4.0.1; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/megaatmega2560.html
PLATFORM: Atmel AVR (4.0.1) > Arduino Mega or Mega 2560 ATmega2560 (Mega 2560)
HARDWARE: ATMEGA2560 16MHz, 8KB RAM, 248KB Flash
DEBUG: Current (avr-stub) External (avr-stub, simavr)
PACKAGES: 
 - framework-arduino-avr @ 5.1.0 
 - toolchain-atmelavr @ 1.70300.191015 (7.3.0)
Converting Marlin.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 5 compatible libraries
Scanning dependencies...
Dependency Graph
|-- Wire @ 1.0
Building in release mode
Compiling .pio\build\mega2560\src\src\HAL\AVR\HAL.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\AVR\HAL_SPI.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\AVR\MarlinSerial.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\AVR\Servo.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\AVR\eeprom.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\AVR\fast_pwm.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\AVR\registers.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\AVR\u8g\u8g_com_HAL_AVR_sw_spi.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\shared\Delay.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\shared\HAL.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\shared\MinSerial.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\shared\eeprom_api.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\shared\esp_wifi.cpp.o
Compiling .pio\build\mega2560\src\src\HAL\shared\servo.cpp.o
Compiling .pio\build\mega2560\src\src\MarlinCore.cpp.o
Compiling .pio\build\mega2560\src\src\core\serial.cpp.o
Compiling .pio\build\mega2560\src\src\core\utility.cpp.o
Compiling .pio\build\mega2560\src\src\feature\host_actions.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\calibrate\G28.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\config\M200-M205.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\config\M220.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\config\M221.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\config\M301.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\config\M302.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\config\M92.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M108_M112_M410.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M111.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M120_M121.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M17_M18_M84.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M211.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M80_M81.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M85.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\control\M999.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\eeprom\M500-M504.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\feature\advance\M900.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\feature\ft_motion\M493.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\feature\ft_motion\M494.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\gcode.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\gcode_d.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\geometry\G92.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\geometry\M206_M428.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\host\M110.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\host\M113.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\host\M114.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\host\M115.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\host\M118.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\host\M119.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\host\M876.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\motion\G0_G1.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\motion\G2_G3.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\motion\G4.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\motion\M400.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\parser.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\queue.cpp.o
Compiling .pio\build\mega2560\src\src\gcode\stats\M31.cpp.o
In file included from Marlin\src\gcode\feature\ft_motion\../../../inc/MarlinConfigPre-1-axes.h:40:0,
                 from Marlin\src\gcode\feature\ft_motion\../../../inc/Conditionals-1-axes.h:32,
                 from Marlin\src\gcode\feature\ft_motion\../../../inc/MarlinConfigPre.h:46,
                 from Marlin\src\gcode\feature\ft_motion\../../../inc/MarlinConfigPre-5-post.h:24,
                 from Marlin\src\gcode\feature\ft_motion\../../../inc/Conditionals-5-post.h:32,
                 from Marlin\src\gcode\feature\ft_motion\../../../inc/MarlinConfigPre-6-type.h:24,
                 from Marlin\src\gcode\feature\ft_motion\../../../inc/Conditionals-6-type.h:33,
                 from Marlin\src\gcode\feature\ft_motion\../../../inc/MarlinConfig.h:41,
                 from Marlin\src\gcode\feature\ft_motion\M493.cpp:23:
Marlin\src\gcode\feature\ft_motion\M493.cpp: In static member function 'static void GcodeSuite::M493_report(bool)':
Marlin\src\gcode\feature\ft_motion\../../../module/ft_motion/shaping.h:52:70: error: 'const ft_shaped_xy_float_t {aka const struct FTShapedAxesXY<float>}' has no member named 'Z'
   #define SHAPED_AXIS_NAMES       XY_LIST(X, Y) OPTARG(FTM_SHAPER_Z, Z) OPTARG(FTM_SHAPER_E, E)
                                                                      ^
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:686:24: note: in definition of macro 'EVAL1'
 #define EVAL1(V...)    V
                        ^
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:684:24: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:684:30: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:683:24: note: in expansion of macro 'EVAL4'
 #define EVAL8(V...)    EVAL4(EVAL4(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:684:24: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                        ^~~~~
Compiling .pio\build\mega2560\src\src\gcode\stats\M75-M78.cpp.o
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:684:30: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:683:30: note: in expansion of macro 'EVAL4'
 #define EVAL8(V...)    EVAL4(EVAL4(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:682:24: note: in expansion of macro 'EVAL8'
 #define EVAL16(V...)   EVAL8(EVAL8(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:684:24: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:684:30: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:683:24: note: in expansion of macro 'EVAL4'
 #define EVAL8(V...)    EVAL4(EVAL4(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:684:24: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:684:30: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:683:30: note: in expansion of macro 'EVAL4'
 #define EVAL8(V...)    EVAL4(EVAL4(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:682:30: note: in expansion of macro 'EVAL8'
 #define EVAL16(V...)   EVAL8(EVAL8(V))
                              ^~~~~
Marlin\src\gcode\feature\ft_motion\M493.cpp:157:7: note: in expansion of macro 'F_REPORT'
       F_REPORT(A) \
       ^~~~~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:771:3: note: in expansion of macro '_REPORT_M493_AXIS'
   _MAP_OP(A)                       \
   ^~~~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:775:17: note: in expansion of macro '_MAP'
 #define __MAP() _MAP
                 ^~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:673:24: note: in expansion of macro 'EVAL16'
 #define EVAL(V...)     EVAL16(V)
                        ^~~~~~
c:\users\flo\documents\github\marlin\marlin\src\hal\avr\timers.h:102:22: note: in expansion of macro '_IF_1'
 #define _CAT(a,V...) a##V
                      ^
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:775:17: note: in expansion of macro '_MAP'
 #define __MAP() _MAP
                 ^~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:777:22: note: in expansion of macro 'EVAL'
 #define MAP(OP,V...) EVAL(_MAP(OP,V))
                      ^~~~
c:\users\flo\documents\github\marlin\marlin\src\hal\avr\timers.h:102:22: note: in expansion of macro '_IF_1'
 #define _CAT(a,V...) a##V
                      ^
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:777:27: note: in expansion of macro '_MAP'
 #define MAP(OP,V...) EVAL(_MAP(OP,V))
                           ^~~~
Marlin\src\gcode\feature\ft_motion\../../../module/ft_motion/shaping.h:57:35: note: in expansion of macro 'MAP'
   #define SHAPED_MAP(F)           MAP(F, SHAPED_AXIS_NAMES)
                                   ^~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:663:26: note: in expansion of macro 'EMIT'
 #define THIRD(a,b,c,...) c
                          ^
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:212:42: note: in expansion of macro '_OPTARG'
 #define TERN_(O,A)          TERF(O,EMIT)(A)         // OPTION ? 'A' : '<nul>'   ; Usage: TERN_(OPTION, EMITTHIS)
                                          ^
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:221:29: note: in expansion of macro 'TERN_'
 #define OPTARG(O,A...)      TERN_(O,DEFER(_OPTARG)(A))
                             ^~~~~
Marlin\src\gcode\feature\ft_motion\../../../module/ft_motion/shaping.h:52:49: note: in expansion of macro 'OPTARG'
   #define SHAPED_AXIS_NAMES       XY_LIST(X, Y) OPTARG(FTM_SHAPER_Z, Z) OPTARG(FTM_SHAPER_E, E)
                                                 ^~~~~~
Marlin\src\gcode\feature\ft_motion\../../../module/ft_motion/shaping.h:57:42: note: in expansion of macro 'SHAPED_AXIS_NAMES'
   #define SHAPED_MAP(F)           MAP(F, SHAPED_AXIS_NAMES)
                                          ^~~~~~~~~~~~~~~~~
Marlin\src\gcode\feature\ft_motion\M493.cpp:162:3: note: in expansion of macro 'SHAPED_MAP'
   SHAPED_MAP(_REPORT_M493_AXIS);
   ^~~~~~~~~~
Marlin\src\gcode\feature\ft_motion\../../../module/ft_motion/shaping.h:52:94: error: 'const ft_shaped_xy_float_t {aka const struct FTShapedAxesXY<float>}' has no member named 'E'
   #define SHAPED_AXIS_NAMES       XY_LIST(X, Y) OPTARG(FTM_SHAPER_Z, Z) OPTARG(FTM_SHAPER_E, E)
                                                                                              ^
Compiling .pio\build\mega2560\src\src\gcode\temp\M104_M109.cpp.o
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:686:24: note: in definition of macro 'EVAL1'
 #define EVAL1(V...)    V
                        ^
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:684:24: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:684:30: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:683:24: note: in expansion of macro 'EVAL4'
 #define EVAL8(V...)    EVAL4(EVAL4(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:684:24: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:684:30: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:683:30: note: in expansion of macro 'EVAL4'
 #define EVAL8(V...)    EVAL4(EVAL4(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:682:24: note: in expansion of macro 'EVAL8'
 #define EVAL16(V...)   EVAL8(EVAL8(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:684:24: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:684:30: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:683:24: note: in expansion of macro 'EVAL4'
 #define EVAL8(V...)    EVAL4(EVAL4(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:684:24: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:24: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                        ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:685:30: note: in expansion of macro 'EVAL1'
 #define EVAL2(V...)    EVAL1(EVAL1(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:684:30: note: in expansion of macro 'EVAL2'
 #define EVAL4(V...)    EVAL2(EVAL2(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:683:30: note: in expansion of macro 'EVAL4'
 #define EVAL8(V...)    EVAL4(EVAL4(V))
                              ^~~~~
Marlin\src\gcode\feature\ft_motion\M493.cpp:157:7: note: in expansion of macro 'F_REPORT'
       F_REPORT(A) \
       ^~~~~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:771:3: note: in expansion of macro '_REPORT_M493_AXIS'
   _MAP_OP(A)                       \
   ^~~~~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:775:17: note: in expansion of macro '_MAP'
 #define __MAP() _MAP
                 ^~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:682:30: note: in expansion of macro 'EVAL8'
 #define EVAL16(V...)   EVAL8(EVAL8(V))
                              ^~~~~
c:\users\flo\documents\github\marlin\marlin\src\hal\avr\timers.h:102:22: note: in expansion of macro '_IF_1'
 #define _CAT(a,V...) a##V
                      ^
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:775:17: note: in expansion of macro '_MAP'
 #define __MAP() _MAP
                 ^~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:673:24: note: in expansion of macro 'EVAL16'
 #define EVAL(V...)     EVAL16(V)
                        ^~~~~~
c:\users\flo\documents\github\marlin\marlin\src\hal\avr\timers.h:102:22: note: in expansion of macro '_IF_1'
 #define _CAT(a,V...) a##V
                      ^
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:775:17: note: in expansion of macro '_MAP'
 #define __MAP() _MAP
                 ^~~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:777:22: note: in expansion of macro 'EVAL'
 #define MAP(OP,V...) EVAL(_MAP(OP,V))
                      ^~~~
c:\users\flo\documents\github\marlin\marlin\src\hal\avr\timers.h:102:22: note: in expansion of macro '_IF_1'
 #define _CAT(a,V...) a##V
                      ^
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:777:27: note: in expansion of macro '_MAP'
 #define MAP(OP,V...) EVAL(_MAP(OP,V))
                           ^~~~
Marlin\src\gcode\feature\ft_motion\../../../module/ft_motion/shaping.h:57:35: note: in expansion of macro 'MAP'
   #define SHAPED_MAP(F)           MAP(F, SHAPED_AXIS_NAMES)
                                   ^~~
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:663:26: note: in expansion of macro 'EMIT'
 #define THIRD(a,b,c,...) c
                          ^
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:212:42: note: in expansion of macro '_OPTARG'
 #define TERN_(O,A)          TERF(O,EMIT)(A)         // OPTION ? 'A' : '<nul>'   ; Usage: TERN_(OPTION, EMITTHIS)
                                          ^
c:\users\flo\documents\github\marlin\marlin\src\core\macros.h:221:29: note: in expansion of macro 'TERN_'
 #define OPTARG(O,A...)      TERN_(O,DEFER(_OPTARG)(A))
                             ^~~~~
Marlin\src\gcode\feature\ft_motion\../../../module/ft_motion/shaping.h:52:73: note: in expansion of macro 'OPTARG'
   #define SHAPED_AXIS_NAMES       XY_LIST(X, Y) OPTARG(FTM_SHAPER_Z, Z) OPTARG(FTM_SHAPER_E, E)
                                                                         ^~~~~~
Marlin\src\gcode\feature\ft_motion\../../../module/ft_motion/shaping.h:57:42: note: in expansion of macro 'SHAPED_AXIS_NAMES'
   #define SHAPED_MAP(F)           MAP(F, SHAPED_AXIS_NAMES)
                                          ^~~~~~~~~~~~~~~~~
Marlin\src\gcode\feature\ft_motion\M493.cpp:162:3: note: in expansion of macro 'SHAPED_MAP'
   SHAPED_MAP(_REPORT_M493_AXIS);
   ^~~~~~~~~~
*** [.pio\build\mega2560\src\src\gcode\feature\ft_motion\M493.cpp.o] Error 1
=============================================================================================== [FAILED] Took 3.02 seconds ===============================================================================================

Environment    Status    Duration
-------------  --------  ------------
mega2560       FAILED    00:00:03.015
========================================================================================= 1 failed, 0 succeeded in 00:00:03.015 =========================================================================================

 *  The terminal process "C:\Users\Flo\.platformio\penv\Scripts\platformio.exe 'run', '--environment', 'mega2560'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

```

### Steps to Reproduce

1. Create new Branch
2. uncomment `#define FT_MOTION`
3. uncomment `#define FTM_DYNAMIC_FREQ`
4. uncomment `#define FTM_SHAPER_Z` and/or `#define FTM_SHAPER_E`
5. Build

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Custom CoreXY

### Electronics

BIGTREETECH GTR V1.0

### LCD/Controller

BIGTREETECH TFT35 V3.0

### Other add-ons

_No response_

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Other (explain below)

### Host Software

OctoPrint

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Config.zip](https://github.com/user-attachments/files/31639162/Config.zip)

### PR DESCRIPTION
**Pull request by thinkyhead**
### Description

Fixes #28548. `M493_report()` used the generic `SHAPED_MAP` (which iterates all shaped axes: X, Y, Z, E) to print each axis's Dynamic Frequency scaling value (`c.dynFreqK.A`). PR #28509 made `dynFreqK` XY-only (`ft_shaped_xy_float_t`), so this now fails to compile whenever `FTM_DYNAMIC_FREQ` is combined with `FTM_SHAPER_Z` and/or `FTM_SHAPER_E`, since `FTShapedAxesXY` has no `Z` or `E` member:

```
error: 'const ft_shaped_xy_float_t {aka const struct FTShapedAxesXY<float>}' has no member named 'Z'
error: 'const ft_shaped_xy_float_t {aka const struct FTShapedAxesXY<float>}' has no member named 'E'
```

### Fix

Split the M493 report into `SHAPED_XY_MAP` for X/Y (which may include Dynamic Frequency scaling) and a separate, explicit path for Z/E (which never had Dynamic Frequency scaling support — matching the rest of `M493.cpp`, which already treats Z/E individually).

### Testing

Verified locally with `mftest`/`pio` on `mega2560` for all relevant combinations, before and after the fix:

| Config | Before | After |
|---|---|---|
| `FTM_DYNAMIC_FREQ` + `FTM_SHAPER_Z` + `FTM_SHAPER_E` (reported combo) | fails | builds |
| `FTM_DYNAMIC_FREQ` only (XY) | builds | builds |
| `FTM_DYNAMIC_FREQ` + `FTM_SHAPER_Z` only | builds | builds |
| `FTM_DYNAMIC_FREQ` + `FTM_SHAPER_E` only | builds | builds |
| `FTM_DYNAMIC_FREQ` disabled + Z/E enabled | builds | builds |
| Default config (`FT_MOTION` disabled) | builds | builds |

### Requirements

N/A — bug fix only, no new config options.

### Benefits

Restores the ability to build with `FTM_DYNAMIC_FREQ` alongside `FTM_SHAPER_Z`/`FTM_SHAPER_E`, a regression introduced by #28509.

### Related Issues

Fixes #28548

### CODE REVIEW

**Comment by plampix** [comment]
**FTM_DYNAMIC_FREQ + FTM_SHAPER_E only**

Didn't build then, and doesn't build now, though the error message has changed:

```In file included from Marlin/src/gcode/feature/ft_motion/../../../inc/MarlinConfigPre-1-axes.h:40:0,
                 from Marlin/src/gcode/feature/ft_motion/../../../inc/Conditionals-1-axes.h:32,
                 from Marlin/src/gcode/feature/ft_motion/../../../inc/MarlinConfigPre.h:46,
                 from Marlin/src/gcode/feature/ft_motion/../../../inc/MarlinConfigPre-5-post.h:24,
                 from Marlin/src/gcode/feature/ft_motion/../../../inc/Conditionals-5-post.h:32,
                 from Marlin/src/gcode/feature/ft_motion/../../../inc/MarlinConfigPre-6-type.h:24,
                 from Marlin/src/gcode/feature/ft_motion/../../../inc/Conditionals-6-type.h:33,
                 from Marlin/src/gcode/feature/ft_motion/../../../inc/MarlinConfig.h:41,
                 from Marlin/src/gcode/feature/ft_motion/M493.cpp:23:
Marlin/src/gcode/feature/ft_motion/M493.cpp: In static member function 'static void GcodeSuite::M493_report(bool)':
Marlin/src/gcode/feature/ft_motion/M493.cpp:151:7: error: expected primary-expression before ',' token
       , F(" I"), c.zeta.A \
       ^
```

**Comment by thinkyhead** [comment]
Odd, it did build for me once I removed an extra comma in a macro definition. Will give it another pass!

**Comment by thinkyhead** [comment]
Seems fine at this time. If I revert the code before my last commit (restoring the errant comma) it fails the build as you report.

**Comment by plampix** [comment]
No, it's not fine at this time:

```cd /tmp; git clone https://github.com/MarlinFirmware/Marlin.git; cd Marlin; sed -i -e 's;//\(#define FT_MOTION\);\1;' -e 's;//\(#define FTM_DYNAMIC_FREQ\);\1;' -e 's;//\(#define FTM_SHAPER_E\);\1;' Marlin/Configuration_adv.h; pio run```

fails

**Comment by thinkyhead** [comment]
Ah, thanks for specifying `FTM_SHAPER_E`. That was not included in prior tests. Patching now.
