### ISSUE TITLE
STM32F4 Compile error with STM32Generic

### ISSUE THREAD

**Issue by bipsendk** [MarlinFirmware/Marlin#12521]
### Description

Trying to compile Marlin 2.0 with the recommended STM32Generic toolchain as described on the readme.md on https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x/Marlin/src/HAL/HAL_STM32F4

Copying example config file from Marlin/src/config/examples/STM32F4

Running compile in Arduino IDE 1.9.0 returns:

```
C:\Users\xxx\AppData\Local\Temp\arduino_build_419999\sketch\src\HAL\HAL_STM32\watchdog_STM32.cpp:30:25: fatal error: IWatchdog.h: No such file or directory

   #include <IWatchdog.h>

                         ^
compilation terminated.

```

### Steps to Reproduce

1. Install Arduino IDE 1.9.0 beta
2. Download STM32Generic and install according to instructions in c:\users\xxx\Documents\Arduino\hardware\
3. Copy STM32F4 example config to over the standard example config in the same foilder as the ino file
4. Select "BLACK F407VG..." board
5. Select "Black F407VE (v2.0)" as specific board
6. Compile

**Expected behavior:** [What you expect to happen]

Code compile successfully

**Actual behavior:** [What actually happens]

Compile fails:

```
C:\Users\xxx\AppData\Local\Temp\arduino_build_419999\sketch\src\HAL\HAL_STM32\watchdog_STM32.cpp:30:25: fatal error: IWatchdog.h: No such file or directory

   #include <IWatchdog.h>

                         ^
compilation terminated.
```

**Comment by mr-miky** [comment]
The real question is why it uses the HAL of the STM32 core instead of HAL_STM32F4 for the Generic ...

What BOARD did you "define"?

**Comment by bipsendk** [comment]
From configuration.h ?

  #define MOTHERBOARD BOARD_STM32F4

I am just testing with STM32 cores installed from within the IDE, and the updated from Github according to https://github.com/stm32duino/wiki/wiki/Using-git-repository

Board selected: Generic STM32F4 series
Board Part Number: Blue F407VE Mini

So far the com pile runs - no errors yet (will be updated once it completes)

**Comment by mr-miky** [comment]
STM32Generic is not STM32Core (stm32duino)...

**Comment by bipsendk** [comment]
STM32Generic is a spinoff/variuant of STM32Core - unfortunately it looks like STM32Generic isn't updated as often as STM32Duino 

Also, the STM32GENERIC seem to support fewer boards than STM32Core

**Comment by bipsendk** [comment]
![arduino-vet6-board-selection](https://user-images.githubusercontent.com/8531428/48957105-f6b3bb00-ef56-11e8-9cfa-84d0017df2ae.png)

Selected board config with STM32Generic

The question probably is whether the issue is in the Marlin code - or STM32GENRIC

**Comment by mr-miky** [comment]
I do not know what to tell you I'm using STM32 Generic with STM32F407 and compile without problems.
Probably missing some define and because of this it is used the code written for STM32Core (stm32duino).

**Comment by bipsendk** [comment]
I removes the STM32Core stuff - but still get the issue with the wrong HAL...

Does the board selection look OK ?

**Comment by mr-miky** [comment]
Check the log on the Arduino IDE and see what define (-D) does for compiling

**Comment by bipsendk** [comment]
```
C:\\Users\\xxx\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\arm-none-eabi-gcc\\4.8.3-2014q1/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -DF_CPU=168000000L -mthumb **-DSTM32GENERIC** -DRAM_LENGTH=131072 -DFLASH_LENGTH=524288 -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -w -x c++ -E -CC **-DSTM32F4** -DARDUINO=10900 -DARDUINO_BLACK_F407VE -DARDUINO_ARCH_STM32 -DSTM32F407VE -DHSE_VALUE=8000000 -DMENU_USB_SERIAL -DMENU_SERIAL_AUTO=SerialUSB "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\cores\\arduino/stm32" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\cores\\arduino/usb" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\system/CMSIS" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\system/STM32F4/CMSIS_Inc" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\system/STM32F4/CMSIS_Src" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\system/STM32F4/HAL_Inc" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\system/STM32F4/HAL_Src" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\system/STM32F4/stm32_chip" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\cores\\arduino" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\variants\\BLACK_F407VE" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\libraries\\SPI\\src" "C:\\Users\\BRIAN~1.IPS\\AppData\\Local\\Temp\\arduino_build_551349\\sketch\\src\\HAL\\HAL_STM32\\watchdog_STM32.cpp" -o nul
```

**Comment by bipsendk** [comment]
Tried to edit boards.h - to add 
-DSTM32F4 
to compile parameter. Seems like the wrong HAL still is being selected.

```
"C:\\Users\\xxx\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\arm-none-eabi-gcc\\4.8.3-2014q1/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -DF_CPU=168000000L -mthumb **-DSTM32GENERIC** -DRAM_LENGTH=131072 -DFLASH_LENGTH=524288 -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -w -x c++ -E -CC **-DSTM32F4** -DARDUINO=10900 -DARDUINO_BLACK_F407VE -DARDUINO_ARCH_STM32 -DSTM32F407VE -DHSE_VALUE=8000000 **-DSTM32F4** -DMENU_USB_SERIAL -DMENU_SERIAL_AUTO=SerialUSB "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\cores\\arduino/stm32" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\cores\\arduino/usb" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\system/CMSIS" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\system/STM32F4/CMSIS_Inc" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\system/STM32F4/CMSIS_Src" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\system/STM32F4/HAL_Inc" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\system/STM32F4/HAL_Src" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\system/STM32F4/stm32_chip" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\cores\\arduino" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\variants\\BLACK_F407VE" "-IC:\\Users\\xxx\\Documents\\Arduino\\hardware\\STM32GENERIC-master\\STM32\\libraries\\SPI\\src" "C:\\Users\\BRIAN~1.IPS\\AppData\\Local\\Temp\\arduino_build_11173\\sketch\\src\\HAL\\HAL_STM32\\watchdog_STM32.cpp" -o nul
```

**Comment by mr-miky** [comment]
mine: 

-DSTM32F4 -DARDUINO=10802 -DARDUINO_BLACK_F407ZG -DARDUINO_ARCH_STM32  -DSTM32F407ZG -DHSE_VALUE=8000000   -DMENU_SERIAL_AUTO=SerialUSB
-DARDUINO_ARCH_STM32 t

I do not have **-DARDUINO_ARCH_STM32** that almost certainly messes with


```
#elif defined (__ STM32F1__) || defined (TARGET_STM32F1)
   #define HAL_PLATFORM HAL_STM32F1
 >>>>>>> #elif defined (STM32GENERIC) &&defined (STM32F4)
 >>>>>>>>>  #define HAL_PLATFORM HAL_STM32F4**
#elif defined (STM32GENERIC) &&defined (STM32F7)
   #define HAL_PLATFORM HAL_STM32F7
>>>>>>>>>  #elif defined (ARDUINO_ARCH_STM32)
 >>>>>>>>>  #define HAL_PLATFORM HAL_STM32
#elif defined (ARDUINO_ARCH_ESP32)
   #define HAL_PLATFORM HAL_ESP32
#else
```

in platforms.h

First it defines HAL_PLATFORM HAL_STM32F4 and then override it
by defining HAL_PLATFORM HAL_STM32

**Comment by mr-miky** [comment]
Ooppppsss ,

**Comment by mr-miky** [comment]
-DARDUINO_ARCH_STM32 almost certainly messes with

```
#elif defined (__ STM32F1__) || defined (TARGET_STM32F1)
   #define HAL_PLATFORM HAL_STM32F1
#elif defined (STM32GENERIC) &&defined (STM32F4)
   #define HAL_PLATFORM HAL_STM32F4
#elif defined (STM32GENERIC) &&defined (STM32F7)
   #define HAL_PLATFORM HAL_STM32F7
#elif defined (ARDUINO_ARCH_STM32)
   #define HAL_PLATFORM HAL_STM32
#elif defined (ARDUINO_ARCH_ESP32)
   #define HAL_PLATFORM HAL_ESP32
#else

```
in platforms.h

First it defines HAL_PLATFORM HAL_STM32F4 and then override it
by defining HAL_PLATFORM HAL_STM32

try to comment out 
```
#elif defined(ARDUINO_ARCH_STM32)
  #define HAL_PLATFORM HAL_STM32
```

**Now the real question is why it works for me**

**Comment by bipsendk** [comment]
Same result - it still picks the 
src\HAL\HAL_STM32\watchdog_STM32.cpp
file 

Also - the #ifdef / #elif - else if - so if HAL_STM32F4 was defined correctly, it should never consider checking for "if defined (ARDUINO_ARCH_STM32)" ...

Are you using IDE 1.9.0 beta ?

**Comment by bipsendk** [comment]
Could you try to attach your boards.txt and platform.txt from the STM32 catalog? I would like to compare them...

**Comment by mr-miky** [comment]
Stupid test, what happens if you move the folder HAL_STM32 out of project ?

**Comment by bipsendk** [comment]
That gives:

```
In file included from C:\Users\xxx\AppData\Local\Temp\arduino_build_668081\sketch\src\HAL\HAL_STM32F4\HAL.cpp:30:0:

C:\Users\xxx\AppData\Local\Temp\arduino_build_668081\sketch\src\HAL\HAL_STM32F4\HAL.h:58:4: error: #error "Serial port 0 does not exist"

   #error "Serial port 0 does not exist"

```

**Comment by mr-miky** [comment]
change it in configuration.h 

```
/**
 * Select the serial port on the board to use for communication with the host.
 * This allows the connection of wireless adapters (for instance) to non-default port pins.
 * Note: The first serial port (-1 or 0) will always be used by the Arduino bootloader.
 *
 * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
 */
//#define SERIAL_PORT -1
#define SERIAL_PORT 1

/**
```

**Comment by bipsendk** [comment]
Will that put output on the USB port of the card ?

**Comment by mr-miky** [comment]
It would be better to be able to compile everything then complicate it ;-P

You can use. I think you have to enable it when you choose the Black card etc etc

**Comment by mr-miky** [comment]
Arduino IDE: menu tools/usb_interface , select Serial[virtual com port].

**Comment by bipsendk** [comment]
In configuration.h:

#define SERIAL_PORT 1

And

```
In file included from C:\Users\xxx\AppData\Local\Temp\arduino_build_639443\sketch\src\HAL\HAL_STM32F4\HAL.cpp:30:0:

C:\Users\xxx\AppData\Local\Temp\arduino_build_639443\sketch\src\HAL\HAL_STM32F4\HAL.h:58:4: error: #error "Serial port 0 does not exist"

   #error "Serial port 0 does not exist"
    ^

```

And serial:

![stm32f4-serial](https://user-images.githubusercontent.com/8531428/48960834-481c7400-ef70-11e8-969c-8dbc8d79862c.png)

**Comment by mr-miky** [comment]
Are you sure you have modified the right config.h, not the one between the examples?

If I remember correctly config.h and config_adv.h both go on the same dir of marlin.ino

**Comment by bipsendk** [comment]
The file edited was the one in the same folder as Marlin.ino

**Comment by mr-miky** [comment]
> in platforms.h
> 
> First it defines HAL_PLATFORM HAL_STM32F4 and then override it
> by defining HAL_PLATFORM HAL_STM32
> 
> try to comment out
> 
> ```
> #elif defined(ARDUINO_ARCH_STM32)
>   #define HAL_PLATFORM HAL_STM32
> ```
> 
> **Now the real question is why it works for me**

Wow,
it is logical that it works, the #elif following the one with the match are no longer considered.
Maybe I need to sleep a little ...

**Comment by mr-miky** [comment]
Ok, 
I have compiled everything on another computer.
Arduino IDE 1.85, STM32Generic, BLACK407ZG demo.
The only things I had to do are:

Remove the servo library folder from the arduino suite.
Remove the HAL_STM32 from the sources.

For safety, if you edit files from outside the Arduino IDE, close and reopen the project

The build ends successfully

**Comment by mr-miky** [comment]
the problem should be caused by

`#ifdef ARDUINO_ARCH_STM32`

that are in all the .cpp files in HAL_STM32

In both STM32Generic and STM32Core is  "true" so if you build using STM32Generic, the code for STM32Core is also build and then fails miserably.

The opposite should not happen because in HAL_STM32F4 is present

`#if defined (STM32GENERIC) && (defined (STM32F4) || defined (STM32F4xx))`

which is erroneous because STM32GENERIC does not define STM32F4xx but still imposes a condition defined(STM32GENERIC) that prevents to build the code with STM32 Core.

In HAL_STM32F7 it is even easier because it is only checked if STM32F7 is defined, which only STM32GENERIC does. STM32Core defines STM32F7xx and STM32F4xx not STM32F7 STM32F4

**Comment by hasenbanck** [comment]
Oh, did we broke the old STM32F4 HAL by using "ARDUINO_ARCH_STM32" to check for the "official" STM32 core? Geez, I was under the impression that the STM32GNERIC only sets STM32GENERIC and not ARDUINO_ARCH_STM32.

You could try to fix the STM32F4 HAL so that it compiles again of course (and of course turn in a PR to fix the issue), but in the long run, the STM32F4 HAL will phase out in favor of the STM32 HAL. The only issue right now left for the "official" STM32 core is the missing VCOM/CDC support. There is a branch by me that fixes the issue temporarily, but in the next major release we will have official support for that feature (v1.5).

I would advise you to use the STM32 HAL instead and write your own pin definition for the F4 board you use since maybe the core already support your board as a variant inside the core: https://github.com/stm32duino/Arduino_Core_STM32

**Comment by bipsendk** [comment]
Trying to compile using the official STM32 Core just gives a whole bunch of other errors. As far as I remember, the right board already exists in the STM32 Core, but there is probably some conflicts between the Marlin HALs and whatever is present in STM32 Core....

**Comment by hasenbanck** [comment]
If you mean compiling the #define MOTHERBOARD BOARD_STM32F4 board definition with the "official" core, that would be to be expected, since it targets the STM32F4 HAL. You would need to update those pin definition and other parts for that board in Marlin for use the STM32 HAL and the "official" core. Or you create a brand new pin definition for your board.

**Comment by bipsendk** [comment]
If the target of Marlin 2.0 is to be able to compile using the STM32 Core package for STM32 based packages, I might just wait until at least the basic compilation runs OK. Modifying an existing pins file is not the biggest challenge - introducing a new board type is a bit more complicated (for me, at least). I know how to handle the hardware, and modify the pins.h/configuration.h - but I am not a programmer, and my only experience with git is to clone stuff down to my own PC to compile it. Pull/merge operations (as I think some of them are called) are not something I have experience with :-)

**Comment by mr-miky** [comment]
Unfortunately, the example configuration for STM32F4 in marlin, at present, is made with the pin definitions of stm32generic, PA0, PA1 etc etc ... therefore, in theory, it was easier to use STM32Generic to have something that at least turns on.

I do not understand why the developers of STM32 Core continue to ignore the need to have a generic board definition with the pins mapped 1 to 1 without that damned translation of arduino pins.

Personally I continue to use the GENERIC because, despite all the problems it has (and to understand certain it took me days to figure out what was wrong), I managed to make everything work but, above all, I do not want to define a board just for my pcb and redo all the definition of the pins since in all STM32 schematics is reported PA0 and not D0, A13, D44 ...

**Comment by hasenbanck** [comment]
The "official" core allows the usage of generic GPIO port names (PA0 etc)
for quite some time now. So you are free to use those in your pin
definition file with the STM32 HAL. Have a look at pins_ARMED.h for example.

**Comment by mr-miky** [comment]
@hasenbanck 

Can I ask you something that has little to do with marlin?

Can you make STM32 firmware updates via octoprint plugin?

**Comment by hasenbanck** [comment]
I don't think there is a plug-in for that yet. Recently I extended
stm32flash to be able to flash using SPI, which will be helpful for my next
board. Sooner or later I want to write an octoprint plug-in for stm32flash.

**Comment by mr-miky** [comment]
I can get the STM32F4 into bootloader mode via software through a specific menu / command of marlin but then I do not know how to do the upload by octoprint since it lacks the specific plugin for the stm32 firmware. It should be simple but it need stm32flash for ARM
  I was hoping you did it ;-)

**Comment by mr-miky** [comment]
I took a look at pins_ARMED.h and they use PA0 PA1 et etc.

This works because they wrote a variant.cpp / varriant.h that maps the PAx pins in PA_x, which in my view is ridiculous.

**Comment by hasenbanck** [comment]
It's not ridiculous at all. At least not in the context of the STM32
arduino core. Variant definitions are needed for STM32 systems, since they
are highly flexible and need a lot of configuration.

You are free to write / propose a better solution and bring it upstream
into the core. Frederic (maintainer of the core) is always open for
improvements.

**Comment by Phr3d13** [comment]
Just my two cents, but with all the board schematics and chip data sheets that I've looked at for stm32 variants, most (if not all) of them default to PA0, etc. You have to remember that, with these boards, you're stepping away from the generic avr structure to a generic stm32 structure.

**Comment by mr-miky** [comment]
What I mean to say is that it should be the opposite, that is, map the arduino pins on the standard stm32 pin.

If I do not care to use the names of the arduino pins, I access directly without going through the mapping, PA0 is PA0 and D44 will be translated(slowly) through PinName digitalPin [];

**Comment by boelle** [comment]
@bipsendk problem gone?

**Comment by bipsendk** [comment]
@boelle - I will just check with VSCode and Arduino IDE to verify...

**Comment by boelle** [comment]
thanks, we need to get the list of issue as small we can, so only real and active issues are open :-D

**Comment by bipsendk** [comment]
@boelle  - Seems like my compile attempt in VScode still fails - not sure whether it is caused by issues in my configuration.h file....

In file included from Marlin\src\HAL\HAL_STM32F4\HAL.cpp:30:0:
Marlin\src\HAL\HAL_STM32F4\HAL.h:58:4: error: #error "Serial port 0 does not exist"
#error "Serial port 0 does not exist"

But in configuration.h I have serial port set to -1 ....

I will try with Arduino IDE 1.9.0 beta next...

[stm32f4-config.zip](https://github.com/MarlinFirmware/Marlin/files/2891201/stm32f4-config.zip)

**Comment by boelle** [comment]
and you use bugfix 2.0? sorry i had to ask, a lot use old versions still

**Comment by bipsendk** [comment]
@boelle Just tried in Arduino IDE 1.8.5 - with a git pull from February 21st.
I get a compile error with:

```
In file included from C:\Users\BRIAN\AppData\Local\Temp\arduino_build_912204\sketch\src\lcd\dogm\status_screen_DOGM.cpp:32:0:

C:\Users\BRIAN\AppData\Local\Temp\arduino_build_912204\sketch\src\lcd\dogm\dogm_Statusscreen.h:30:20: fatal error: binary.h: No such file or directory

 #include <binary.h>
                    ^
compilation terminated.

```

This is with MKS_MINI_12864 defined as display.

**Comment by bipsendk** [comment]
With 

#define SERIAL_PORT 1

and no LCD defined, I get:

```
In file included from C:\Users\BRIAN\AppData\Local\Temp\arduino_build_912204\sketch\src\HAL\HAL_STM32F4\HAL.cpp:30:0:

C:\Users\BRIAN\AppData\Local\Temp\arduino_build_912204\sketch\src\HAL\HAL_STM32F4\HAL.h:58:4: error: #error "Serial port 0 does not exist"

   #error "Serial port 0 does not exist"

    ^


```

and

```
exit status 1
Error compiling for board BLACK F407VG/VE/ZE/ZG boards.
```

This is with STM32 v1.5.0 installed (pulled from github)
I wonder why my defined SERIAL_PORT 1 suddenly is set to 0 ?

**Comment by boelle** [comment]
same with ide 1.9 ?

**Comment by bipsendk** [comment]
Same error with IDE 1.9 beta - serial port 0 does not exist.

Both IDE´s uses the same STM32Generic toolchain installed in %AppData%\Local\Arduino15

**Comment by bipsendk** [comment]
I discovered I had multiple STM32-generic's floating around (in docuemnts folder, appdata and so on). I will just clean up and try from scratch...

**Comment by boelle** [comment]
we have all been there :-D

**Comment by boelle** [comment]
maybe look in to vs code and platform io ? it has helped me in the way that i dont need to think about having the right lib's etc

but of course its a new tool to learn

**Comment by bipsendk** [comment]
Not having great success with VScode and PlatformIO,...

Here I also see:

In file included from Marlin\src\HAL\HAL_STM32F4\HAL.cpp:30:0:
Marlin\src\HAL\HAL_STM32F4\HAL.h:58:4: error: #error "Serial port 0 does not exist"
#error "Serial port 0 does not exist"
^~~~~

And this is with:

#define SERIAL_PORT -1

in configuration.h 

Build-log attached.

[stm32f4-vscode-buildlog.txt](https://github.com/MarlinFirmware/Marlin/files/2893719/stm32f4-vscode-buildlog.txt)

**Comment by boelle** [comment]
@thinkyhead you are the almighty and fearless code god, does it tell you anything?

**Comment by AnHardt** [comment]
Are you sure Marlin is still ought to be compiled with STM32Generic?
I mean to remember on rumor this was switched to the `official` core. But i'm quite unsure about that.

**Comment by mr-miky** [comment]
IMHO, platformio loses some define -D on the command line at compile time.
If I remember well there is something to be defined to enable the serial but I should investigate. For sure with STM32Generic I compile marlin 2.0x but not with platformIO. I currently use the serial 1 connected to the usual FT232 converter and it works ...

**Comment by mr-miky** [comment]
`"/home/michele/Arduino/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-gcc" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -DF_CPU=168000000L -mthumb -DSTM32GENERIC -DRAM_LENGTH=131072 -DFLASH_LENGTH=1232896 -c -g -MMD -O1 -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -MMD -DSTM32F4 -DARDUINO=10802 -DARDUINO_BLACK_F407ZG -DARDUINO_ARCH_STM32  -DSTM32F407ZG -DHSE_VALUE=8000000   -DMENU_SERIAL_AUTO=SerialUSB  "-I/home/michele/Arduino/hardware/STM32GENERIC/STM32/cores/arduino/stm32" "-I/home/michele/Arduino/hardware/STM32GENERIC/STM32/cores/arduino/usb" "-I/home/michele/Arduino/hardware/STM32GENERIC/STM32/system/CMSIS" "-I/home/michele/Arduino/hardware/STM32GENERIC/STM32/system/STM32F4/CMSIS_Inc" "-I/home/michele/Arduino/hardware/STM32GENERIC/STM32/system/STM32F4/CMSIS_Src" "-I/home/michele/Arduino/hardware/STM32GENERIC/STM32/system/STM32F4/HAL_Inc" "-I/home/michele/Arduino/hardware/STM32GENERIC/STM32/system/STM32F4/HAL_Src"  "-I/home/michele/Arduino/hardware/STM32GENERIC/STM32/system/STM32F4/stm32_chip"   -I"/home/michele/Arduino/hardware/STM32GENERIC/STM32/cores/arduino" -I"/home/michele/Arduino/hardware/STM32GENERIC/STM32/variants/BLACK_F407ZG" -I"/home/michele/Arduino/hardware/STM32GENERIC/STM32/libraries/Servo/src" -I"/home/michele/Arduino/hardware/STM32GENERIC/STM32/libraries/SPI/src" -I"/home/michele/Arduino/hardware/STM32GENERIC/STM32/libraries/stm32_dma/src" -I"/home/michele/Arduino/libraries/U8glib/src" -I"/home/michele/Arduino/libraries/TMCStepper/src" -I"/home/michele/Arduino/hardware/STM32GENERIC/STM32/libraries/Wire/src" -I"/home/michele/Arduino/hardware/STM32GENERIC/STM32/libraries/SDIO/src" -MMD -MP -MF"core/core/usb/msc/usbd_msc_scsi.c.d" -MT"core/core/usb/msc/usbd_msc_scsi.c.o" -D__IN_ECLIPSE__=1 "/home/michele/Arduino/hardware/STM32GENERIC/STM32/cores/arduino/usb/msc/usbd_msc_scsi.c"  -o  "core/core/usb/msc/usbd_msc_scsi.c.o"  -Wno-expansion-to-defined -DU8G_HAL_LINKS -DBOOTLOADER_MENU -DTARGET_STM32F4 -DUSB_OTG_POWER
`
@bipsendk  -DMENU_SERIAL_AUTO=SerialUSB    exists on your configuration ??  

It should be platformio that adds it based on your selections ...
Check if you can see the complete command that is given to compile ..

**Comment by mr-miky** [comment]
@bipsendk 
Ha ha ha...   "il diavolo fa le pentole ma non i coperchi !"  (the devil makes the pots but not the lids !). 
I found out why I do not have that damn mistake.
in    `src/HAL/HAL_STM32F4/HAL.h`

`//Serial override`
`//extern HalSerial usb_serial;`
`#if SERIAL_PORT == 0`
`//  #error "Serial port 0 does not exist"`
`#endif`

`#if !WITHIN(SERIAL_PORT, -1, 6)`
`  #error "SERIAL_PORT must be from -1 to 6"`
`#endif`

if I uncomment it, the build fails with the same error messages
If you do not want to melt the fuse, substitute it with a nail ;-)

**Comment by mr-miky** [comment]
Very interesting,

SERIAL_PORT is clearly 1 and error is still issued ...


![senzanome](https://user-images.githubusercontent.com/12703876/53288077-b0077400-3784-11e9-94c5-e20b68b09a86.jpg)

SERIAL_PORT is at the same time 0 and 1?

**Comment by mr-miky** [comment]
Is it not the case that the control on the serials goes to sanitycheck.h rather than here since the header is also included in other parts such as spi and timers?

How many platforms have the serial 0?

**Comment by mr-miky** [comment]
Since SERIAL_PORT is not defined in spi and timers, can this be an acceptable fix for HAL.h ??

`#ifdef SERIAL_PORT`
`..#if SERIAL_PORT == 0`
`....#error "Serial port 0 does not exist"`
`..#endif`
`..#if !WITHIN(SERIAL_PORT, -1, 6)`
`....#error "SERIAL_PORT must be from -1 to 6"`
`..#endif`
`#endif`

**Comment by bipsendk** [comment]
@mr-miky - The settings in my Arduino IDE regarding the USB part is shown in the attached image.

Seems like the extra define comes from boards.txt ....

![arduinoide-serialusb](https://user-images.githubusercontent.com/8531428/53291244-9ed45c80-37b0-11e9-88ea-07357d38dfb3.png)

From boards.txt:

BLACK_F407XX.menu.upload_method.STLinkMethod.build.extra_flags_serial_auto=-DMENU_SERIAL_AUTO=SerialUSB

**Comment by mr-miky** [comment]
@bipsendk   try to comment out 

// #error "Serial port 0 does not exist"

**Comment by bipsendk** [comment]
@mr-miky - tried the approach with:

`#ifdef SERIAL_PORT`
`..#if SERIAL_PORT == 0`
`....#error "Serial port 0 does not exist"`
`..#endif`
`..#if !WITHIN(SERIAL_PORT, -1, 6)`
`....#error "SERIAL_PORT must be from -1 to 6"`
`..#endif`
`#endif`

Seemed to solve the serial port issue.

Now, when enabling MKS_MINI_12864, I get:

```
In file included from C:\Users\BRIAN\AppData\Local\Temp\arduino_build_211900\sketch\src\lcd\dogm\status_screen_DOGM.cpp:32:0:

C:\Users\BRIAN\AppData\Local\Temp\arduino_build_211900\sketch\src\lcd\dogm\dogm_Statusscreen.h:30:20: fatal error: binary.h: No such file or directory

 #include <binary.h>
                    ^
compilation terminated.
```

Not quite sure what causes this... But commenting it out when compiling for STM32F4 will at least remove the error, and let the compile end successfull... Next step will be to test it on a STM32F4 board...

**Comment by mr-miky** [comment]
as you can see here https://github.com/danieleff/STM32GENERIC/tree/master/STM32/cores/arduino binary.h is missing :-(

**Comment by bipsendk** [comment]
@mr-miky - But a binary.h exists [here](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x/Marlin/src/HAL/HAL_STM32F1) - in STM32F1 HAL folder .. Maybe a work-around ?

**Comment by mr-miky** [comment]
I copied it by taking it from arduino-1.8.5/hardware/arduino/avr/cores/arduino/ and then inserted it in STM32GENERIC/tree/master/STM32/cores/arduino/
However, since you compile everything even without binary.h I think it's not really used.
Probably soon you will have some problems with the pwm, I do not know if it has been fixed in the official version of stm32generic, but there are patches written by someone who wanders around here.

**Comment by thinkyhead** [comment]
See if this helps in `status_screen_DOGM.cpp`…
```cpp
#ifndef B00000000
  #include <binary.h>
#endif
```

**Comment by bipsendk** [comment]
On which line (before/after which existing line in the file) ?

**Comment by bipsendk** [comment]
I se ethe error originatin from dogm_statusscreen.h - maybe I should change

`#include <binary.h>`

to

```
#ifndef B00000000
  #include <binary.h>
#endif

```

**Comment by bipsendk** [comment]
Okay, changing it in dogm_statusscreen.h did not solve the issue:

```
C:\Users\BRIAN\AppData\Local\Temp\arduino_build_883256\sketch\src\lcd\dogm\dogm_Statusscreen.h:32:22: fatal error: binary.h: No such file or directory

   #include <binary.h>
                      ^
compilation terminated.
```

**Comment by mr-miky** [comment]
@thinkyhead     B00000000 is not defined because it is missing binary.h so if you then include it the build fails anyway

Maybe you could put a local copy of binary.h inside HAL_STM32F4 and if B000000 is not defined  just include the binary.h inside HAL_STM32F4 or you could put it in HAL / shared but I think the problem is related only to stm32F4.

**Comment by thinkyhead** [comment]
I believe that this platform might define the binary equivalents in another file, as done by STM32F1. Does one of these includes work?
```cpp
#include "bit_constants.h"
#include <bit_constants.h>
```

**Comment by mr-miky** [comment]
@thinkyhead 

bit_constants.h exists ... see https://github.com/danieleff/STM32GENERIC/tree/master/STM32/cores/arduino
and is included by  Arduino.h

probably that  #include <binary.h> is of no use
