### ISSUE TITLE
[FR] (feature summary)

### ISSUE THREAD

**Issue by ivankillerg** [MarlinFirmware/Marlin#21639]
### Is your feature request related to a problem? Please describe.

MKS TS35 v 2.0 don,t work with btt skr 1.3 

### Are you looking for hardware support?

Marlin 2.0 bugfix layest
btt skr 1.3
mks ts35 v2.0

### Describe the feature you want

I want use ts35 on skr 1.3 but marlin run out "Marlin\src\HAL\LPC1768\tft\tft_spi.h:63:93: error: 'TFT_A0_PIN' was not declared in this scope; did you mean 'TFT_SPI'?"

please bugfix it or write me how solve this problem

**Comment by thisiskeithb** [comment]
Please file a proper [Bug Report](https://github.com/MarlinFirmware/Marlin/issues/new?assignees=&labels=&template=bug_report.yml&title=%5BBUG%5D+%28bug+summary%29).
