### ISSUE TITLE
[BUG] Trinamic errors on compile with older BUGFIX2.0 configuration files

### ISSUE THREAD

**Issue by ISAndreiva** [MarlinFirmware/Marlin#16859]
So using my old BUGFIX2.0 configurations files I get this errors:

<details><summary>Build Output</summary>

```
C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:71:18: error: X_CHAIN_POS was not declared in this scope

   TMC_SPI_DEFINE(X, X);

                  ^

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:49:111: note: in definition of macro __TMC_SPI_DEFINE

   #define __TMC_SPI_DEFINE(IC, ST, L, AI) TMCMarlin<IC##Stepper, L, AI> stepper##ST(ST##_CS_PIN, ST##_RSENSE, ST##_CHAIN_POS)

                                                                                                               ^~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:56:32: note: in expansion of macro _TMC_SPI_DEFINE

 #define TMC_SPI_DEFINE(ST, AI) _TMC_SPI_DEFINE(ST##_DRIVER_TYPE, ST, AI##_AXIS)

                                ^~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:71:3: note: in expansion of macro TMC_SPI_DEFINE

   TMC_SPI_DEFINE(X, X);

   ^~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:71:18: note: suggested alternative: X_MIN_POS

   TMC_SPI_DEFINE(X, X);

                  ^

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:49:111: note: in definition of macro __TMC_SPI_DEFINE

   #define __TMC_SPI_DEFINE(IC, ST, L, AI) TMCMarlin<IC##Stepper, L, AI> stepper##ST(ST##_CS_PIN, ST##_RSENSE, ST##_CHAIN_POS)

                                                                                                               ^~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:56:32: note: in expansion of macro _TMC_SPI_DEFINE

 #define TMC_SPI_DEFINE(ST, AI) _TMC_SPI_DEFINE(ST##_DRIVER_TYPE, ST, AI##_AXIS)

                                ^~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:71:3: note: in expansion of macro TMC_SPI_DEFINE

   TMC_SPI_DEFINE(X, X);

   ^~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:77:18: error: Y_CHAIN_POS was not declared in this scope

   TMC_SPI_DEFINE(Y, Y);

                  ^

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:49:111: note: in definition of macro __TMC_SPI_DEFINE

   #define __TMC_SPI_DEFINE(IC, ST, L, AI) TMCMarlin<IC##Stepper, L, AI> stepper##ST(ST##_CS_PIN, ST##_RSENSE, ST##_CHAIN_POS)

                                                                                                               ^~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:56:32: note: in expansion of macro _TMC_SPI_DEFINE

 #define TMC_SPI_DEFINE(ST, AI) _TMC_SPI_DEFINE(ST##_DRIVER_TYPE, ST, AI##_AXIS)

                                ^~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:77:3: note: in expansion of macro TMC_SPI_DEFINE

   TMC_SPI_DEFINE(Y, Y);

   ^~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:77:18: note: suggested alternative: Y_MIN_POS

   TMC_SPI_DEFINE(Y, Y);

                  ^

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:49:111: note: in definition of macro __TMC_SPI_DEFINE

   #define __TMC_SPI_DEFINE(IC, ST, L, AI) TMCMarlin<IC##Stepper, L, AI> stepper##ST(ST##_CS_PIN, ST##_RSENSE, ST##_CHAIN_POS)

                                                                                                               ^~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:56:32: note: in expansion of macro _TMC_SPI_DEFINE

 #define TMC_SPI_DEFINE(ST, AI) _TMC_SPI_DEFINE(ST##_DRIVER_TYPE, ST, AI##_AXIS)

                                ^~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:77:3: note: in expansion of macro TMC_SPI_DEFINE

   TMC_SPI_DEFINE(Y, Y);

   ^~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:83:18: error: Z_CHAIN_POS was not declared in this scope

   TMC_SPI_DEFINE(Z, Z);

                  ^

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:49:111: note: in definition of macro __TMC_SPI_DEFINE

   #define __TMC_SPI_DEFINE(IC, ST, L, AI) TMCMarlin<IC##Stepper, L, AI> stepper##ST(ST##_CS_PIN, ST##_RSENSE, ST##_CHAIN_POS)

                                                                                                               ^~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:56:32: note: in expansion of macro _TMC_SPI_DEFINE

 #define TMC_SPI_DEFINE(ST, AI) _TMC_SPI_DEFINE(ST##_DRIVER_TYPE, ST, AI##_AXIS)

                                ^~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:83:3: note: in expansion of macro TMC_SPI_DEFINE

   TMC_SPI_DEFINE(Z, Z);

   ^~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:83:18: note: suggested alternative: Z_MIN_POS

   TMC_SPI_DEFINE(Z, Z);

                  ^

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:49:111: note: in definition of macro __TMC_SPI_DEFINE

   #define __TMC_SPI_DEFINE(IC, ST, L, AI) TMCMarlin<IC##Stepper, L, AI> stepper##ST(ST##_CS_PIN, ST##_RSENSE, ST##_CHAIN_POS)

                                                                                                               ^~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:56:32: note: in expansion of macro _TMC_SPI_DEFINE

 #define TMC_SPI_DEFINE(ST, AI) _TMC_SPI_DEFINE(ST##_DRIVER_TYPE, ST, AI##_AXIS)

                                ^~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:83:3: note: in expansion of macro TMC_SPI_DEFINE

   TMC_SPI_DEFINE(Z, Z);

   ^~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:65:47: error: E0_CHAIN_POS was not declared in this scope

   #define TMC_SPI_DEFINE_E(AI) TMC_SPI_DEFINE(E##AI, E)

                                               ^

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:49:111: note: in definition of macro __TMC_SPI_DEFINE

   #define __TMC_SPI_DEFINE(IC, ST, L, AI) TMCMarlin<IC##Stepper, L, AI> stepper##ST(ST##_CS_PIN, ST##_RSENSE, ST##_CHAIN_POS)

                                                                                                               ^~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:56:32: note: in expansion of macro _TMC_SPI_DEFINE

 #define TMC_SPI_DEFINE(ST, AI) _TMC_SPI_DEFINE(ST##_DRIVER_TYPE, ST, AI##_AXIS)

                                ^~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:65:32: note: in expansion of macro TMC_SPI_DEFINE

   #define TMC_SPI_DEFINE_E(AI) TMC_SPI_DEFINE(E##AI, E)

                                ^~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:95:3: note: in expansion of macro TMC_SPI_DEFINE_E

   TMC_SPI_DEFINE_E(0);

   ^~~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:65:47: note: suggested alternative: Z_MIN_POS

   #define TMC_SPI_DEFINE_E(AI) TMC_SPI_DEFINE(E##AI, E)

                                               ^

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:49:111: note: in definition of macro __TMC_SPI_DEFINE

   #define __TMC_SPI_DEFINE(IC, ST, L, AI) TMCMarlin<IC##Stepper, L, AI> stepper##ST(ST##_CS_PIN, ST##_RSENSE, ST##_CHAIN_POS)

                                                                                                               ^~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:56:32: note: in expansion of macro _TMC_SPI_DEFINE

 #define TMC_SPI_DEFINE(ST, AI) _TMC_SPI_DEFINE(ST##_DRIVER_TYPE, ST, AI##_AXIS)

                                ^~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:65:32: note: in expansion of macro TMC_SPI_DEFINE

   #define TMC_SPI_DEFINE_E(AI) TMC_SPI_DEFINE(E##AI, E)

                                ^~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:95:3: note: in expansion of macro TMC_SPI_DEFINE_E

   TMC_SPI_DEFINE_E(0);

   ^~~~~~~~~~~~~~~~

Using library U8glib at version 1.19.1 in folder: C:\Users\Andreiva\Documents\Arduino\libraries\U8glib 
Using library TMCStepper at version 0.6.2 in folder: C:\Users\Andreiva\Documents\Arduino\libraries\TMCStepper 
Using library SPI at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SPI 
Using library SoftwareSerial at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SoftwareSerial 
exit status 1
Error compiling for board Arduino Mega or Mega 2560.
So using my old BUGFIX2.0 configurations files I get this errors:


C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:71:18: error: X_CHAIN_POS was not declared in this scope

   TMC_SPI_DEFINE(X, X);

                  ^

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:49:111: note: in definition of macro __TMC_SPI_DEFINE

   #define __TMC_SPI_DEFINE(IC, ST, L, AI) TMCMarlin<IC##Stepper, L, AI> stepper##ST(ST##_CS_PIN, ST##_RSENSE, ST##_CHAIN_POS)

                                                                                                               ^~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:56:32: note: in expansion of macro _TMC_SPI_DEFINE

 #define TMC_SPI_DEFINE(ST, AI) _TMC_SPI_DEFINE(ST##_DRIVER_TYPE, ST, AI##_AXIS)

                                ^~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:71:3: note: in expansion of macro TMC_SPI_DEFINE

   TMC_SPI_DEFINE(X, X);

   ^~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:71:18: note: suggested alternative: X_MIN_POS

   TMC_SPI_DEFINE(X, X);

                  ^

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:49:111: note: in definition of macro __TMC_SPI_DEFINE

   #define __TMC_SPI_DEFINE(IC, ST, L, AI) TMCMarlin<IC##Stepper, L, AI> stepper##ST(ST##_CS_PIN, ST##_RSENSE, ST##_CHAIN_POS)

                                                                                                               ^~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:56:32: note: in expansion of macro _TMC_SPI_DEFINE

 #define TMC_SPI_DEFINE(ST, AI) _TMC_SPI_DEFINE(ST##_DRIVER_TYPE, ST, AI##_AXIS)

                                ^~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:71:3: note: in expansion of macro TMC_SPI_DEFINE

   TMC_SPI_DEFINE(X, X);

   ^~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:77:18: error: Y_CHAIN_POS was not declared in this scope

   TMC_SPI_DEFINE(Y, Y);

                  ^

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:49:111: note: in definition of macro __TMC_SPI_DEFINE

   #define __TMC_SPI_DEFINE(IC, ST, L, AI) TMCMarlin<IC##Stepper, L, AI> stepper##ST(ST##_CS_PIN, ST##_RSENSE, ST##_CHAIN_POS)

                                                                                                               ^~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:56:32: note: in expansion of macro _TMC_SPI_DEFINE

 #define TMC_SPI_DEFINE(ST, AI) _TMC_SPI_DEFINE(ST##_DRIVER_TYPE, ST, AI##_AXIS)

                                ^~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:77:3: note: in expansion of macro TMC_SPI_DEFINE

   TMC_SPI_DEFINE(Y, Y);

   ^~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:77:18: note: suggested alternative: Y_MIN_POS

   TMC_SPI_DEFINE(Y, Y);

                  ^

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:49:111: note: in definition of macro __TMC_SPI_DEFINE

   #define __TMC_SPI_DEFINE(IC, ST, L, AI) TMCMarlin<IC##Stepper, L, AI> stepper##ST(ST##_CS_PIN, ST##_RSENSE, ST##_CHAIN_POS)

                                                                                                               ^~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:56:32: note: in expansion of macro _TMC_SPI_DEFINE

 #define TMC_SPI_DEFINE(ST, AI) _TMC_SPI_DEFINE(ST##_DRIVER_TYPE, ST, AI##_AXIS)

                                ^~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:77:3: note: in expansion of macro TMC_SPI_DEFINE

   TMC_SPI_DEFINE(Y, Y);

   ^~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:83:18: error: Z_CHAIN_POS was not declared in this scope

   TMC_SPI_DEFINE(Z, Z);

                  ^

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:49:111: note: in definition of macro __TMC_SPI_DEFINE

   #define __TMC_SPI_DEFINE(IC, ST, L, AI) TMCMarlin<IC##Stepper, L, AI> stepper##ST(ST##_CS_PIN, ST##_RSENSE, ST##_CHAIN_POS)

                                                                                                               ^~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:56:32: note: in expansion of macro _TMC_SPI_DEFINE

 #define TMC_SPI_DEFINE(ST, AI) _TMC_SPI_DEFINE(ST##_DRIVER_TYPE, ST, AI##_AXIS)

                                ^~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:83:3: note: in expansion of macro TMC_SPI_DEFINE

   TMC_SPI_DEFINE(Z, Z);

   ^~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:83:18: note: suggested alternative: Z_MIN_POS

   TMC_SPI_DEFINE(Z, Z);

                  ^

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:49:111: note: in definition of macro __TMC_SPI_DEFINE

   #define __TMC_SPI_DEFINE(IC, ST, L, AI) TMCMarlin<IC##Stepper, L, AI> stepper##ST(ST##_CS_PIN, ST##_RSENSE, ST##_CHAIN_POS)

                                                                                                               ^~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:56:32: note: in expansion of macro _TMC_SPI_DEFINE

 #define TMC_SPI_DEFINE(ST, AI) _TMC_SPI_DEFINE(ST##_DRIVER_TYPE, ST, AI##_AXIS)

                                ^~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:83:3: note: in expansion of macro TMC_SPI_DEFINE

   TMC_SPI_DEFINE(Z, Z);

   ^~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:65:47: error: E0_CHAIN_POS was not declared in this scope

   #define TMC_SPI_DEFINE_E(AI) TMC_SPI_DEFINE(E##AI, E)

                                               ^

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:49:111: note: in definition of macro __TMC_SPI_DEFINE

   #define __TMC_SPI_DEFINE(IC, ST, L, AI) TMCMarlin<IC##Stepper, L, AI> stepper##ST(ST##_CS_PIN, ST##_RSENSE, ST##_CHAIN_POS)

                                                                                                               ^~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:56:32: note: in expansion of macro _TMC_SPI_DEFINE

 #define TMC_SPI_DEFINE(ST, AI) _TMC_SPI_DEFINE(ST##_DRIVER_TYPE, ST, AI##_AXIS)

                                ^~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:65:32: note: in expansion of macro TMC_SPI_DEFINE

   #define TMC_SPI_DEFINE_E(AI) TMC_SPI_DEFINE(E##AI, E)

                                ^~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:95:3: note: in expansion of macro TMC_SPI_DEFINE_E

   TMC_SPI_DEFINE_E(0);

   ^~~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:65:47: note: suggested alternative: Z_MIN_POS

   #define TMC_SPI_DEFINE_E(AI) TMC_SPI_DEFINE(E##AI, E)

                                               ^

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:49:111: note: in definition of macro __TMC_SPI_DEFINE

   #define __TMC_SPI_DEFINE(IC, ST, L, AI) TMCMarlin<IC##Stepper, L, AI> stepper##ST(ST##_CS_PIN, ST##_RSENSE, ST##_CHAIN_POS)

                                                                                                               ^~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:56:32: note: in expansion of macro _TMC_SPI_DEFINE

 #define TMC_SPI_DEFINE(ST, AI) _TMC_SPI_DEFINE(ST##_DRIVER_TYPE, ST, AI##_AXIS)

                                ^~~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:65:32: note: in expansion of macro TMC_SPI_DEFINE

   #define TMC_SPI_DEFINE_E(AI) TMC_SPI_DEFINE(E##AI, E)

                                ^~~~~~~~~~~~~~

C:\Users\Andreiva\AppData\Local\Temp\arduino_build_804389\sketch\src\module\stepper\trinamic.cpp:95:3: note: in expansion of macro TMC_SPI_DEFINE_E

   TMC_SPI_DEFINE_E(0);

   ^~~~~~~~~~~~~~~~

Using library U8glib at version 1.19.1 in folder: C:\Users\Andreiva\Documents\Arduino\libraries\U8glib 
Using library TMCStepper at version 0.6.2 in folder: C:\Users\Andreiva\Documents\Arduino\libraries\TMCStepper 
Using library SPI at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SPI 
Using library SoftwareSerial at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SoftwareSerial 
exit status 1
Error compiling for board Arduino Mega or Mega 2560.
```
</details>

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4205772/Marlin.zip)

**Comment by thinkyhead** [comment]
Yes, you'll need to get the latest config files and bring your settings over.

_Please don't file support questions as bug reports. This really bugs some of the maintainers._
