### ISSUE TITLE
[BUG] undefined reference to `MarlinUI::drawPercent()

### ISSUE THREAD

**Issue by CRCinAU** [MarlinFirmware/Marlin#27864]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Compile fails with the following errors:

```
Linking .pio/build/STM32F103RE_creality/firmware.elf

Marlin/src/inc/Warnings.cpp:130:6: warning: #warning "Note: Auto-assigned LCD_SERIAL_PORT. (Define NO_AUTO_ASSIGN_WARNING to suppress this warning.)" [-Wcpp]
  130 |     #warning "Note: Auto-assigned LCD_SERIAL_PORT. (Define NO_AUTO_ASSIGN_WARNING to suppress this warning.)"
      |      ^~~~~~~
/home/marlin/.platformio/packages/toolchain-gccarmnoneeabi@1.90201.191206/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: .pio/build/STM32F103RE_creality/src/src/lcd/marlinui.cpp.o:(.rodata+0x4): undefined reference to `MarlinUI::drawPercent()'
/home/marlin/.platformio/packages/toolchain-gccarmnoneeabi@1.90201.191206/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: .pio/build/STM32F103RE_creality/src/src/lcd/marlinui.cpp.o:(.rodata+0x8): undefined reference to `MarlinUI::drawElapsed()'
/home/marlin/.platformio/packages/toolchain-gccarmnoneeabi@1.90201.191206/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: .pio/build/STM32F103RE_creality/src/src/lcd/marlinui.cpp.o:(.rodata+0xc): undefined reference to `MarlinUI::drawRemain()'
collect2: error: ld returned 1 exit status
*** [.pio/build/STM32F103RE_creality/firmware.elf] Error 1
```

### Bug Timeline

First broke in commit 6cda10de0fa8224c30f86baff50be3b14a1e9e1e

### Expected behavior

Build works

### Actual behavior

Build fails

### Version of Marlin Firmware

bugfix-2.1.x

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/user-attachments/files/20266762/Configuration.zip)

**Comment by thinkyhead** [comment]
I was working on a standard method that alternates the display of elapsed, remaining, and estimated time. The missing methods are included when the flag for their existence is set, depending on display and time-rotation option. Might have missed this for `DWIN_MARLINUI_PORTRAIT`. I'll take a look and see if a PR exists, and if not, I will patch this forthwith.

**Comment by thinkyhead** [comment]
Haha, it is already fixed. I think I'll need a crate of hotdogs for all this catchup!
