### ISSUE TITLE
error compiling v1b1 for ramps 1.3/1.4 on MEGA 2560

### ISSUE THREAD

**Issue by birdmun** [MarlinFirmware/Marlin#40]
I have tried arduino-019, 22, 23, 1.0. ( I know the firmware isn't supposed to compile on 1.0, but, I just wanted to be somewhat thorough in my attempts to get around the problem. )
All four error saying:

In file included from /Sd2Card.h:27,
                 from Sd2Card.cpp:21:
Sd2PinMap.h:42: error: expected unqualified-id before numeric constant
Sd2PinMap.h:43: error: expected unqualified-id before numeric constant

for reference lines 42 and 43:

uint8_t const SS_PIN = 53;    // B0
uint8_t const MOSI_PIN = 51;  // B2

I attempted to comment out the sdcard reader as I am not currently using it. I could not manage to get the compile to complete.

The base download will compile as is, but, as soon as I change MOTHERBOARD to 33 the error occurs.
