### ISSUE TITLE
'EXTRUDERS' was not declared in this scope

### ISSUE THREAD

**Issue by Zangetsu57** [MarlinFirmware/Marlin#510]
When I try to compile with Arduino r23 or 1.0.4, I get the below error:

'EXTRUDERS' was not declared in this scope

In file included from cardreader.cpp:5:
temperature.h:36: error: 'EXTRUDERS' was not declared in this scope
temperature.h:37: error: 'EXTRUDERS' was not declared in this scope
/temperature.h: In function 'float degHotend(uint8_t)':
temperature.h:61: error: 'current_temperature' was not declared in this scope
/temperature.h: In function 'float degTargetHotend(uint8_t)':
temperature.h:69: error: 'target_temperature' was not declared in this scope
/temperature.h: In function 'void setTargetHotend(const float&, uint8_t)':
temperature.h:77: error: 'target_temperature' was not declared in this scope
/temperature.h: In function 'bool isHeatingHotend(uint8_t)':
temperature.h:85: error: 'target_temperature' was not declared in this scope
temperature.h:85: error: 'current_temperature' was not declared in this scope
/temperature.h: In function 'bool isCoolingHotend(uint8_t)':
temperature.h:93: error: 'target_temperature' was not declared in this scope
temperature.h:93: error: 'current_temperature' was not declared in this scope
