### ISSUE TITLE
Fysteclcd dgus with mks 1.4  problem

### ISSUE THREAD

**Issue by manarsak** [MarlinFirmware/Marlin#16931]
Hi, I have a mks1. 4 board and I want to connect a fystec lcd screen when downloading the program. I see this message. I have a problem, I have another question. What are the appropriate settings for the screen to work and what are the appropriate pins on the board to connect it to the screen

![10140275291170951805](https://user-images.githubusercontent.com/25624009/75102172-9ee78200-55e7-11ea-8109-d45a4fefe1fc.jpg)
![IMG_20200223_022221](https://user-images.githubusercontent.com/25624009/75102176-a4dd6300-55e7-11ea-9e27-657de99576c2.jpg)

**Comment by ellensp** [comment]
No config files, not text, no versions, practically no information provided.  An image may be worth a 1000 words, but we really need the 1000 words and config files!

**Comment by manarsak** [comment]
I'm sorry, these are the configuration files
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/4241384/Marlin.zip)

**Comment by ellensp** [comment]
Confirmed. This does not compile. Compiles on 2.0.0 and 2.0.1 but anything newer than 2.0.1 that you get the "undefined reference to `ExtUI::FileList::FileList()'"

**Comment by ellensp** [comment]
Seems to have stopped working on commit 0e6ef65aec52980daeda09d7a6e8cd98b97f3806

**Comment by manarsak** [comment]
My friend, I know what the message means, but what is the reason for this problem, knowing that when you comment on the option dgus fystec, things are okay

//#define DGUS_LCD_UI_FYSETC

**Comment by boelle** [comment]
@manarsak 
Please test the [bugfix-2.0.x branch](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands.

**Comment by thinkyhead** [comment]
The latest code builds fine with your configs.
