### PR TITLE
[1.1.x] Fix compilation failure when non DOGM LCD used with SDSUPPORT enabled

### PR DESCRIPTION
**Pull request by Elehiggle**
Bug was introduced here: https://github.com/MarlinFirmware/Marlin/commit/f177da45bb93a6617cb3cf1dbdf50396571ccb82#diff-34f7cdd618621ae7d8c113cf0b86a2f4

This code change causes a compilation failure: 'drawing_screen' was not declared in this scope.

Fix is to check for DOGLCD.

Reproducible with: MKS_13, REPRAP_DISCOUNT_SMART_CONTROLLER, SD_SUPPORT

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
This bug was introduced by PR #9954.

**Comment by Bob-the-Kuhn** [comment]
This change makes all the uses of **drawing_screen** conditional on **DOGLCD** being enabled.  This omission has been in the code a long time.

This ommision became apparent when PR #9954 made the declaration of **drawing_screen** conditional on **DOGLCD**.

**Comment by Bob-the-Kuhn** [comment]
Bugfix-2.0.x does not have this issue.
