### ISSUE TITLE
[BUG] [Bugfix 2.0.x] Compile error when enabling UBL (for SKR V1.3)

### ISSUE THREAD

**Issue by ManIkWeet** [MarlinFirmware/Marlin#15990]
### Description

Enabling UBL for BigTreeTech SKR1.3 appears to give a compile exception since recently.

```
Marlin\src\feature\bedlevel\ubl\ubl_G29.cpp: In static member function 'static void unified_bed_leveling::probe_entire_mesh(const xy_pos_t&, bool, bool, bool)':
Marlin\src\feature\bedlevel\ubl\ubl_G29.cpp:793:10: error: 'class MarlinUI' has no member named 'release'
       ui.release();
          ^~~~~~~
Marlin\src\feature\bedlevel\ubl\ubl_G29.cpp:795:10: error: 'class MarlinUI' has no member named 'capture'
       ui.capture();
          ^~~~~~~
*** [.pio\build\LPC1768\
src\src\feature\bedlevel\ubl\ubl_G29.cpp.o] Error 1
```

### Steps to Reproduce
**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files. 
[compileerror.zip](https://github.com/MarlinFirmware/Marlin/files/3883528/compileerror.zip)

1. set default_envs = LPC1768
2. set #define MOTHERBOARD BOARD_BIGTREE_SKR_V1_3
3. set #define BLTOUCH
4. set #define AUTO_BED_LEVELING_UBL
5. set #define RESTORE_LEVELING_AFTER_G28
6. set #define EEPROM_SETTINGS
7. compile

**Expected behavior:** No compile error

**Actual behavior:** Compile error

#### Additional Information
Broken since 9906e96ffb3d1376ad5981f47dd1c02477502a1e

**Comment by ManIkWeet** [comment]
Apparently already a pull request for it:
https://github.com/MarlinFirmware/Marlin/pull/15981
