### ISSUE TITLE
2.0.6 doesn't compile with Arduino 1.9.0 IDE

### ISSUE THREAD

**Issue by T69** [MarlinFirmware/Marlin#18913]
When compiling 2.0.6 with Arduino 1.9.0 Beta IDE I get the following errors (Compiling 2.0.3 is fine):

<details><summary>Log Output</summary>

```
In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'NUL_STR' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:211:1: note: in expansion of macro 'PGMSTR'

 PGMSTR(NUL_STR, "");

 ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:122:19: error: from previous declaration 'NUL_STR'

 extern const char NUL_STR[], M112_KILL_STR[], G28_STR[], M21_STR[], M23_STR[], M24_STR[],

                   ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'M112_KILL_STR' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:212:1: note: in expansion of macro 'PGMSTR'

 PGMSTR(M112_KILL_STR, "M112 Shutdown");

 ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:122:30: error: from previous declaration 'M112_KILL_STR'

 extern const char NUL_STR[], M112_KILL_STR[], G28_STR[], M21_STR[], M23_STR[], M24_STR[],

                              ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'G28_STR' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:213:1: note: in expansion of macro 'PGMSTR'

 PGMSTR(G28_STR, "G28");

 ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:122:47: error: from previous declaration 'G28_STR'

 extern const char NUL_STR[], M112_KILL_STR[], G28_STR[], M21_STR[], M23_STR[], M24_STR[],

                                               ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'M21_STR' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:214:1: note: in expansion of macro 'PGMSTR'

 PGMSTR(M21_STR, "M21");

 ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:122:58: error: from previous declaration 'M21_STR'

 extern const char NUL_STR[], M112_KILL_STR[], G28_STR[], M21_STR[], M23_STR[], M24_STR[],

                                                          ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'M23_STR' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:215:1: note: in expansion of macro 'PGMSTR'

 PGMSTR(M23_STR, "M23 %s");

 ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:122:69: error: from previous declaration 'M23_STR'

 extern const char NUL_STR[], M112_KILL_STR[], G28_STR[], M21_STR[], M23_STR[], M24_STR[],

                                                                     ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'M24_STR' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:216:1: note: in expansion of macro 'PGMSTR'

 PGMSTR(M24_STR, "M24");

 ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:122:80: error: from previous declaration 'M24_STR'

 extern const char NUL_STR[], M112_KILL_STR[], G28_STR[], M21_STR[], M23_STR[], M24_STR[],

                                                                                ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'SP_P_STR' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:217:1: note: in expansion of macro 'PGMSTR'

 PGMSTR(SP_P_STR, " P");  PGMSTR(SP_T_STR, " T");

 ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:124:19: error: from previous declaration 'SP_P_STR'

                   SP_P_STR[], SP_T_STR[], SP_X_STR[], SP_Y_STR[], SP_Z_STR[], SP_E_STR[],

                   ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'SP_T_STR' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:217:26: note: in expansion of macro 'PGMSTR'

 PGMSTR(SP_P_STR, " P");  PGMSTR(SP_T_STR, " T");

                          ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:124:31: error: from previous declaration 'SP_T_STR'

                   SP_P_STR[], SP_T_STR[], SP_X_STR[], SP_Y_STR[], SP_Z_STR[], SP_E_STR[],

                               ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'X_LBL' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:219:1: note: in expansion of macro 'PGMSTR'

 PGMSTR(X_LBL,     "X:"); PGMSTR(Y_LBL,     "Y:"); PGMSTR(Z_LBL,     "Z:"); PGMSTR(E_LBL,     "E:");

 ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:125:19: error: from previous declaration 'X_LBL'

                   X_LBL[], Y_LBL[], Z_LBL[], E_LBL[], SP_X_LBL[], SP_Y_LBL[], SP_Z_LBL[], SP_E_LBL[];

                   ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'Y_LBL' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:219:26: note: in expansion of macro 'PGMSTR'

 PGMSTR(X_LBL,     "X:"); PGMSTR(Y_LBL,     "Y:"); PGMSTR(Z_LBL,     "Z:"); PGMSTR(E_LBL,     "E:");

                          ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:125:28: error: from previous declaration 'Y_LBL'

                   X_LBL[], Y_LBL[], Z_LBL[], E_LBL[], SP_X_LBL[], SP_Y_LBL[], SP_Z_LBL[], SP_E_LBL[];

                            ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'Z_LBL' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:219:51: note: in expansion of macro 'PGMSTR'

 PGMSTR(X_LBL,     "X:"); PGMSTR(Y_LBL,     "Y:"); PGMSTR(Z_LBL,     "Z:"); PGMSTR(E_LBL,     "E:");

                                                   ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:125:37: error: from previous declaration 'Z_LBL'

                   X_LBL[], Y_LBL[], Z_LBL[], E_LBL[], SP_X_LBL[], SP_Y_LBL[], SP_Z_LBL[], SP_E_LBL[];

                                     ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'E_LBL' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:219:76: note: in expansion of macro 'PGMSTR'

 PGMSTR(X_LBL,     "X:"); PGMSTR(Y_LBL,     "Y:"); PGMSTR(Z_LBL,     "Z:"); PGMSTR(E_LBL,     "E:");

                                                                            ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:125:46: error: from previous declaration 'E_LBL'

                   X_LBL[], Y_LBL[], Z_LBL[], E_LBL[], SP_X_LBL[], SP_Y_LBL[], SP_Z_LBL[], SP_E_LBL[];

                                              ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'SP_A_STR' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:220:1: note: in expansion of macro 'PGMSTR'

 PGMSTR(SP_A_STR, " A");  PGMSTR(SP_B_STR, " B");  PGMSTR(SP_C_STR, " C");

 ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:123:19: error: from previous declaration 'SP_A_STR'

                   SP_A_STR[], SP_B_STR[], SP_C_STR[],

                   ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'SP_B_STR' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:220:26: note: in expansion of macro 'PGMSTR'

 PGMSTR(SP_A_STR, " A");  PGMSTR(SP_B_STR, " B");  PGMSTR(SP_C_STR, " C");

                          ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:123:31: error: from previous declaration 'SP_B_STR'

                   SP_A_STR[], SP_B_STR[], SP_C_STR[],

                               ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'SP_C_STR' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:220:51: note: in expansion of macro 'PGMSTR'

 PGMSTR(SP_A_STR, " A");  PGMSTR(SP_B_STR, " B");  PGMSTR(SP_C_STR, " C");

                                                   ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:123:43: error: from previous declaration 'SP_C_STR'

                   SP_A_STR[], SP_B_STR[], SP_C_STR[],

                                           ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'SP_X_STR' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:221:1: note: in expansion of macro 'PGMSTR'

 PGMSTR(SP_X_STR, " X");  PGMSTR(SP_Y_STR, " Y");  PGMSTR(SP_Z_STR, " Z");  PGMSTR(SP_E_STR, " E");

 ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:124:43: error: from previous declaration 'SP_X_STR'

                   SP_P_STR[], SP_T_STR[], SP_X_STR[], SP_Y_STR[], SP_Z_STR[], SP_E_STR[],

                                           ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'SP_Y_STR' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:221:26: note: in expansion of macro 'PGMSTR'

 PGMSTR(SP_X_STR, " X");  PGMSTR(SP_Y_STR, " Y");  PGMSTR(SP_Z_STR, " Z");  PGMSTR(SP_E_STR, " E");

                          ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:124:55: error: from previous declaration 'SP_Y_STR'

                   SP_P_STR[], SP_T_STR[], SP_X_STR[], SP_Y_STR[], SP_Z_STR[], SP_E_STR[],

                                                       ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'SP_Z_STR' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:221:51: note: in expansion of macro 'PGMSTR'

 PGMSTR(SP_X_STR, " X");  PGMSTR(SP_Y_STR, " Y");  PGMSTR(SP_Z_STR, " Z");  PGMSTR(SP_E_STR, " E");

                                                   ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:124:67: error: from previous declaration 'SP_Z_STR'

                   SP_P_STR[], SP_T_STR[], SP_X_STR[], SP_Y_STR[], SP_Z_STR[], SP_E_STR[],

                                                                   ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'SP_E_STR' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:221:76: note: in expansion of macro 'PGMSTR'

 PGMSTR(SP_X_STR, " X");  PGMSTR(SP_Y_STR, " Y");  PGMSTR(SP_Z_STR, " Z");  PGMSTR(SP_E_STR, " E");

                                                                            ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:124:79: error: from previous declaration 'SP_E_STR'

                   SP_P_STR[], SP_T_STR[], SP_X_STR[], SP_Y_STR[], SP_Z_STR[], SP_E_STR[],

                                                                               ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'SP_X_LBL' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:222:1: note: in expansion of macro 'PGMSTR'

 PGMSTR(SP_X_LBL, " X:"); PGMSTR(SP_Y_LBL, " Y:"); PGMSTR(SP_Z_LBL, " Z:"); PGMSTR(SP_E_LBL, " E:");

 ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:125:55: error: from previous declaration 'SP_X_LBL'

                   X_LBL[], Y_LBL[], Z_LBL[], E_LBL[], SP_X_LBL[], SP_Y_LBL[], SP_Z_LBL[], SP_E_LBL[];

                                                       ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'SP_Y_LBL' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:222:26: note: in expansion of macro 'PGMSTR'

 PGMSTR(SP_X_LBL, " X:"); PGMSTR(SP_Y_LBL, " Y:"); PGMSTR(SP_Z_LBL, " Z:"); PGMSTR(SP_E_LBL, " E:");

                          ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:125:67: error: from previous declaration 'SP_Y_LBL'

                   X_LBL[], Y_LBL[], Z_LBL[], E_LBL[], SP_X_LBL[], SP_Y_LBL[], SP_Z_LBL[], SP_E_LBL[];

                                                                   ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'SP_Z_LBL' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:222:51: note: in expansion of macro 'PGMSTR'

 PGMSTR(SP_X_LBL, " X:"); PGMSTR(SP_Y_LBL, " Y:"); PGMSTR(SP_Z_LBL, " Z:"); PGMSTR(SP_E_LBL, " E:");

                                                   ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:125:79: error: from previous declaration 'SP_Z_LBL'

                   X_LBL[], Y_LBL[], Z_LBL[], E_LBL[], SP_X_LBL[], SP_Y_LBL[], SP_Z_LBL[], SP_E_LBL[];

                                                                               ^

In file included from sketch\src\inc/MarlinConfig.h:30:0,

                 from sketch\src\MarlinCore.h:24,

                 from sketch\src\MarlinCore.cpp:31:

sketch\src\inc/../HAL/HAL.h:41:46: error: redeclaration 'SP_E_LBL' differs in 'constexpr'

   #define PGMSTR(NAM,STR) constexpr char NAM[] = STR

                                              ^

sketch\src\MarlinCore.cpp:222:76: note: in expansion of macro 'PGMSTR'

 PGMSTR(SP_X_LBL, " X:"); PGMSTR(SP_Y_LBL, " Y:"); PGMSTR(SP_Z_LBL, " Z:"); PGMSTR(SP_E_LBL, " E:");

                                                                            ^

In file included from sketch\src\MarlinCore.cpp:31:0:

sketch\src\MarlinCore.h:125:91: error: from previous declaration 'SP_E_LBL'

                   X_LBL[], Y_LBL[], Z_LBL[], E_LBL[], SP_X_LBL[], SP_Y_LBL[], SP_Z_LBL[], SP_E_LBL[];
```
</details>

Is Platformio now the preferred IDE environment or is there any way to fix this?

Thanks & Regards

**Comment by Grogyan** [comment]
Marlin is intended to be compiled with Platformio with VSCode

**Comment by boelle** [comment]
@T69 

> Is Platformio now the preferred IDE environment

Yes

**Comment by ellensp** [comment]
Arduino 1.9.0 beta build (not hourly), marlin 2.0.6. Default RAMPS configs. on Linux...  compiles without issues.

**Comment by ellensp** [comment]
Just tried the same on windows. Also compiled without issues.

Cannot reproduce this issue.

**Comment by T69** [comment]
Thanks ellensp! 
Installed Arduino 1.9.0 beta build (not hourly) & additional libraries ...

Compiling for MOTHERBOARD BOARD_RAMPS_14_EFB works ok ...
Compiling for MOTHERBOARD BOARD_RAMPS4DUE_EFB is apparently the problem and gives me the errors above ...

**Comment by ellensp** [comment]
Please attach your configuration files.

**Comment by boelle** [comment]
@T69 

Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by T69** [comment]
I'm sorry, configuration is now attached ... thanks for looking into this ...

[conf.zip](https://github.com/MarlinFirmware/Marlin/files/5021934/conf.zip)

**Comment by ellensp** [comment]
I can confirm there is an issue. but i'm not sure if its a arduino issue or a marlin issue.  Since it compiles fine on other platforms I a inclined to believe its an arduino ide issue. 
The final nail in the coffin for arduino ide perhaps?

**Comment by T69** [comment]
Just compiled 2.0.5 for BOARD_RAMPS4DUE_EFB without issues ...

**Comment by T69** [comment]
Compiled 2.0.6 with same configuration using PlatformIO was working, but after uploading the REPRAP_DISCOUNT_SMART_CONTROLLER is only showing a blinking cursor, but OctoPrint can connect to 2.0.6 via USB ...

Ok, got the LCD back, solution was to follow the workaround mentioned in this bug report
https://github.com/MarlinFirmware/Marlin/issues/13461 which comments out 
USES_LIQUIDCRYSTAL      = LiquidCrystal@1.5.0
in platformio.ini & installs LiquidCrystal@1.0.7 in Platformio libraries. After rebuilding everything from scratch, LCD is back.

**Comment by AFprinter** [comment]
Is this for an archim board?

**Comment by T69** [comment]
No, it's for an arduino due with a modded RAMPS 1.5 ...

**Comment by futuretech208** [comment]
Hi,
I am still getting an issue in compiling with VScode. I did commenting USES_LIQUIDCRYSTAL. It didn't help. I am compiling for modified ramps with DUE.

**Comment by thinkyhead** [comment]
See if it helps to make this change:
```diff
-  #define PGMSTR(NAM,STR) constexpr char NAM[] = STR
+  #define PGMSTR(NAM,STR) const char NAM[] = STR
```

**Comment by futuretech208** [comment]
Update-- Yes It finally got compiled and uploaded on my board. I used Marlin Auto build in VScode(PlatformIO). This is before I make any changes.
After making changes as suggested, I am getting new error in Arduino/VSCode IDE, ..\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-gcc.exe: The filename or extension is too long.
 But I am able to compile with platformIO.

**Comment by thinkyhead** [comment]
> The filename or extension is too long

This is a Windows+Arduino issue. It may fix the issue to move your "Marlin" folder closer to the root of the C: drive.

> But I am able to compile with platformIO

Great! We do still want to support Arduino for the platforms that it can build, but PlatformIO is the better choice, since we can filter out all extraneous files and do a **_much faster_** build. Plus, on my system Arduino IDE uses only 20% of the available processor power during a build, while PlatformIO uses all available power, spiking all my cores to 100%, and this reduces the build time even more.

**Comment by futuretech208** [comment]
Thanks for the reply. Also is it possible to update the firmware from SD card in case of 32-bit boards? I can see it was possible if the board is with Mega2560. (As written in configuration_adv.h)

**Comment by thinkyhead** [comment]
> is it possible to update the firmware from SD card in case of 32-bit boards

For some 32-bit boards there is no USB update option at all, only SD card updates or direct linking to a pin header with a debugger device.
