### ISSUE TITLE
[BUG] (bug summary) bootstrap_.gcd_imopt: @cli.resultcallback() error

### ISSUE THREAD

**Issue by cmora111** [MarlinFirmware/Marlin#28107]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Using vs code withe the marlin firmware auto build module getting a compilation error:

 platformio run --silent -e mega2560 ; echo "done" >|"/tmp/ipc"
Traceback (most recent call last):
  File "/usr/bin/platformio", line 33, in <module>
    sys.exit(load_entry_point('platformio==4.3.4', 'console_scripts', 'platformio')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/platformio", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/platformio/__main__.py", line 66, in <module>
    @cli.resultcallback()
     ^^^^^^^^^^^^^^^^^^
AttributeError: 'PlatformioCLI' object has no attribute 'resultcallback'. Did you mean: 'result_callback'?

### Version of Marlin Firmware

Marlin2.1

### Printer model

Creality 10S

### Electronics

configuring for bl-touch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

 platformio run --silent -e mega2560 ; echo "done" >|"/tmp/ipc"
Traceback (most recent call last):
  File "/usr/bin/platformio", line 33, in <module>
    sys.exit(load_entry_point('platformio==4.3.4', 'console_scripts', 'platformio')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/platformio", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/platformio/__main__.py", line 66, in <module>
    @cli.resultcallback()
     ^^^^^^^^^^^^^^^^^^
AttributeError: 'PlatformioCLI' object has no attribute 'resultcallback'. Did you mean: 'result_callback'?

[Marlin-config.zip](https://github.com/user-attachments/files/22857059/Marlin-config.zip)

**Comment by ellensp** [comment]
firstly and foremost the provided configs are from the development only branch import. and contain "#error "Don't build with import-2.1.x configurations!"

You should not be trying to build Marlin using these, these are for developers adding new example Configurations. 

For bugfix 2.1.x code you use example for bugfix-2.1.x  ie https://github.com/MarlinFirmware/Configurations/archive/refs/heads/bugfix-2.1.x.zip

Secondly the provided configs are the default config for Marlin with an attempt to enable btouch, but with no Creality 10S settings.

Download the link above, extract the Creality 10S files and replace the default marlin Configuration.h and Configuration_adv.h with the new ones. (also copy over _Bootscreen.h and _Statusscreen.h)

Check the Configuration.h now has the line 24 `#define CONFIG_EXAMPLES_DIR "Creality/CR-10S/CrealityV1"` or something similar if using a different board. 

Check this builds, then modify it for BLTOUCH
