### ISSUE TITLE
Issue compiling bugfix-1.1.x on octoPi since ‘M290' commit.

### ISSUE THREAD

**Issue by autonumous** [MarlinFirmware/Marlin#8445]
Running on an Raspberry Pi, octaprint 0.14.0,  I use an [octoprint](https://github.com/tohara/OctoPrint-BigBoxFirmware) plugin to compile/upload a Marlin firmware (bug fix-1.1.x).  Allows for various profiles and customised settings etc.  Never had any major issues. 

My current firmware was successfully compiled ~Oct 28th.

However, recently been unable to successfully compile current commits.  (Although the same code successful compiles on my desktop running Arduino 1.8.5).  So I don’t necessarily think there is an issue, possibly just the combination of compiler used etc, so looking for any suggestion/advice.  

Compiler errors shown below.

 By way of troubleshooting, I have successfully compiled by:

- disabling baby stepping, or
- reverting [M290](https://github.com/MarlinFirmware/Marlin/commit/fa44130734ed9a0b742fb3522c080d95b2815907#diff-1cb08de130a6ece2d1b5b9c37bcfef48) Commit, or
 - adding `-fpermissive` to the CEXTRA option in the Makefile 

Im sticking with the last option, just wondering why this would be, or if there is other settings required that i’ve missed?  It’s my understanding that that use of "-fpermissive” is frowned upon, as it allows nonconforming code to compile.

Compiler Errors:
```
In file included from MarlinConfig.h:37:0,
                 from Marlin.h:36,
                 from Marlin_main.cpp:245:
Marlin_main.cpp: In function ‘void gcode_M290()’:
Marlin_main.cpp:9323:65: error: invalid conversion from ‘uint8_t {aka unsigned char}’ to ‘AxisEnum’ [-fpermissive]
           const float offs = constrain(parser.value_axis_units(a), -2, 2);
                                                                 ^
/home/pi/oprint/lib/python2.7/site-packages/octoprint_bigboxfirmware/lib/arduino-1.6.8/hardware/arduino/avr/cores/arduino/Arduino.h:87:35: note: in definition of macro ‘constrain’
 #define constrain(amt,low,high) ((amt)<(low)?(low):((amt)>(high)?(high):(amt)))
                                   ^
In file included from Marlin_main.cpp:260:0:
gcode.h:245:31: error:   initializing argument 1 of ‘static float GCodeParser::value_axis_units(AxisEnum)’ [-fpermissive]
     FORCE_INLINE static float value_axis_units(const AxisEnum a)    { UNUSED(a); return value_float(); }
                               ^
In file included from MarlinConfig.h:37:0,
                 from Marlin.h:36,
                 from Marlin_main.cpp:245:
Marlin_main.cpp:9323:65: error: invalid conversion from ‘uint8_t {aka unsigned char}’ to ‘AxisEnum’ [-fpermissive]
           const float offs = constrain(parser.value_axis_units(a), -2, 2);
                                                                 ^
/home/pi/oprint/lib/python2.7/site-packages/octoprint_bigboxfirmware/lib/arduino-1.6.8/hardware/arduino/avr/cores/arduino/Arduino.h:87:54: note: in definition of macro ‘constrain’
 #define constrain(amt,low,high) ((amt)<(low)?(low):((amt)>(high)?(high):(amt)))
                                                      ^
In file included from Marlin_main.cpp:260:0:
gcode.h:245:31: error:   initializing argument 1 of ‘static float GCodeParser::value_axis_units(AxisEnum)’ [-fpermissive]
     FORCE_INLINE static float value_axis_units(const AxisEnum a)    { UNUSED(a); return value_float(); }
                               ^
In file included from MarlinConfig.h:37:0,
                 from Marlin.h:36,
                 from Marlin_main.cpp:245:
Marlin_main.cpp:9323:65: error: invalid conversion from ‘uint8_t {aka unsigned char}’ to ‘AxisEnum’ [-fpermissive]
           const float offs = constrain(parser.value_axis_units(a), -2, 2);
                                                                 ^
/home/pi/oprint/lib/python2.7/site-packages/octoprint_bigboxfirmware/lib/arduino-1.6.8/hardware/arduino/avr/cores/arduino/Arduino.h:87:74: note: in definition of macro ‘constrain’
 #define constrain(amt,low,high) ((amt)<(low)?(low):((amt)>(high)?(high):(amt)))
                                                                          ^
In file included from Marlin_main.cpp:260:0:
gcode.h:245:31: error:   initializing argument 1 of ‘static float GCodeParser::value_axis_units(AxisEnum)’ [-fpermissive]
     FORCE_INLINE static float value_axis_units(const AxisEnum a)    { UNUSED(a); return value_float(); }
                               ^
Marlin_main.cpp:9330:78: error: invalid conversion from ‘uint8_t {aka unsigned char}’ to ‘AxisEnum’ [-fpermissive]
           thermalManager.babystep_axis(a, offs * planner.axis_steps_per_mm[a]);
                                                                              ^
In file included from Marlin_main.cpp:251:0:
temperature.h:457:19: error:   initializing argument 1 of ‘static void Temperature::babystep_axis(AxisEnum, int)’ [-fpermissive]
       static void babystep_axis(const AxisEnum axis, const int distance) {
                   ^
  CXX   vector_3.cpp
make: *** [/home/pi/.octoprint/data/bigboxfirmware/tmp/Marlin_main.o] Error 1
make: *** Waiting for unfinished jobs....
/home/pi/oprint/lib/python2.7/site-packages/octoprint_bigboxfirmware/lib/Makefile:319: recipe for target '/home/pi/.octoprint/data/bigboxfirmware/tmp/Marlin_main.o' failed
Something went wrong. Hex file does not exist!
Cleaning up build files....
  RM    /home/pi/.octoprint/data/bigboxfirmware/tmp/*
  RMDIR /home/pi/.octoprint/data/bigboxfirmware/tmp/
Done!
```

**Comment by thinkyhead** [comment]
This should now be fixed with the most recent patch.
