### PR TITLE
Enabled 2 mesh viewers

### PR DESCRIPTION
**Pull request by classicrocker883**
### Description
for *ProUI*:
---

This adds the option to enable two types of mesh viewers.  
Toggle between the older "Red ..0.. Green" square block style and the newer rainbow color round style.

- add menu option to view 2 ways to view mesh.
- renamed to `MSG_CHANGE_MESH` from `MSG_CHANGE_MESH_VIEWER`

changed in **Conditionals_post.h** so `USE_GRID_MESHVIEWER` is defined when ProUI is used, because `bedlevelTools` is.
in **settings.cpp**, also added a couple relevant comments to other things in **settings.cpp**.

### Requirements
`DWIN_LCD_PROUI`
`HAS_MESH`

### Benefits
gives the user the option to toggle between the two ways to view the mesh.  

### Configurations

in **meshviewer.cpp** I wrote a `TODO:` comment because  `set_status_and_level` was changed in **marlinui.h** (which is now in the other **PR**).
>
>I'm not sure which is right... either leaving how this function is defined, and just changing how it is used in **meshviewer.cpp** (by adding `, 0)` to the end of it *OR* `level=0` as its defined).

```diff
-   ui.set_status_and_level(MString<30>(F("Mesh Z min: "), p_float_t(min, 2), F(", max: "), p_float_t(max, 2)));
// with change in marlin.h -- level=0
+   ui.set_status_and_level(MString<30>(F("Mesh Z min: "), p_float_t(min, 2), F(", max: "), p_float_t(max, 2)), 0);
// without changes 
```
as example
```diff
-  static void set_status_and_level(const char * const cstr, const int8_t level) { _set_status_and_level(cstr, level, false); }
+  static void set_status_and_level(const char * const cstr, const int8_t level=0) { _set_status_and_level(cstr, level, false); }
```

### CODE REVIEW

**Comment by classicrocker883** [comment]
@thisiskeithb @thinkyhead [Prusa/MK3S-BigTreeTech-BTT002](https://github.com/MarlinFirmware/Configurations/blob/import-2.1.x/config/examples/Prusa/MK3S-BigTreeTech-BTT002) has caused an issue with pull requests

`(BIGTREE_BTT002) (pull_request)` fails and with the given error:  
>Marlin\src\sd\cardreader.cpp:996:28: error: 'IS_DIR' was not declared in this scope; did you mean 'EISDIR'?
>Marlin\src\sd\cardreader.cpp:1014:30: error: 'IS_DIR' was not declared in this scope; did you mean 'EISDIR'?
>Marlin\src\sd\cardreader.cpp:1365:11: error: 'isDir' was not declared in this scope; did you mean 'isDigit'?

`HAS_FOLDER_SORTING` should be enabled, because `FOLDER_SORTING` became undefined in the recent push to example configs.

**Comment by thisiskeithb** [comment]
Thinkyhead will need to push a follow-up commit after checking existing configs that were broken after https://github.com/MarlinFirmware/Configurations/commit/65c51209d4cccdd4f4709d2af71bea675d4d9d1f.

**Comment by thinkyhead** [comment]
The `viewer_asymmetric_range` flag is still referenced, so that cannot be removed just yet. If it is no longer relevant then the code that refers to it must be updated. Check with @mriscoc for advice on whether it should be retained.

File: Marlin/src/lcd/e3v2/proui/dwin.cpp [hunk 1]
```diff
@@ -3478,12 +3483,15 @@ void drawMotionMenu() {
...
     checkkey = ID_Menu;
-    if (SET_MENU(manualMesh, MSG_UBL_MANUAL_MESH, 6)) {
+    if (SET_MENU(manualMesh, MSG_UBL_MANUAL_MESH, 7)) {
       BACK_ITEM(drawPrepareMenu);
       MENU_ITEM(ICON_ManualMesh, MSG_LEVEL_BED, onDrawMenuItem, manualMeshStart);
       mMeshMoveZItem = EDIT_ITEM(ICON_Zoffset, MSG_MOVE_Z, onDrawMMeshMoveZ, setMMeshMoveZ, &current_position.z);
       MENU_ITEM(ICON_Axis, MSG_UBL_CONTINUE_MESH, onDrawMenuItem, manualMeshContinue);
       MENU_ITEM(ICON_MeshViewer, MSG_MESH_VIEW, onDrawSubMenu, dwinMeshViewer);
+      #if USE_GRID_MESHVIEWER
+        EDIT_ITEM(ICON_PrintSize, MSG_CHANGE_MESH_VIEWER, onDrawChkbMenu, setViewMesh, &bedLevelTools.view_mesh);
```
Comment (thinkyhead) [inline Marlin/src/lcd/e3v2/proui/dwin.cpp]: In what way does this "change" the mesh viewer?

**Comment by mriscoc** [comment]
> The `viewer_asymmetric_range` flag is still referenced, so that cannot be removed just yet. If it is no longer relevant then the code that refers to it must be updated. Check with @mriscoc for advice on whether it should be retained.

I didn't see what was wrong with the thumbnail preview. Proper definitions should be ensured to allow people to choose between having a normal mesh viewer, a grid mesh viewer, or a selectable one; otherwise, we're increasing the program memory usage for no real benefit.

File: Marlin/src/lcd/e3v2/proui/dwin.cpp (hunk 1 above)
Comment (classicrocker883) [reply Marlin/src/lcd/e3v2/proui/dwin.cpp]: there are two types of ways to view the mesh

<p><a target="_blank" rel="noopener noreferrer nofollow"></a></p>
<p><a target="_blank" rel="noopener noreferrer nofollow"></a></p>
This shows the two types of meshviewer as an example<br>


you can toggle between with the checkbox

**Comment by classicrocker883** [comment]
> I didn't see what was wrong with the thumbnail preview.


it wasnt working when I tried before I made the changes. unless I imagined it. but it was working fine after.

update: not sure what happened. thumbnail previews are working without changes made. so disregard.

File: Marlin/src/lcd/e3v2/proui/dwin.cpp (hunk 1 above)
Comment (thinkyhead) [reply Marlin/src/lcd/e3v2/proui/dwin.cpp]: The display with solid colors is much nicer. The display with circles seems noisy and inferior, but is it useful for people with color blindness?

Comment (thinkyhead) [reply Marlin/src/lcd/e3v2/proui/dwin.cpp]: Anyway, you get my point. The label "Change Mesh Viewer" with a checkbox next to it is unclear and therefore bad UI design. The label should indicate what type of mesh viewer will be seen when the checkbox is checked. For example, the label "Ugly Mesh View" would make it clear that when the checkbox is checked the mesh viewer will be the "ugly" version, as opposed to the "normal" version.

**Comment by thinkyhead** [comment]
> I didn't see what was wrong with the thumbnail preview.

@mriscoc — If you look at the current `bugfix-2.1.x` code you will see that `viewer_asymmetric_range` exists as part of ProUI but it never changes; it is always `false`. It seems to be a remnant of JyersUI that should have been removed. Or maybe `viewer_asymmetric_range` was meant to be used but no interface has been created yet to toggle it.

**Comment by mriscoc** [comment]
> you will see that `viewer_asymmetric_range` exists as part of ProUI but it never changes

viewer_asymmetric_range was kept to allow to JYERSUI to use the bed_level_tools in the future but it is currently not used in ProUI.

File: Marlin/src/lcd/e3v2/proui/dwin.cpp (hunk 1 above)
Comment (classicrocker883) [reply Marlin/src/lcd/e3v2/proui/dwin.cpp]: > The display with solid colors is much nicer. The display with circles seems noisy and inferior, but is it useful for people with color blindness?

That's a valid point. I'm not partial to either, just offering making the options more available. I just wanted to say the picture examples posted aren't reminiscent of a true bed level, merely did a quick manual edit of the values to give a quick example of how it can be displayed.

<p><a target="_blank" rel="noopener noreferrer nofollow"></a></p>

this above image is more a true representation of a typical mesh.

anyway it is what it is. and as for calling it "Normal Mesh View" or something like that is a good idea. Having the checkbox enabled means to have the Square block style. default would be the box unchecked and Circle colorful style.

File: Marlin/src/lcd/e3v2/proui/meshviewer.cpp [hunk 2]
```diff
@@ -127,12 +133,11 @@ void MeshViewer::draw(const bool withsave/*=false*/, const bool redraw/*=true*/)
...
-    bedLevelTools.setMeshViewerStatus();
-  #else
-    char str_1[6], str_2[6] = "";
-    ui.status_printf(0, F("Mesh minZ: %s, maxZ: %s"), dtostrf(min, 1, 2, str_1), dtostrf(max, 1, 2, str_2));
-  #endif
+  if (see_mesh) {
+    TERN_(USE_GRID_MESHVIEWER, bedLevelTools.setMeshViewerStatus());
+  }
+  else
+    ui.set_status_and_level(MString<30>(F("Mesh Z min: "), p_float_t(min, 2), F(", max: "), p_float_t(max, 2)));
```
Comment (classicrocker883) [inline Marlin/src/lcd/e3v2/proui/meshviewer.cpp]: I propose we change this to 
```suggestion
    ui.set_status_and_level(MString<32>(
      F("Zmin: "), p_float_t(min, 3), F(" | "), p_float_t(max, 3), F("+"), F(" :Zmax"))
    );
```
it will look like
```r
Zmin: -0.000 | 0.000+ :Zmax
```

of course we can always change it around
```r
-0.000 :Zmin | Zmax: 0.000+
```

**Comment by classicrocker883** [comment]
I made some changes to this PR which should be easier to merge now.
take a look at the *Note* in description for a small concern/issue

**Comment by classicrocker883** [comment]
@thinkyhead I believe we can merge this now if you dont mind taking a quick review

**Comment by thinkyhead** [comment]
Please test to make sure nothing has been broken. I can also test this on my E3V2. I think most would prefer the square grid mesh viewer instead of the one with circles as the default because the white text is hard to read on the bright circles. Neither mesh viewer stands out as more "normal" so we can consider different labels. Maybe one is "View Mesh (grid)" and the other is "View Mesh (blobs)".

I have not used ProUI from the community fork in a couple of years, so I don't know what else may be implemented there which has not been migrated here, but we can continue to bring over missing pieces as time allows.

e.g., I grabbed code from other sources to decompress and display images embedded in G-code, experimented with that a little. So we could potentially display print previews (large and icon) once we have that code in there. It would be good to display it on the print confirmation screen.

**Comment by classicrocker883** [comment]
> I grabbed code from other sources to decompress and display images embedded in G-code,

are you talking about `HAS_GCODE_PREVIEW`?
"Preview G-code model thumbnail"

isnt that already a feature? except I dont believe the slicer scripts/plugin have been added
you can find in [How-to-generate-a-gcode-preview](https://github.com/mriscoc/Ender3V2S1/wiki/How-to-generate-a-gcode-preview) wiki.

I know cura has a plugin to "Create Thumbnail", im not sure if current bugfix-2.1.x ProUI is compatible with *that* or not. it does produce a similar code in the .gcode, it may just work over on my fork of MRicoC's ProUI

edit:
also, mriscoc's firmware has a different style Mesh Viewer. its similar to the old block one.
and the code for it is not available - locked in the library
