### ISSUE TITLE
[BUG] Marlin Failed do compile on VSCODE SKR 1.4 BLTOUCH

### ISSUE THREAD

**Issue by rodnvs** [MarlinFirmware/Marlin#19791]
### Bug Description

Marlin failed to compile showing an error:

```
Compiling .pio\build\LPC1769\src\src\feature\babystep.cpp.o
In file included from Marlin\src\module/../HAL/shared/servo.h:76,
                 from Marlin\src\module/servo.h:29,
                 from Marlin\src\MarlinCore.cpp:125:
c:\marlin\marlin\src\hal\lpc1768\servo.h:51:10: fatal error: Servo.h: No such file or directory
```

### My Configurations

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5396978/Configuration.zip)

### Steps to Reproduce

1. Edit Configuration files for a SKR 1.4 board with bltouch
2. Install servo.h dependency
3. Try to compile

**Expected behavior:** Compile generating a .bin file

**Actual behavior:** an error stops the compiling

**Comment by thisiskeithb** [comment]
This is not a Marlin bug. Your configs build fine against the latest `bugfix-2.0.x`.

```prolog
Indexing .pio/build/LPC1769/libFrameworkArduino.a
Linking .pio/build/LPC1769/firmware.elf
Building .pio/build/LPC1769/firmware.bin
Checking size .pio/build/LPC1769/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=====     ]  48.4% (used 15828 bytes from 32736 bytes)
Flash: [=====     ]  46.9% (used 223000 bytes from 475136 bytes)
======================================== [SUCCESS] Took 33.15 seconds ========================================

Environment    Status    Duration
-------------  --------  ------------
LPC1769        SUCCESS   00:00:33.154
======================================== 1 succeeded in 00:00:33.154 ========================================
```

---
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
