### ISSUE TITLE
52158dffccfa6b73ba42d6e01867e295e14d818c (Big temperature update) breaks compilation when EXTRUDERS > 1 - unable to find a register to spill in class 'POINTER_REGS' temperature.cpp:318

### ISSUE THREAD

**Issue by triffid** [MarlinFirmware/Marlin#347]
I have no idea what's going on here, https://github.com/ErikZalm/Marlin/commit/52158dffccfa6b73ba42d6e01867e295e14d818c#L0R318 seems fairly innocuous to my eye, and L462 is the closing brace of manage_heater();

$ git bisect start origin/Marlin_v1 587154c01
$ git bisect run sh -c "( cd Marlin; rm -r applet; perl -pi~ -e 's/define EXTRUDERS 1/define EXTRUDERS 2/;' Configuration_adv.h; make HARDWARE_MOTHERBOARD=34 all applet/temperature.o; git checkout -- Configuration_adv.h; )  ; [ -e Marlin/applet/temperature.o ]"
...
  CXX   temperature.cpp
temperature.cpp: In function 'void manage_heater()':
**temperature.cpp:462:1: error: unable to find a register to spill in class 'POINTER_REGS'**
temperature.cpp:462:1: error: this is the insn:
(insn 100 99 102 4 temperature.cpp:318 (set (reg/v:SF 113 [ pid_input ])
        (mem/s:SF (post_inc:HI (reg:HI 133 [ ivtmp.135 ])) [3 current_temperature S4 A8])) 13 {_movsf} (expr_list:REG_INC (reg:HI 133 [ ivtmp.135 ])
        (nil)))
temperature.cpp:462: confused by earlier errors, bailing out
make: *_\* [applet/temperature.o] Error 1
52158dffccfa6b73ba42d6e01867e295e14d818c is the first bad commit
commit 52158dffccfa6b73ba42d6e01867e295e14d818c
Author: daid303 daid303@gmail.com
Date:   Sun Dec 9 23:00:06 2012 +0100

```
Big temperature code update. No longer converts back and forwards between temperature and raw sample value. Reducing complexity, removing code. Also named some variables better. While keeping the safety intact and functionality the same.
```

:040000 040000 56bde532429e7f5e53225b988d2069c715daa34b 873e71c450dbce95dee2f88ee2d6575665e8455b M Marlin
