### PR TITLE
MAX31865 enhancements

### LINKED ISSUE #22526: [BUG] MINTEMP on SKR 1.3 with MAX31865
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

MAX31865 is not working   Marlin-bugfix-2.0.x 2021-08-05 
SKR1.3 +TFT35 
Case 1 
conf.h :
```cpp
#define SERIAL_PORT -1
#define SERIAL_PORT_2 0 
#define MOTHERBOARD BOARD_BTT_SKR_V1_3 
#define TEMP_SENSOR_0 -5
#define MAX31865_SENSOR_OHMS_0      100   // (Ω) Typically 100 or 1000 (PT100 or PT1000)
#define MAX31865_CALIBRATION_OHMS_0 430   // (Ω) Typically 430 for Adafruit PT100; 4300 for Adafruit PT1000

#define SDSUPPORT
//#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
```
conf_adv.h
```cpp
  //#define SDCARD_CONNECTION LCD
```
MAX31865.h:
`SPI_MODE1 `

pins_BTT_SKR_common:
```cpp
#define TEMP_0_CS_PIN   P0_16
// #ifndef TEMP_0_PIN
//   #define TEMP_0_PIN                    P0_24_A1  // A1 (T1) - (68) - TEMP_0_PIN
// #endif

   #define SDCARD_CONNECTION            ONBOARD
```
MAX31865 connected to:
```
SDI  P0.18
CS    P0.16
CLK  P0.15
SDO P0.17 
VCC and GND 
```
Compilation - no errors  
file .bin >> sd card>> SKR>> restart >> no printer attached  on TFT35 

Case 2 >>
```cpp
#define TEMP_SENSOR_0  1 
//#define TEMP_0_CS_PIN   P0_16
 #ifndef TEMP_0_PIN
   #define TEMP_0_PIN                    P0_24_A1  // A1 (T1) - (68) - TEMP_0_PIN
 #endif
```
Compilation - no errors  
file .bin >> sd card>> SKR>> restart >> READY 
 
case 3 :
after some changes .... MINTEMP triggered HEATER_ID: E0

Some suggestions? 

### Expected behavior

MAX 31865 work  with SKR 1.3

### Actual behavior

no communication / freeze of mainboard

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

SKR 1.3 

### Electronics

SKR 1.3

### PR DESCRIPTION
**Pull request by jinhong-**
### Description

- Fix SPI mode typo
- Use software SPI library for software SPI mode
- Added timings/delays for sck and cs signals to match SPI speed

### Requirements

Software SPI now uses the `<SoftwareSPI.h>` dependency. Not quite sure which board is or is not compatible, but i assume it should be compatible with all

### Benefits

Using the software SPI library, SPI clock speed can now be regulated, hopefully this means more compatibility with boards of different speeds. So far this PR will work with SKR E3 Turbo

### Configurations

No additional configurations apart from the original settings to enable MAX31865

### Related Issues

Might Fix #22526

### CODE REVIEW

**Comment by jinhong-** [comment]
@thinkyhead I tweaked this so that it has compatibility with non `lpc176x` platforms by using @slowbro's original implementation

**Comment by thinkyhead** [comment]
Thanks for the followup! I will review this later today, along with others who had comments for the previous PR.

**Comment by Gotos** [comment]
For completions sake (and because I think putting it here is the more reasonable place than just putting it in the old PR):
I just successfully compiled this with the Arduino IDE when I couldn't before, so this seems to have solved my problem. Thanks!

**Comment by jinhong-** [comment]
@thinkyhead just to continue the conversation of the bit bang implementation of the soft spi library, it seems to make certain assumptions in terms of clock speeds and adding "delays"(It doesn't really add delays, rather it creates loops that acts as delays). We could port the codes over if we understood the different clock speeds of each platform. Is there a "universal" way to retrieve clock speeds for different processors?

**Comment by thinkyhead** [comment]
The Marlin HAL provides the macros `DELAY_NS` and `DELAY_US` which should be reasonably accurate on all platforms, as they use the known speed of the MCU and NOPs where necessary.

**Comment by jinhong-** [comment]
@thinkyhead I updated the codes to use DELAY_NS. Tested it working on my SKR E3 Turbo. Might be worth verifying the delay calculation and testing this on other platforms to see if it works well

File: Marlin/src/libs/MAX31865.cpp [hunk 1]
```diff
@@ -485,16 +454,33 @@ uint8_t MAX31865::spixfer(uint8_t x) {
...
+  return reply;  
+}
+
+void MAX31865::softSpiBegin(uint8_t spi_speed) {
+  #ifdef MAX31865_DEBUG
+    SERIAL_ECHOLNPGM("Initializing MAX31865 Software SPI");
+  #endif
+
+  // Calculate the actual clock speed
+  uint8_t target_clock_speed = 10000000/(2^spi_speed);
```
Comment (thinkyhead) [inline Marlin/src/libs/MAX31865.cpp]: In C++ the `^` operator is XOR, not exponent! This should be `_BV32(spi_speed)` or `pow(2, spi_speed)`.

**Comment by thinkyhead** [comment]
> jinhong- force-pushed the jinhong-:max31865-enhancements  branch from 9854cf4 to 18d82c1 2 hours ago

This force-push sacrificed a number of improvements. I'll push one more commit restoring to the last known-good state, and then you can apply your additional updates or undo elements of that commit after you've pulled it down with GitHub Desktop.

**Comment by thinkyhead** [comment]
> verifying the delay calculation

The number of milliseconds or nanoseconds should be based on the speed where SPI can function reliably. So, as we go from full speed to half to quarter to eighth, the base delay should simply double. So the first question is, what is the bit-rate for "full speed" ? And, where are the delays meant to be inserted? Do they have to go after _every_ `WRITE` or just some of them? And, if there are three delays, do they all need to be the same size? When we add all three of them together, is the total time for a single bit to be clocked in / out correctly matching the expected SPI rate?

**Comment by thinkyhead** [comment]
I'll need to throw together a version of `DELAY_NS` for Teensy that can work with the older GCC 5.4.1 compiler (compared to 9.3.1 for LPC1768), since with my current calculations the µs delays will tend to always end up as 0. Hopefully this won't take too long to sort out.

**Comment by thinkyhead** [comment]
There is a [helpful post for nanosecond delays on Teensy](https://forum.pjrc.com/threads/29105-Sub-Micro-Second-Pulses), but it would require some extra work to incorporate. I think our current delay functions are probably fine. So for now I simply added code to check the compiler version and skip any attempt to evaluate `IS_CONSTEXPR` if it's too old. I'm not sure of the exact GCC version that adds the capability, but there might be a capability flag that can replace the version check.

**Comment by jinhong-** [comment]
> > verifying the delay calculation
> 
> The number of milliseconds or nanoseconds should be based on the speed where SPI can function reliably. So, as we go from full speed to half to quarter to eighth, the base delay should simply double. So the first question is, what is the bit-rate for "full speed" ? And, where are the delays meant to be inserted? Do they have to go after _every_ `WRITE` or just some of them? And, if there are three delays, do they all need to be the same size? When we add all three of them together, is the total time for a single bit to be clocked in / out correctly matching the expected SPI rate?

I lifted the codes from the software SPI of the libraries i found. Both implementations are doing it exactly this way

Implementations can be found here. Having said that this looks, like mode0 implementation. I think i'd have to change it to mode1 implementation

https://github.com/MarlinFirmware/Marlin/blob/718227a94c0cb163a73f0f288be6f7b864b7127a/Marlin/src/HAL/NATIVE_SIM/u8g/u8g_com_sw_spi.cpp#L72-L98
https://github.com/MarlinFirmware/Marlin/blob/718227a94c0cb163a73f0f288be6f7b864b7127a/Marlin/src/HAL/NATIVE_SIM/u8g/u8g_com_st7920_sw_spi.cpp#L72-L90

**Comment by jinhong-** [comment]
@thinkyhead i think you are right. Looking at the delay cycles, they seem to be delaying for roughly half the actual SPI speed that was selected

**Comment by trengtor** [comment]
Nice! I hope that will extend possibilities E3 RRF too (via extension bus using).

**Comment by thinkyhead** [comment]
When it comes down to it, there should be a simplified capability to use a shared SPI bus with different speeds for different peripherals attached to the bus. But this means adding yet another layer of indirection by wrapping the general SPI bus class(es) in another class, perhaps called "`SPIDevice`" that handles the Begin, Transfer, and End, deals with different SPI transfer modes, and so on. At the present time it seems like we are defining too many _ad hoc_ classes that each have their own ideas about how to relate to the SPI buses.

For the present case, although it is not likely that the MAX31865 SPI speed will ever need to be modified after initialization, the SPI speed is not being specified as a template parameter or as a constant within the class. Doing so would allow for the highest level of optimization, both in size and performance, and would obviate the need to add the `DELAY_CYCLES_VAR` as I have done here.

File: Marlin/src/libs/MAX31865.cpp [hunk 2]
```diff
@@ -152,22 +145,13 @@ void MAX31865::begin(max31865_numwires_t wires, float zero, float ref) {
...
   if (_sclk != TERN(LARGE_PINMAP, -1UL, -1)) {
-    // Define pin modes for Software SPI
-    #ifdef MAX31865_DEBUG
-      SERIAL_ECHOLN("Initializing MAX31865 Software SPI");
-    #endif
-
-    OUT_WRITE(_sclk, LOW);
-    SET_OUTPUT(_mosi);
-    SET_INPUT(_miso);
+    softSpiBegin(SPI_QUARTER_SPEED); // Define pin modes for Software SPI
```
Comment (slowbro) [inline Marlin/src/libs/MAX31865.cpp:148]: Should this be `softSpiBegin(TERN(TARGET_LPC1768, SPI_QUARTER_SPEED, TERN(ARDUINO_ARCH_STM32, SPI_CLOCK_DIV4, 500000));` ?

Comment (thinkyhead) [reply Marlin/src/libs/MAX31865.cpp:148]: `softSpiBegin` currently takes a shift value and uses it in an equation that gives a nanoseconds result. 
```cpp
_spi_delay = (100UL << spi_speed) / 3;
```
Those other values `SPI_CLOCK_DIV4` and `500000` are quite large numbers and seem to relate to the clock cycles speed, which would need to be translated back to nanoseconds in such usage. I have no idea how those values are otherwise used by `SPI.beginTransaction` when passed, whether they are architecture-specific, and so on…
```cpp
SPI.beginTransaction(spiConfig);
```
If you're very interested in the topic and want to be more involved in this PR, then please make a study of those SPI implementations and let us know what's going on under the hood and whether our nanoseconds delays are a good idea.

**Comment by FinziNeto** [comment]
I have tried the last Bug Fix and it is still not working. I have a SKR v1.4 Turbo + BTT TFT35 + BTT MAX31865 v2.0 + PT1000 (two wires) installed on E1 driver plug. Still, no temperature information can be seen on TFT35 (always displays zero). I would appreciate any help provided and I am available to perform tests as needed.

**Comment by thinkyhead** [comment]
@FinziNeto — You should only be commenting on your testing of this specific Pull Request.

**Comment by jinhong-** [comment]
Hey just wanted to check in on this PR. Things picked up quite a little bit elsewhere. I'll try to find some time this weekend to fix up the PR 😄

**Comment by thinkyhead** [comment]
Thanks for checking in! I am also anxious to know whether this is complete or needs refinements.

File: Marlin/src/libs/MAX31865.cpp [hunk 3]
```diff
@@ -484,17 +457,34 @@ uint8_t MAX31865::spixfer(uint8_t x) {
...
-  return reply;
+void MAX31865::softSpiBegin(const uint8_t spi_speed) {
+  #ifdef MAX31865_DEBUG
+    SERIAL_ECHOLNPGM("Initializing MAX31865 Software SPI");
+  #endif
+  #ifdef TARGET_LPC1768
+    swSpiBegin(_sclk, _miso, _mosi);
+    _spi_speed = swSpiInit(spi_speed, _sclk, _mosi);
+  #else
+    _spi_delay = (100UL << spi_speed) / 3; // Calculate delay in ns. Top speed is ~10MHz, or 100ns delay between bits.
```
Comment (jinhong-) [inline Marlin/src/libs/MAX31865.cpp:492]: Not sure if 10MHz is okay for MAX31865. [Datasheet](https://datasheets.maximintegrated.com/en/ds/MAX31865.pdf) mentions a max clock frequency of 5MHz

**Comment by jinhong-** [comment]
I noticed the changes went back to the version that uses the built in SPI library for LPC176X chips. I just tested these codes for my ender 3 running on a SKR e3 turbo and it works great. I think I also ironed out some previously erratic behavior - it was a likely grounding problem of my raspberry pi and skr board

Did anyone get a chance to test it on existing platforms that the previous PR broke? I think my concern might be the `_spi_delay` we're adding. We may want to limit it to 5MHz instead of 10MHz, looking at max31865's datasheet

Also, i found this [softspi codes](https://github.com/MajenkoLibraries/SoftSPI/tree/master/src) that seems to have the full implementations of the different modes. Not sure if it's worth importing and converging all the implementation to this

File: Marlin/src/libs/MAX31865.cpp (hunk 3 above)
Comment (thinkyhead) [reply Marlin/src/libs/MAX31865.cpp:492]: Accordingly, the `SPI_QUARTER_SPEED` used here should be limiting the speed to 2.5MHz.

**Comment by thinkyhead** [comment]
> Not sure if it's worth importing and converging all the implementation to this

This PR only needs the mode(s) required for MAX31865 and not necessarily the full generalization of the MajenkoLibraries SoftSPI library. That said, Marlin already has its own `SoftSPI` class, located at `src/libs/softspi.h` / `src/libs/softspi.cpp` which supports different modes. That could also be used here instead of the _ad hoc_ implementation.

**Comment by jinhong-** [comment]
ah i did not realize that. I briefly looked at the code and it seems like it relies on knowing the pins during compile time using `template<>`. Might be doable by generating multiple derived SoftSPI classes from this
The current codes works pretty okay for my SKR E3 Turbo. Anything else we need to do to get this merged and closed?

**Comment by thinkyhead** [comment]
> it relies on knowing the pins during compile time … Might doable by generating multiple derived SoftSPI classes from this

Pins are never changed after compile time so that is fine. And one derived class is already used for a TFT peripheral. It is specifically intended to be used in just this way because the class is very small and runs much faster with the pin numbers known at compile-time.

**Comment by thinkyhead** [comment]
Incidentally, how well does it work if `-DLIB_MAX31865` is added to the build flags? This causes Marlin to set the `USE_ADAFRUIT_MAX31865` flag and to use the Adafruit MAX31865 library. I'd have to review the commit history to see why we aren't using it currently.

That was introduced in #20447 by @GadgetAngel.

**Comment by jinhong-** [comment]
> Incidentally, how well does it work if `-DLIB_MAX31865` is added to the build flags? This causes Marlin to set the `USE_ADAFRUIT_MAX31865` flag and to use the Adafruit MAX31865 library. I'd have to review the commit history to see why we aren't using it currently.
> 
> That was introduced in #20447 by @GadgetAngel.

Interesting. Let me give that a shot this weekend and report back

**Comment by jinhong-** [comment]
@thinkyhead I tried using the flag to enable the dependency and.. it does not compile. Using v1.3 of the [library](https://platformio.org/lib/show/1253/Adafruit%20MAX31865%20library/examples) resulted in a string of dependency errors. It was reporting the following error `.pio\libdeps\LPC1769\Adafruit MAX31865 library/Adafruit_MAX31865.h:52:10: fatal error: WProgram.h: No such file or directory` which i do not quite understand. Is it because the program was designed for the arduino platform?
