### ISSUE TITLE
[BUG] non-constant condition for static assertion marlin

### ISSUE THREAD

**Issue by disappear123df** [MarlinFirmware/Marlin#15540]
Arduino: 1.8.8 (Linux), Board: "Anet V1.0"

error: https://pastebin.com/uWq4skCb

(edited so that error is in a pastebin link, keep this post sort - but nothing has been removed)

**Comment by boelle** [comment]
tried 1.9.0 beta of ide?
where is the config files ? issue template says to attach them as zip
what version of marlin?

**Comment by GMagician** [comment]
> "X_MIN_PIN is not interrupt-capable

This is the error...maybe wrong pins used (or enabled endstop interrupts on a board that doesn't support it?)

**Comment by ghost** [comment]
Was my case, now compiling fine. 
Same error but on Y_MAX_PIN.
Disabled ENDSTOP_INTERRUPTS_FEATURE.
Arduino+RAMPS 1.4

**Comment by boelle** [comment]
will close as its mostly a user error, ie wrong use pins used

we can always reopen

**Comment by Gabrielerusso** [comment]
I've got the same issue with a configuration i've used for years and pin14 is interrupt capable (PCINT10 of atmega 2560), with ide 1.8.10 and 1.8.11.

> will close as its mostly a user error, ie wrong use pins used
> 
> we can always reopen

got the same error, it's an IDE problem not recognizing the pointer of the following macro:
```
  #define digitalPinToPCICR(p)    ( WITHIN(p, 10, 15) || \
                                    WITHIN(p, 50, 53) || \
                                    WITHIN(p, 62, 69) ? &PCICR : (uint8_t*)0 )
```

throwing this error that causes the "non-constant condition for static assertion" error


```
endstop_interrupts.h:57:57: error: reinterpret_cast from integer to pointer

                                     WITHIN(p, 62, 69) ? &PCICR : (uint8_t*)0 )
```

with windows-store version 1.8.21.0 working perfectly.

**Comment by disappear123df** [comment]
i deactivate ENDSTOP_INTERRUPTS in the Configuration.h

**Comment by sublime392** [comment]
I have this error as well.  I can't compile after version 1.8.8. I ignored it up until now because I could use 1.8.8 but now I can't use that version because it doesn't work on Catalina. 

This is not user error @boelle.
Deactivating ENDSTOP_INTERRUPTS is not the proper configuration for the board I, and others, have.

**Comment by boelle** [comment]
> ide 1.8.10 and 1.8.11.

recommended is 1.9.0 beta or vscode+platform.io

**Comment by boelle** [comment]
> is not the proper

what is then?

**Comment by sublime392** [comment]
> > is not the proper
> 
> what is then?

What I mean to say is, the ENDSTOP_INTERRUPTS are supposed to be enabled. I have tried the 1.9.0 version and the same error exists there. 

As it is, I now have to use a windows laptop in order to compile.

**Comment by ansemjo** [comment]
I hit this same error before when trying to compile with the Arduino IDE. After updating to the latest commit I got a different error but still couldn't compile with the `ENDSTOP_INTERRUPTS_FEATURE` enabled.

Reproducible with PlatformIO and the latest example configuration for the Anet A8, see #15770.

Interestingly, it works fine on the `bugfix-1.1.x` branch.

**edit:** with PR #15771 I can compile via PlatformIO with this feature enabled again.

**Comment by dzamosenchuk** [comment]
I've tried to compile for Anet A2+ printer and have same error. I've tried Arduino IDE 1.8.10 and beta 1.9. 
I've tried Marlin versions 1.1.x and bugfix-1.1.x

**Comment by GMagician** [comment]
@dzamosenchuk please check my PR to see if it fixes this issue

**Comment by disappear123df** [comment]
Comment out ENDSTOP_INTERRUPTS in the Configuration.h on in it should do the trick

**Comment by ansemjo** [comment]
I checked @GMagician's updated PR and it compiled fine with Arduino IDE and `arduino-cli` while `ENDTOP_INTERRUPTS_FEATURE` was enabled. Thank you!

I used this script to check:

```bash
#!/usr/bin/env bash

# enter temporary directory
cd "$(mktemp -d)" && pwd

# clone marlin source, checkout pull request 15771
git clone https://github.com/MarlinFirmware/Marlin.git ./
git fetch origin pull/15771/head:pr15771
git checkout pr15771

# copy Anet A8 example config
cp config/examples/Anet/A8/Configuration* Marlin/

# compile with arduino-cli (ensure that LiquidCrystal library and Sanguino board definitions are installed)
arduino-cli compile --fqbn Sanguino\:avr\:sanguino\:cpu=atmega1284p Marlin/Marlin.ino
```
