### PR TITLE
Prevent undefined lcd_tmpfan_speed on NO_LCD_MENUS

### LINKED ISSUE #12993: 'lcd_tmpfan_speed' was not declared in this scope after 082f6a27
### Description

Commit 082f6a27 (ADAPTIVE_FAN_SLOWING extension to hotend thermal protection) has caused my configuration to fail on compile (`pio run`) with:
```
Compiling .pioenvs/sanguino_atmega1284p/src/src/module/stepper.cpp.o
Compiling .pioenvs/sanguino_atmega1284p/src/src/module/stepper_indirection.cpp.o
Compiling .pioenvs/sanguino_atmega1284p/src/src/module/temperature.cpp.o
Compiling .pioenvs/sanguino_atmega1284p/src/src/module/tool_change.cpp.o
Compiling .pioenvs/sanguino_atmega1284p/src/src/sd/Sd2Card.cpp.o
Compiling .pioenvs/sanguino_atmega1284p/src/src/sd/SdBaseFile.cpp.o
Compiling .pioenvs/sanguino_atmega1284p/src/src/sd/SdFatUtil.cpp.o
Marlin/src/module/temperature.cpp: In static member function 'static void Temperature::set_fan_speed(uint8_t, uint16_t)':
Marlin/src/module/temperature.cpp:168:7: error: 'lcd_tmpfan_speed' was not declared in this scope
lcd_tmpfan_speed[target] = speed;
^
```

I run a Sanguinololu with an i2c LCD, git diff of my `Configuration.h` / `Configuration_adv.h`: https://gist.github.com/comps/82bcae0de8ffb64175b610d040afac4f
Zip file provided as well, if you prefer that format.

### Steps to Reproduce
1. Apply the configuration diff on 082f6a27
2. `pio run`

### Additional
[082f6a27-lcd_tmpfan_speed-configuration.zip](https://github.com/MarlinFirmware/Marlin/files/2787510/082f6a27-lcd_tmpfan_speed-configuration.zip)

### PR DESCRIPTION
**Pull request by comps**
This fixes a build error introduced by 082f6a2 when NO_LCD_MENUS
is uncommented:
```
 Marlin/src/module/temperature.cpp: In static member function
 'static void Temperature::set_fan_speed(uint8_t, uint16_t)':
 Marlin/src/module/temperature.cpp:168:7: error: 'lcd_tmpfan_speed'
 was not declared in this scope
```
Given that `ENABLED(ULTRA_LCD)` is always true when `HAS_LCD_MENU`
is also true,
```cpp
 #if ENABLED(ULTIPANEL)
   ...
   #define ULTRA_LCD
 #endif
 ...
 #define HAS_LCD_MENU  (ENABLED(ULTIPANEL) && DISABLED(NO_LCD_MENUS))
```
this shouldn't change the logic other than fixing the build error.

Fixes #12993.

### CODE REVIEW

**Comment by comps** [comment]
On further testing, this breaks my TMC config for some reason, investigating.

**Comment by comps** [comment]
Added a second commit fixing the TMC define. All my configs seem to compile now.
