### PR TITLE
lcm1602 support

### PR DESCRIPTION
**Pull request by schirrel**
Add support for LCM1602 adapter like https://magnusglad.files.wordpress.com/2013/03/lcd.jpg
 for hitachi hd44780

### CODE REVIEW

File: Marlin/ultralcd_implementation_hitachi_HD44780.h [hunk 1]
```diff
@@ -185,11 +185,17 @@
...
+    #include <Wire.h>
+    #include <LCD.h>
+    #include <LiquidCrystal_I2C.h>
+    #define LCD_CLASS LiquidCrystal_I2C
+      LCD_CLASS lcd(0x27, 2, 1, 0, 4, 5, 6, 7, 3, POSITIVE); // Addr, En, Rw, Rs, d4, d5, d6, d7, backlighpin, polarity
+  #else
+   #include <LiquidCrystal.h>
+    #define LCD_CLASS LiquidCrystal
+    LCD_CLASS lcd(LCD_PINS_RS, LCD_PINS_ENABLE, LCD_PINS_D4, LCD_PINS_D5, LCD_PINS_D6, LCD_PINS_D7); //RS,Enable,D4,D5,D6,D7
+    #endif#endif
```
Comment (Blue-Marlin) [inline Marlin/ultralcd_implementation_hitachi_HD44780.h:199]: ???

File: Marlin/ultralcd_implementation_hitachi_HD44780.h [hunk 2]
```diff
@@ -869,5 +875,5 @@ void lcd_implementation_drawedit(const char* pstr, char* value) {
   }
 
 #endif // LCD_HAS_SLOW_BUTTONS
-
+#endif
 #endif // ULTRALCD_IMPLEMENTATION_HITACHI_HD44780_H
```
Comment (Blue-Marlin) [inline Marlin/ultralcd_implementation_hitachi_HD44780.h:879]: ???

File: Marlin/ultralcd_implementation_hitachi_HD44780.h [hunk 3]
```diff
@@ -185,11 +185,17 @@
   #define LCD_CLASS LiquidCrystal_SR
   LCD_CLASS lcd(SR_DATA_PIN, SR_CLK_PIN);
 #else
-  // Standard directly connected LCD implementations
-  #include <LiquidCrystal.h>
-  #define LCD_CLASS LiquidCrystal
-  LCD_CLASS lcd(LCD_PINS_RS, LCD_PINS_ENABLE, LCD_PINS_D4, LCD_PINS_D5, LCD_PINS_D6, LCD_PINS_D7); //RS,Enable,D4,D5,D6,D7
-#endif
+  #ifdef LCM1602
+    #include <Wire.h>
```
Comment (Blue-Marlin) [inline Marlin/ultralcd_implementation_hitachi_HD44780.h:189]: #elif ?

File: Marlin/Marlin.ino [hunk 4]
```diff
@@ -43,8 +43,12 @@
   #elif ENABLED(DOGLCD)
     #include <U8glib.h> // library for graphics LCD by Oli Kraus (https://code.google.com/p/u8glib/)
   #else
-    #include <LiquidCrystal.h> // library for character LCD
-  #endif
+ #ifdef LCM1602
+      #include <LiquidCrystal_I2C.h>
```
Comment (Blue-Marlin) [inline Marlin/Marlin.ino:47]: #elif ?

File: Marlin/Configuration.h [hunk 5]
```diff
@@ -664,6 +664,7 @@ const bool Z_MIN_PROBE_ENDSTOP_INVERTING = false; // set to true to invert the l
   //#define DISPLAY_CHARSET_HD44780_CYRILLIC
 
 //#define ULTRA_LCD  //general LCD support, also 16x2
+//#define LCM1602 //support for lcm1602 adapter for 16x2 LCD
 //#define DOGLCD  // Support for SPI LCD 128x64 (Controller ST7565R graphic Display Family)
```
Comment (Blue-Marlin) [inline Marlin/Configuration.h:668]: Is LCM1602 important enough for this prominent position?

**Comment by thinkyhead** [comment]
Please address the issues [causing the build to fail](https://travis-ci.org/MarlinFirmware/Marlin/builds/116201618), and please re-submit against the `RCBugFix` branch. And, for best results you should apply your changes to a copy of the `RCBugFix` branch which is not named `RCBugFix`, leaving your `RCBugFix` branch unchanged:

```
git checkout RCBugFix -b rc_lcm1602_support
git push --set-upstream origin rc_lcm1602_support
```

**Comment by schirrel** [comment]
@Blue-Marlin if is that important i don't know but i had to use it, and as i was adapting me to use, and no one had done it before, for no one to face the things i face to figure out how to work with it i thought "why not?" to add it. But it's up for you guys

File: Marlin/ultralcd_implementation_hitachi_HD44780.h (hunk 1 above)
Comment (schirrel) [inline Marlin/ultralcd_implementation_hitachi_HD44780.h:199]: why ???
maybe because of     LCD_CLASS lcd(0x27, 2, 1, 0, 4, 5, 6, 7, 3, POSITIVE); 
 instead of LCD_CLASS lcd(LCD_PINS_RS, LCD_PINS_ENABLE, LCD_PINS_D4, LCD_PINS_D5, LCD_PINS_D6, LCD_PINS_D7); //RS,Enable,D4,D5,D6,D7
 ok i will make the change in pins so i use the pins variable instead of the numbers

File: Marlin/ultralcd_implementation_hitachi_HD44780.h (hunk 2 above)
Comment (schirrel) [inline Marlin/ultralcd_implementation_hitachi_HD44780.h:879]: i accidentaly delete this endif

File: Marlin/ultralcd_implementation_hitachi_HD44780.h (hunk 3 above)
Comment (schirrel) [inline Marlin/ultralcd_implementation_hitachi_HD44780.h:189]: you are right, was a bad practice of mine

File: Marlin/Marlin.ino (hunk 4 above)
Comment (schirrel) [inline Marlin/Marlin.ino:47]: a bad practice again, sorry

**Comment by schirrel** [comment]
@thinkyhead ah, i will fix it and do it at the right place, i'm still having trouble on doing pull request, sorry;
also, wha t i saw is that the error happens in functino that saying "was not declared in this scope" but i compile it and i'm using it and it gives me no errors :S

**Comment by thinkyhead** [comment]
@CoderSquirrel I advise you read all of Github's documentation on branching and making pull requests. Also please go through this interactive tutorial: http://pcottle.github.io/learnGitBranching/

If you still find it difficult to apply your changes in a new branch, someone here may be able to do it on your behalf. But we prefer if the original author gets credit for their commits.

File: Marlin/ultralcd_implementation_hitachi_HD44780.h (hunk 1 above)
Comment (Blue-Marlin) [inline Marlin/ultralcd_implementation_hitachi_HD44780.h:199]: ??? because of "#endif#endif"

File: Marlin/ultralcd_implementation_hitachi_HD44780.h (hunk 2 above)
Comment (Blue-Marlin) [inline Marlin/ultralcd_implementation_hitachi_HD44780.h:879]: No. You added on. The addition seems unrelated to your other changes.Ether you fixed a bug, or you introduced one.

**Comment by Blue-Marlin** [comment]
> @Blue-Marlin if is that important i don't know but i had to use it, and as i was adapting me to use, and no one had done it before, for no one to face the things i face to figure out how to work with it i thought "why not?" to add it. But it's up for you guys

No, no, no. I tried to talk about a section for I2C/TWI displays a bit further down in the file. 
It's not a **main** display type like DOGLCD that describes the class of full graphic displays.

**Comment by thinkyhead** [comment]
Right. What @Blue-Marlin said. There's a better place for the `#define LCM1602` line slightly further down in the same file. When you make your new PR we can try to figure out the best place for it.

**Comment by schirrel** [comment]
Thanks @thinkyhead , i have done the 

> git checkout RCBugFix -b rc_lcm1602_support
> git push --set-upstream origin rc_lcm1602_support

and create the rc_lcm1602_support branch, and so i applied the changes, for make the pPR i will make it against which  branch here?

**Comment by jbrazio** [comment]
@CoderSquirrel RCBugFix please
