### PR TITLE
NoVolumetrics compilation error ' only for 1.1.8' works fine on 2.0

### PR DESCRIPTION
**Pull request by ghost**
When enabling NOVOLUMETRICS , the compilation fails , because , of some missing compilation conditionnals  existing on 2.0 but not reported on 1.1.8
And If possible , leave NOVOLUMETRIC always on by default because not very used in majority

### CODE REVIEW

**Comment by thinkyhead** [comment]
We don't patch 1.1.x, only the bugfix branches. Please check the bugfix branches to see if this is already patched, then resubmit if needed. Thanks!
