### ISSUE TITLE
[BUG] SD card not working on Megatronics V3.1 by install Marlin 2.0.4.3

### ISSUE THREAD

**Issue by swatkxs** [MarlinFirmware/Marlin#17003]
I have compiled both marlin 2.0.4.3 and 1.1.7, confirmed SD card working at 1.1.7, but showing No Media at 2.0.4.3.
[config.zip](https://github.com/MarlinFirmware/Marlin/files/4260462/config.zip)

**Comment by ellensp** [comment]
Version 2.0.4.4 has been released...  lots of changes. Give this a try.

**Comment by ellensp** [comment]
The other question that comes to mind is does the controller notice if you plug a sdcard in or take it out?

**Comment by swatkxs** [comment]
still useless on 2.0.4.4, and the controller does not notice when I plug in & out

**Comment by swatkxs** [comment]
compiling comes some error on 2.0.4.4
{
	"resource": "/f:/CR-10 Firmware/Megatronics3.1/Marlin-2.0.4.4/Marlin/src/core/serial.h",
	"owner": "cpp",
	"severity": 8,
	"message": "expected ')' before string constant",
	"startLineNumber": 251,
	"startColumn": 59,
	"endLineNumber": 251,
	"endColumn": 59
}

{
	"resource": "/f:/CR-10 Firmware/Megatronics3.1/Marlin-2.0.4.4/Marlin/src/gcode/queue.cpp",
	"owner": "cpp",
	"severity": 8,
	"message": "'MSG_SD_ERR_READ' was not declared in this scope",
	"startLineNumber": 530,
	"startColumn": 50,
	"endLineNumber": 530,
	"endColumn": 50
}

**Comment by ellensp** [comment]
in queue.cpp find  MSG_SD_ERR_READ and change it to STR_SD_ERR_READ
This has been fixed in bugfix....

**Comment by tpruvot** [comment]
on 2.0.x branch too (updated a hour ago)
