### PR TITLE
regression in 1d8ad7c breaks Re-ARM builds: "Marlin\src\core\utility.h:36:5: error: 'UNUSED' was not declared in this scope"

### PR DESCRIPTION
**Pull request by salfter**
### Description

I pulled in the latest round of updates from bugfix-2.0.x last week, but when I went to build it for my Re-ARM-equipped A8, compilation stopped here:

```
Compiling .pio\build\LPC1768\src\src\feature\I2CPositionEncoder.cpp.o
In file included from Marlin\src\core\utility.cpp:23:
Marlin\src\core\utility.h: In function 'void serial_delay(millis_t)':
Marlin\src\core\utility.h:36:5: error: 'UNUSED' was not declared in this scope
     UNUSED(ms);
     ^~~~~~
Marlin\src\core\utility.h:36:5: note: the macro 'UNUSED' had not yet been defined
In file included from e:\tmp\marlin\marlin\src\hal\hal_lpc1768\hal.h:39,
                 from e:\tmp\marlin\marlin\src\hal\hal.h:26,
                 from Marlin\src\core\../inc/MarlinConfig.h:30,
                 from Marlin\src\core\../Marlin.h:24,
                 from Marlin\src\core\utility.cpp:25:
e:\tmp\marlin\marlin\src\hal\shared\marduino.h:84: note: it was later defined here
   #define UNUSED(x) ((void)(x))
```

It looks like commit 1d8ad7c removed the definition of UNUSED in Marlin/src/core/macros.h.  Reversing that commit's change to that file should fix this regression.

### Benefits

Fixes builds for Re-ARM, and possibly other LPC1768 boards.

### Related Issues

#15277

### CODE REVIEW

**Comment by thinkyhead** [comment]
Files that want this macro should include "HAL/Marduino.h" instead. This ensures that the `UNUSED` macro provided by the platform is the one that gets used, and we don't have to do choose a different macro based on our expert knowledge of various cores.
