### ISSUE TITLE
TMC2130 & 2208 Error compile on Latest commit BugFix 2.0.x

### ISSUE THREAD

**Issue by Ccleorina87** [MarlinFirmware/Marlin#11849]
```
1) Marlin\src\feature\tmc_util.cpp:283:39: error: 'tmc_axes' was not declared in this scope

2) Marlin\src\feature\tmc_util.cpp:253:3: error: expected ',' or ';' before 'static'

3) Marlin\src\feature\tmc_util.cpp:238:7: error: expected unqualified-id before ',' token
```
Error on tmc_util.cpp

**Comment by thinkyhead** [comment]
Patched!

**Comment by Ccleorina87** [comment]
thanks... for the patch
