### ISSUE TITLE
Issue with compiling 2.0.x, "error: 'R_SENSE' …"

### ISSUE THREAD

**Issue by DerEchteLanger** [MarlinFirmware/Marlin#12342]
Hi! Im currently trying to compile 2.0.X which i downloaded a few hours ago using Arduino 1.9.0 beta. Since im using TMC2130 drivers in my printer i also downloaded the libary "TMCStepper" version 0.2.2.

When trying to compile i get lots of Errors, all of them from `stepper_indirection.cpp`…

Edit: Since Github screws up the error formating a pastebin link instead:

https://pastebin.com/GyxY0u7U

If i try compiling with TMC2130 2.5.0 i get this Error "sketch\src\module/stepper_indirection.h:59:26: fatal error: TMCStepper.h: No such file or directory" so i assume 0.2.2 is the right one...

My first question would be if this is even the right place for this issue or if i should go to https://github.com/teemuatlut/TMCStepper?

[configs.zip](https://github.com/MarlinFirmware/Marlin/files/2550337/configs.zip)

**Comment by swilkens** [comment]
https://github.com/MarlinFirmware/Marlin/issues/12144

> Recommend you stick with the old code until @teemuatlut has completed TMCStepper.

**Comment by DerEchteLanger** [comment]
The old TMC2130Stepper doesnt seem to work with the most recent Marlin 2.0.X, which version am i supposed to use? My old copy of 2.0.X is from May i think...

**Comment by teemuatlut** [comment]
You have an issue with your config files.
```diff
-#if HAS_TRINAMIC
+#if ENABLED(HAVE_TMC2130) || ENABLED(HAVE_TMC2208)
```
Revert that.

**Comment by DerEchteLanger** [comment]
Thanks, i copied that over from my old config...

**Comment by thinkyhead** [comment]
> Since Github screws up the error [formatting]…

GitHub uses [Markdown](https://guides.github.com/features/mastering-markdown/).

![image](https://user-images.githubusercontent.com/698003/48116152-d089dd80-e22a-11e8-8ecd-bc6c1a97a19f.png)

You should use three backticks ` ``` ` on a line by itself before and after things that you want to appear as blocks of plaintext.

**Comment by MiguelCastillo** [comment]
Hello folks - do we know when TMC2130Stepper support might be completed?

**Comment by teemuatlut** [comment]
Two years ago?

**Comment by MiguelCastillo** [comment]
lolol! gotcha. Ok i thought this was somehow related to `The old TMC2130Stepper doesnt seem to work with the most recent Marlin 2.0.X` which Im currently running into with an einsy rambo board.

**Comment by boelle** [comment]
@DerEchteLanger problem solved?

**Comment by DerEchteLanger** [comment]
yes

**Comment by boelle** [comment]
then click green close button
