### PR TITLE
Fix _temp_error-related compile error

### PR DESCRIPTION
**Pull request by Idorobots**
### Description

Fixes the compilation errors introduced in #13756 and https://github.com/MarlinFirmware/Marlin/commit/bddb776ddb6aa8eb0eb9a15f701df24940b02b46, with a little compromise on the error message format - instead of using the specific message, it'll format the error as `<what failed>: <what kind of failure it was>`.

### Benefits

Code compiles again.

### Related Issues

https://github.com/MarlinFirmware/Marlin/issues/13770

### CODE REVIEW

**Comment by Patag** [comment]
Thanks Idorobots, it's compiling fine now

File: Marlin/src/module/temperature.cpp [hunk 1]
```diff
@@ -86,12 +86,12 @@ Temperature thermalManager;
  */
 
 #if HAS_HEATED_BED
-  #define _BED_PSTR(M,E) (E) == -1 ? PSTR(MSG_BED ": " M) :
+  #define _BED_PSTR(M,E) (E) == -1 ? PSTR(M ## _BED) :
```
Comment (Idorobots) [inline Marlin/src/module/temperature.cpp]: That's the part that doesn't compile. `M` get's expanded all the way to a string and it attempts to append `_BED` to it. I'm not sure if there's a way to make this work with the current setup, other than switching on the message type an selecting the one for the bed/chamber.

Comment (thinkyhead) [reply Marlin/src/module/temperature.cpp]: It can be made to work. I will experiment further.

Comment (Idorobots) [reply Marlin/src/module/temperature.cpp]: Perhaps moving the underscore to the call site? As long as it doesn't expand any further it should append and then expand correctly, right? So, `PSTR(M ## BED)` here and `MSG_THERMAL_RUNAWAY_` at the call site?

Comment (thinkyhead) [reply Marlin/src/module/temperature.cpp]: A commit has been added that should do the trick.
