### ISSUE TITLE
expected '}' before numeric constant

### ISSUE THREAD

**Issue by Roiij117** [MarlinFirmware/Marlin#24507]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Hi,

I'm a nood at this so plz bear with me...

I've upgraded my ender 3 with a BTT SKR  1.4 Turbo and now I'm trying to compile the firmware for this.
Sadly I know nothing about coding, so youtube it is :)
I've been trying a few days with different versions and already compiled versions and so on, always different errors.
Now I use the latest and I get a few errors like the one below.
What do I need to change?
I also uploaded a copy of the configuration files.

In file included from Marlin\src\module\../inc/MarlinConfigPre.h:37,
                 from Marlin\src\module\../inc/MarlinConfig.h:28,
                 from Marlin\src\module\motion.h:31,
                 from Marlin\src\module\motion.cpp:27:
Marlin\src\module\../inc/../../Configuration.h:1457:19: error: expected '}' before numeric constant
 1457 | #define Y_MIN_POS 0

All help is much appreciated!

### Bug Timeline

Error because of me...

### Expected behavior

Success in compiling

### Actual behavior

Error

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

Ender 3

### Electronics

BTT SKR 1.4 Turbo

### Your Slicer

Simplify3D

### Host Software

Same as my slicer

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/9126031/Marlin.zip)

**Comment by thisiskeithb** [comment]
> Did you test the latest bugfix-2.1.x code?
> Yes, and the problem still exists.

These configs are for an older version of Marlin and would not compile with the latest version.

Using the configs from [MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Creality/Ender-3/BigTreeTech SKR 1.4](https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Creality/Ender-3/BigTreeTech%20SKR%201.4) & disabling `SHOW_CUSTOM_BOOTSCREEN` & `CUSTOM_STATUS_SCREEN_IMAGE`, they compile fine with the latest `bugfix-2.1.x`.
