### PR TITLE
[2.0.x] Fixed compile error due to assignment to const ptr.

### PR DESCRIPTION
**Pull request by marcio-ao**
- Regression introduced in commit 31c28d0dd2

```
src/gcode/gcode.cpp: In static member function 'static void GcodeSuite::process_subcommands_now(char*)':
src/gcode/gcode.cpp:793:25: error: assignment of read-only location '*(const char*)delim'
       if (delim) *delim = '\0';                         // Replace with nul
                         ^
compilation terminated due to -Wfatal-errors.
Makefile:838: recipe for target 'applet/src/gcode/gcode.o' failed
make: *** [applet/src/gcode/gcode.o] Error 1
```

### CODE REVIEW

**Comment by marcio-ao** [comment]
Also, I made it so USE_EXECUTE_COMMANDS_IMMEDIATE isn't redefined if it is already defined. We use `process_subcommands_now_P` a lot in our firmware, even in firmware that does not have bed leveling, so we define USE_EXECUTE_COMMANDS_IMMEDIATE in "Config.h" and your latest commit was causing it to be turned off when G29_RETRY_AND_RECOVER was disabled.

It seems like USE_EXECUTE_COMMANDS_IMMEDIATE is a useful enough feature that it ought to stand alone.

File: Marlin/src/inc/Conditionals_post.h [hunk 1]
```diff
@@ -1619,7 +1619,9 @@
 // If platform requires early initialization of watchdog to properly boot
 #define EARLY_WATCHDOG (ENABLED(USE_WATCHDOG) && defined(ARDUINO_ARCH_SAM))
 
-#define USE_EXECUTE_COMMANDS_IMMEDIATE ENABLED(G29_RETRY_AND_RECOVER)
+#ifndef USE_EXECUTE_COMMANDS_IMMEDIATE
+  #define USE_EXECUTE_COMMANDS_IMMEDIATE ENABLED(G29_RETRY_AND_RECOVER)
+#endif
```
Comment (thinkyhead) [inline Marlin/src/inc/Conditionals_post.h]: This isn't quite compatible with the usage of `USE_EXECUTE_COMMANDS_IMMEDIATE`. Configurable switches are simply defined with `#define THE_SWITCH` and can be tested with `#if ENABLED(THE_SWITCH)`, whereas conditionals are set to a pre-compiler true/false value and in the code are tested with `#if THE_CONDITION`. So this would require someone to add a line like `#define USE_EXECUTE_COMMANDS_IMMEDIATE 1` to their configuration. But doing so wouldn't be of any benefit because the presence of the immediate sub-commands functions is entirely dependent on features that use it being enabled, so enabling them outside of having any features that use them is only useful for developer hacking.

**Comment by thinkyhead** [comment]
`USE_EXECUTE_COMMANDS_IMMEDIATE` isn't a feature switch, but a conditional. If your firmware uses the immediate sub-commands, then you should just change the conditional to mention your feature that uses it.
```cpp
#define USE_EXECUTE_COMMANDS_IMMEDIATE (ENABLED(G29_RETRY_AND_RECOVER) || ENABLED(ALEPHOBJECTS_FEATURES))
```

File: Marlin/src/inc/Conditionals_post.h (hunk 1 above)
Comment (marcio-ao) [reply Marlin/src/inc/Conditionals_post.h]: > But doing so wouldn't be of any benefit because the presence of the immediate sub-commands functions is entirely dependent on features that use it being enabled, so enabling them outside of having any features that use them is only useful for developer hacking.

You are looking at it just from the perspective of individual users, for companies like ours, there has always been a need to tweak the firmware beyond what makes sense to push upstream. For example, I have modified our firmware to inject additional commands after a print abort. I think "process_subcommands_now_P" is an effective way to make small tweaks like that, far superior than having to write a bunch of C++ code.

**Comment by marcio-ao** [comment]
> ```c++
> #define USE_EXECUTE_COMMANDS_IMMEDIATE (ENABLED(G29_RETRY_AND_RECOVER) || ENABLED(ALEPHOBJECTS_FEATURES))
> ```

That would work. I will implement that suggestion.
