### ISSUE TITLE
[BUG] Compile Error 

### ISSUE THREAD

**Issue by QuePID** [MarlinFirmware/Marlin#27144]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Marlin fails to compile on BTT Octopus Max EZ v1.0 with BTT TFT35 E3 touch screen. 

...
Processing STM32H723ZE_btt (board: marlin_STM32H723ZE; platform: ststm32@15.4.1; framework: arduino)
-----------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
In file included from d:\marlin-2.1.2.3\marlin\src\pins\pins.h:754,
                 from d:\marlin-2.1.2.3\marlin\src\inc\marlinconfig.h:36,
                 from buildroot/share/PlatformIO/scripts/common-dependencies.h:29:
d:\marlin-2.1.2.3\marlin\src\pins\stm32h7/pins_BTT_OCTOPUS_MAX_EZ.h:462:4: error: #error "Only BTT_MINI_12864 (BTT Mini 12864 V2.0 with FPC cable) is currently supported on the BIGTREE_OCTOPUS_MAX_EZ."
  462 |   #error "Only BTT_MINI_12864 (BTT Mini 12864 V2.0 with FPC cable) is currently supported on the BIGTREE_OCTOPUS_MAX_EZ."
      |    ^~~~~
Error: Failed to parse Marlin features. See previous error messages.
============================================================ [FAILED] Took 1.69 seconds ============================================================

Environment      Status    Duration
---------------  --------  ------------
STM32H723ZE_btt  FAILED    00:00:01.689
======================================================= 1 failed, 0 succeeded in 00:00:01.689 =======================================================

### Bug Timeline

I noticed bug with Marlin 2.1.2.1 onwards

### Actual behavior

I expected Marlin firmware to compile successfully as usual.

### Steps to Reproduce

Use Visual Studio Code & PlatformIO to compile Marlin 2.1.2.3 and observe error.

### Version of Marlin Firmware

2.1.2.33

### Printer model

Ender 3 Pro with BTT Octopus Max EZ v1.0 board using EZ2209 stepper drivers

### Electronics

BTT Octopus Max EZ with BTT TFT35 E3 touch screen

### LCD/Controller

BTT TFT35 E3 

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin_compile_issue.zip](https://github.com/user-attachments/files/15523819/Marlin_compile_issue.zip)
![Screenshot 2024-06-01 212635](https://github.com/MarlinFirmware/Marlin/assets/15154777/bb725212-a0dc-4151-8760-88f41e526b5c)

**Comment by thisiskeithb** [comment]
As the error states:

> Only BTT_MINI_12864 (BTT Mini 12864 V2.0 with FPC cable) is currently supported on the BIGTREE_OCTOPUS_MAX_EZ.

All you need to do for one of BTT's TFT on this motherboard is enable the proper serial port & follow the Marlin Dependencies section of the TFT firmware readme: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware?tab=readme-ov-file#marlin-dependencies

You will not have access to "Marlin Mode".

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
