### ISSUE TITLE
[BUG] Teensy HAL: defining BEEPER_PIN causes compilation to fail

### ISSUE THREAD

**Issue by salfter** [MarlinFirmware/Marlin#13513]
### Description

Doing some work on a Teensy 3.6 shield (latest update and a render are at https://reprap.org/forum/read.php?2,850018,850211#msg-850211), but when I went to put the latest pins definition on a Teensy, the build failed:

```
Compiling .pioenvs/teensy36/src/src/libs/buzzer.cpp.o
In file included from Marlin/src/libs/../inc/MarlinConfig.h:30:0,
from Marlin/src/libs/buzzer.cpp:23:
Marlin/src/libs/buzzer.cpp: In static member function 'static void Buzzer::tick()':
Marlin/src/libs/../inc/../HAL/HAL_TEENSY35_36/HAL.h:87:66: error: '__get_PRIMASK' was not declared in this scope
#define CRITICAL_SECTION_START  uint32_t primask = __get_PRIMASK(); __disable_irq()
Compiling .pioenvs/teensy36/src/src/libs/hex_print_routines.cpp.o
^
Marlin/src/libs/buzzer.cpp:70:9: note: in expansion of macro 'CRITICAL_SECTION_START'
CRITICAL_SECTION_START;
^
*** [.pioenvs/teensy36/src/src/libs/buzzer.cpp.o] Error 1
```

Thinking it may have just been an issue with the pins file I created, I tried again with the stock Teensy 3.5/3.6 configuration (```#define MOTHERBOARD TEENSY35_36```)...still no joy.

I've traced it to a missing ```#include <util/atomic.h>```, and that the name of the function is defined in atomic.h as __get_primask, not __get_PRIMASK.  A PR will be submitted shortly.

### Steps to Reproduce

1. ```#define BEEPER_PIN 50``` (or something) when building for Teensy 3.5/3.6
2. start the build
3. watch it fail

**Expected behavior:** [What you expect to happen]

build succeeds
