### ISSUE TITLE
[BUG] (Last bugfix does not compile)

### ISSUE THREAD

**Issue by Bergerac56** [MarlinFirmware/Marlin#13868]
Last bugfix : 408a5f08dc5c43fc17c8dfb07271d941594c2ef6 does not compile. 
The problem seems to have been introduced by commit 2740cc64d841eec1fb97c7dbd1b40da559606314
At line 280 of menu_main.cpp,  #elif does not seem to be correct

Compiling .pioenvs\LPC1768\src\src\lcd\menu\menu_main.cpp.o
Marlin\src\lcd\menu\menu_main.cpp:280:12: error: #elif with no expression
#elif
^
*** [.pioenvs\LPC1768\src\src\lcd\menu\menu_main.cpp.o] Error 1

**Comment by RudyBenner** [comment]
![image](https://user-images.githubusercontent.com/40361032/57025609-9e6b9e00-6c05-11e9-84ed-00dfb48f3295.png)

**Comment by Bergerac56** [comment]
Exactly what I did ;)
