### ISSUE TITLE
[BUG]  #22919 breaks the BTT SKR Mini E3 V2 _maple target

### ISSUE THREAD

**Issue by Zwaubel** [MarlinFirmware/Marlin#22952]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

#22919 breaks the _maple target when using the BTT SKR Mini E3 V2 aka STM32F1.
As stated in the thread of the pull request, SDA and SCL are not defined and the following errors are thrown during the build process:

```
In file included from Marlin\src\HAL\shared\../../inc/../pins/pins.h:521:0,
                 from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:34,
                 from Marlin\src\HAL\shared\eeprom_if_i2c.cpp:28:
Marlin\src\HAL\shared\../../inc/../pins/stm32f1/pins_BTT_SKR_MINI_E3_V2_0.h:33:44: error: 'SDA' was not declared in this scope
   #define I2C_SDA_PIN                      SDA
                                            ^
Marlin\src\HAL\shared\eeprom_if_i2c.cpp:36:36: note: in expansion of macro 'I2C_SDA_PIN'
   SlowSoftWire Wire = SlowSoftWire(I2C_SDA_PIN, I2C_SCL_PIN, true);
                                    ^~~~~~~~~~~
Marlin\src\HAL\shared\../../inc/../pins/stm32f1/pins_BTT_SKR_MINI_E3_V2_0.h:34:44: error: 'SCL' was not declared in this scope
   #define I2C_SCL_PIN                      SCL
                                            ^
Marlin\src\HAL\shared\eeprom_if_i2c.cpp:36:49: note: in expansion of macro 'I2C_SCL_PIN'
   SlowSoftWire Wire = SlowSoftWire(I2C_SDA_PIN, I2C_SCL_PIN, true);
                                                 ^~~~~~~~~~~
Marlin\src\HAL\shared\../../inc/../pins/stm32f1/pins_BTT_SKR_MINI_E3_V2_0.h:34:44: note: suggested alternative: 'SCK'
   #define I2C_SCL_PIN                      SCL
                                            ^
Marlin\src\HAL\shared\eeprom_if_i2c.cpp:36:49: note: in expansion of macro 'I2C_SCL_PIN'
   SlowSoftWire Wire = SlowSoftWire(I2C_SDA_PIN, I2C_SCL_PIN, true);
                                                 ^~~~~~~~~~~
```
@thisiskeithb is informed and will attempt to fix the _maple target.

### Bug Timeline

new - introduced with #22919

### Expected behavior

The _maple target of the BTT SKR Mini E3 V2 compiling just fine.

### Actual behavior

During the build process of the _maple target when using a BTT SKR Mini E3 V2 the above error messages are thrown and the build fails.

### Steps to Reproduce

1. Choose a STM32F1*_maple target in the platform.ini file
2. Click compile
3. Build fails at `src\HAL\shared\eeprom_if_i2c.cpp.o`

### Version of Marlin Firmware

latest bugfix

### Printer model

Ender 3 V2

### Electronics

BTT SKR Mini E3 V2 aka STM32F1

### Add-ons

none

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Additional information & file uploads

[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/7341011/Configurations.zip)

**Comment by ellensp** [comment]
I see no reason to fix this. _Maple is obsolete. If it works on  non maple. the maple option for this board should just be removed.  As this is where we are heading.

**Comment by thisiskeithb** [comment]
> I see no reason to fix this. _Maple is obsolete. If it works on non maple. the maple option for this board should just be removed. As this is where we are heading.

I’m with you on this, but it’ll need to be maintained until then.

@Zwaubel: Is there something preventing you from using the non-maple envs? Use one of those for now.

**Comment by Zwaubel** [comment]
I'm fine with switching to a non maple target.
I started using maple a year ago only because back then it felt like the better performing and less storage consuming target on a stm32f1. But as it seems this isn't valid anymore. 
So yes, I agree with removing all stm32f1**_maple targets.
On that note, feel free to close this ticket.

**Comment by ellensp** [comment]
"So yes, I agree with removing all stm32f1**_maple targets."
Well we can't do this yet, many are non functional.  
Each needs looking at individually, and if this one is fine without maple, then this one can have the _maple options removed.

**Comment by Zwaubel** [comment]
I agree with you as well. Testing should be done beforehand.
But if maple is deprecated, devs shouldn't spend to much time fixing bugs related to those targets.

**Comment by thisiskeithb** [comment]
I've updated the SKR Mini E3 V2's pins file to use the real pin numbers instead of aliases: https://github.com/MarlinFirmware/Marlin/pull/22955

**Comment by thisiskeithb** [comment]
#22919 / #22955 have been merged and should take care of the remaining EEPROM issues.
