### ISSUE TITLE
[FR] allow LCD to display long file names

### ISSUE THREAD

**Issue by junwoo091400** [MarlinFirmware/Marlin#8950]
Hello, would it be possible to show full-name of the .gcode File by 'flowing' animation?

if it can be implemented without too much memory consumption, it can be useful to people who name their files very long.

Or is this feature implemented already?

Thank you for reading my issue.

**Comment by cjsoong** [comment]
Configuration_adv.h
// Enable this option to scroll long filenames in the SD card menu
  //#define SCROLL_LONG_FILENAMES

**Comment by junwoo091400** [comment]
@cjsoong  OOPS, thank you so much. My bad not reading through Configuration_adv.h thoroughly.. :)

**Comment by v1ru3** [comment]
only problem is, it doesn't compile in 1.1.8:

cardreader.cpp:726: error: incompatible types in assignment of 'char*' to 'char [66]'

               sortnames[i] = strdup(LONGEST_FILENAME);
