### ISSUE TITLE
G38 Probe_Target Fail Build[BUG] (bug summary)

### ISSUE THREAD

**Issue by mrmazakblu** [MarlinFirmware/Marlin#25997]
[Marlin_rotary_config.zip](https://github.com/MarlinFirmware/Marlin/files/11804100/Marlin_rotary_config.zip)
### ### Did you test the latest `bugfix-2.1.x` code?

Yes Build with`bugfix-2.1.x`  solves the probe_target issue, and introduced a new issue. "Unable to add rotary_axis"
### Bug Description

I have used Marlin for CNC style Laser. With touch probe. Probe target did work in 2.1.1, but now in 2.1.2.1 I get error from endstop.cpp.
error quote

Marlin\src\module\endstops.cpp: In static member function 'static void Endstops::update()':
Marlin\src\module\endstops.cpp:1114:40: error: 'value_t' was not declared in this scope
       const Flags<NUM_AXES> moving = { value_t(NUM_AXES)(0 MAIN_AXIS_MAP(_G38_SET)) };

Confirmed same build time error with default config(after adding "probe" and "probe_target" options

### Bug Timeline

first seen with release 2.1.2.*

### Expected behavior

Compile with probe target option enabled

### Actual behavior

Errors at build time

### Steps to Reproduce

Start with fresh marlin source and default config. 
!. enable "#define FIX_MOUNTED_PROBE" in configuration.h"
2. enable "#define G38_PROBE_TARGET" in configuration_adv.h
3. Compile stops with the error  shown above

### Version of Marlin Firmware

2.1.2.1

### Printer model

mega 2560 ramps 1.4

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

tested with stock(from firmware, not config repo) config to test build, then enabled fixed probe, probe uses Z min endstop, enabled probe_towards in config_adv

CONFIGS TESTED ARE THE DEFAULT ones downloaded with source.
[Marlin_rotary_config.zip](https://github.com/MarlinFirmware/Marlin/files/11804192/Marlin_rotary_config.zip)

**Comment by mrmazakblu** [comment]
basic build on bugix 2.1.X did compile, with extruder set to 1, I need to build again with set to 0. 

at this point its only thing "major" that seems different. 

...
SO far bugfix builds , . 

Must of been me, Of course. 
'

**Comment by mrmazakblu** [comment]
More details. I had a 4th axis enabled AND probe_target enabled and working in release 2.1.1 , the probe target seemed to break in release 2.1.2 , in bugfix 2.1.2 probe target built, but now 4th axis would not build.  

I need to split this into 2 issues.
1.  The original problem I found was Probe_toward not working in 2.1.2.1, Work around for this problem was somewhere in the bugfix release
2.  The second found issue was am issue adding a fourth axis, "I" in my case,
