### ISSUE TITLE
Two extruder one Hotend does not work with Marlin on Ramps 1.4?

### ISSUE THREAD

**Issue by KayIO** [MarlinFirmware/Marlin#5549]
Hello !
I have an issue when compiling the Marlin code 1.1.0RC8 for use with dual extruder, but only one hot end.
I used to go with this: 
https://www.kickstarter.com/projects/811909269/the-prometheus-system-intuitive-multi-filament-3d

But whenever I try to compile the code it stops with an error:

> In file included from sketch\MarlinConfig.h:39:0,
>                  from Y:\Dokumente\3D Printer\Firmware\Tronxy X3\Marlin1.1.0RC8\Marlin-RC\Marlin\Marlin.ino:37:
> SanityCheck.h:741: error: #error "HEATER_1_PIN not defined for this board."
>      #error "HEATER_1_PIN not defined for this board."
> exit status 1
> #error "HEATER_1_PIN not defined for this board."

I also set one fake temp sensor, but his doesn't work.
Isn't such dual extruding solution supported ? I'm not sure if this is an issue or a feature request.

Thanks in advance`
-Kay-

**Comment by KayIO** [comment]
Sorry ! It was a fault by me ...
Found the right definition.... 
Forgot to set 
#define SINGLENOZZLE
Sorry sorry sorry
