### ISSUE TITLE
[BUG] TANGO (Rumba) -> E0_AUTO_FAN_PIN and FAN_PIN

### ISSUE THREAD

**Issue by Aurawin** [MarlinFirmware/Marlin#15651]
I've had this problem in the past, I want to swap E0_AUTO_FAN_PIN and FAN_PIN at the same time.

The Tango board is almost identical to the Rumba.  The tango has E0 as Fan 1 and Fan 0 as the cooler fan.  Both are PWM. 

Previously, I would just re-arrange the wires but thinking forward others won't know they've inadvertently wired their fans properly. Because of this, I think we should have a Tango pins file.

But in the meantime, relying on the Config files it's not possible to   

#define FAN_PIN             8
#define E0_AUTO_FAN_PIN 7

Marlin/src/gcode/control/M42.cpp: In static member function 'static void GcodeSuite::M42()':
Marlin/src/gcode/control/M42.cpp:62:9: error: duplicate case value
         case FAN1_PIN: thermalManager.fan_speed[1] = pin_status; break;
         ^

**Comment by Aurawin** [comment]
Looking at PINS_RUMBA.h lines 143-146

#ifndef FAN_PIN
  #define FAN_PIN           7
#endif
#define FAN1_PIN            8

Line 146 (IMO) is wrong.  It should be prefaced with the conditional that it's not previously defined and should be modifiied to look like:
#ifndef FAN1_PIN
#define FAN1_PIN            8
#endif

Without these changes (and I do make them with every pull) I can't compile.  Please help remedy it.
#define FAN_PIN         8
#define FAN1_PIN -1
#define E0_AUTO_FAN_PIN 7

**Comment by SwiftNick** [comment]
Try using undef first
```
  #undef FAN1_PIN
  #define FAN1_PIN 8
```

**Comment by Aurawin** [comment]
> Try using undef first
> 
> ```
>   #undef FAN1_PIN
>   #define FAN1_PIN 8
> ```


> Executing task: platformio run <
<SNIP>
In file included from Marlin/src/gcode/control/../../inc/../pins/pins.h:150:0,
                 from Marlin/src/gcode/control/../../inc/MarlinConfig.h:32,
                 from Marlin/src/gcode/control/../gcode.h:279,
                 from Marlin/src/gcode/control/M85.cpp:23:
Marlin/src/gcode/control/../../inc/../pins/ramps/pins_RUMBA.h:147:0: warning: "FAN1_PIN" redefined
   #define FAN1_PIN            8
 ^
In file included from Marlin/src/gcode/control/../../inc/MarlinConfigPre.h:56:0,
                 from Marlin/src/gcode/control/../../inc/MarlinConfig.h:28,
                 from Marlin/src/gcode/control/../gcode.h:279,
                 from Marlin/src/gcode/control/M85.cpp:23:
Marlin/src/gcode/control/../../inc/../../Configuration_adv.h:352:0: note: this is the location of the previous definition
 #define FAN1_PIN -1
 ^
Marlin/src/gcode/control/M42.cpp: In static member function 'static void GcodeSuite::M42()':
Marlin/src/gcode/control/M42.cpp:62:9: error: duplicate case value
         case FAN1_PIN: thermalManager.fan_speed[1] = pin_status; break;
         ^
Marlin/src/gcode/control/M42.cpp:59:9: error: previously used here
         case FAN0_PIN: thermalManager.fan_speed[0] = pin_status; break;
         ^
*** [.pio/build/megaatmega2560/src/src/gcode/control/M42.cpp.o] Error 1
================================================= [FAILED] Took 3.71 seconds

**Comment by SwiftNick** [comment]
Is it because  ```#define HEATER_3_PIN        8``` is using the same pin?

**Comment by boelle** [comment]
if you have a working pins file just make a PR to 2.0.x so others can benefit

**Comment by Aurawin** [comment]
> HEATER_3_PIN
> Is it because `#define HEATER_3_PIN 8` is using the same pin?

No, the problem is that FAN1_PIN is declared inside the there (pins_Rumba header) without the preface check to see if it was already defined - overriding my value in my Configuration_adv header.

**Comment by Aurawin** [comment]
> if you have a working pins file just make a PR to 2.0.x so others can benefit

I'll go look for the other complaints about Tango previous issues.

**Comment by el-quique** [comment]
Hi try:

pins_RUMBA.h
#ifndef FAN_PIN
  #define FAN_PIN           8
#endif
#define FAN1_PIN            7

Configuration_adv.h
#define E0_AUTO_FAN_PIN 7

Compile in Arduino IDE 1.8.10

**Comment by boelle** [comment]
no ide 1.9.0 beta is recommended
or vscode+platform.io

**Comment by boelle** [comment]
@Aurawin do you still have the isuue?

**Comment by Aurawin** [comment]
I have no issues at this time.  We now have a pins_TANGO.h file to handle any previous stepper pins later.  But this is great.
