### PR TITLE
Fix dogm soft spi link

### LINKED ISSUE #28569: [BUG] Display on SPI Interface seperate from SD does not work
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I've been trying to use the Bugfix Branch to try out FTM and unfortunately cannot get my Display to work with it. Please forgive the structure of this issue, I have tried a lot of things and wanted to include all details that I have.

I have defined the Pins used by the LCD to the Hardware SPI1 pins that the LCD is connected to:

```
#define DOGLCD_CS EXP2_07_PIN //PE12
#define DOGLCD_A0 EXP1_04_PIN //PC6
#define DOGLCD_MOSI EXP2_06_PIN //PA7
#define DOGLCD_SCK EXP2_02_PIN //PA5
#define LCD_RESET_PIN EXP1_03_PIN //PD13
```

Simply trying to compile yields a compilation error:

```
.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: .pio/build/mks_robin_nano_v3_1/src/src/lcd/dogm/u8g/u8g_dev_st7565_64128n_HAL.cpp.o:(.data.u8g_dev_st7565_64128n_HAL_2x_sw_spi+0x8): undefined reference to `u8g_com_HAL_STM32_sw_spi_fn(_u8g_t, unsigned char, unsigned char, void)'
```

- Manually adding `#define FORCE_SOFT_SPI` allows for compilation however in practice results in a blank screen which is an issue in itself (I would LOVE if hardware SPI would work - [On 2.1.2.7 SW SPI is forced](https://github.com/MarlinFirmware/Marlin/blob/9fc25dfe29e380b3893b86aae0664e3e4c855437/Marlin/src/lcd/dogm/marlinui_DOGM.h#L108-L110) and simply forcing HW SPI does not work)

- If I **un**define `DOGLCD_MOSI`, `DOGLCD_SCK` the build succeeds without `FORCE_SOFT_SPI` - I then get displayed the boot splash screen however nothing after (Independent of if an SD is inserted or not)

- Then undefining `SDSUPPORT` (With `DOGLCD_MOSI` and `DOGLCD_SCK` configured again) yields full functionality of the LCD

### Bug Timeline

Works on 2.1.2.7 - Oddly on the first commit after the 2.1.2.7 release its reproducible

### Expected behavior

Screen should work, ideally with HW SPI

### Actual behavior

Refer to Description

### Steps to Reproduce

Regression from 2.1.2.7 (No compilation / No output with SWSPI):

```
python .\buildroot\bin\opt_set MOTHERBOARD BOARD_MKS_ROBIN_NANO_V3_1
python .\buildroot\bin\opt_set LCD_CONTRAST_DEFAULT 210
python .\buildroot\bin\opt_add VIKI2 XYZ_HOLLOW_FRAME REVERSE_ENCODER_DIRECTION SDCARD_READONLY SDSUPPORT REINIT_NOISY_LCD

python .\buildroot\bin\opt_set SERIAL_PORT -1

python .\buildroot\bin\opt_set DOGLCD_CS EXP2_07_PIN
python .\buildroot\bin\opt_set DOGLCD_A0 EXP1_04_PIN
python .\buildroot\bin\opt_set DOGLCD_MOSI EXP2_06_PIN
python .\buildroot\bin\opt_set DOGLCD_SCK EXP2_02_PIN
python .\buildroot\bin\opt_set LCD_RESET_PIN EXP1_03_PIN
```

### Version of Marlin Firmware

bugfix e2817dbec4256220845de5a6bf88174981209e4d

### Printer model

_No response_

### Electronics

MKS Robin Nano V3.1, using the onboard Micro SD (Connected to SPI3)

### LCD/Controller

I use a bare 12864-06D **Connected to SPI1**, its also the display used by the VIKI2 which is what I configure in Marlin

### Other add-ons

_No response_

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[files.zip](https://github.com/user-attachments/files/32040599/files.zip)

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Fixes #28569 — a DOGM display on SPI pins other than the SD card's fails to link:

```
u8g_dev_st7565_64128n_HAL.cpp.o:(.data.u8g_dev_st7565_64128n_HAL_2x_sw_spi+0x8):
  undefined reference to `u8g_com_HAL_STM32_sw_spi_fn(_u8g_t*, unsigned char, unsigned char, void*)'
```

The SW-SPI U8G communication function is compiled only under `FORCE_SOFT_SPI`,
but the U8G device tables that reference it are compiled unconditionally. When
`marlinui_DOGM.h` selects the SW-SPI device the reference is kept alive, while
the HAL never compiles the function to satisfy it.

Three changes. Fixes 1 and 2 make the software-SPI fallback work, which is what
2.1.2.7 did for this display — `marlinui_DOGM.h` has always forced SW SPI when
the DOGLCD pins differ from the SD card's. Fix 3 goes further and makes
**hardware** SPI work, which is what the reporter actually asked for
("Expected behavior: Screen should work, ideally with HW SPI").

### The mismatch

`u8g_dev_st7565_64128n_HAL.cpp` emits **both** device structs, with no condition
beyond `HAS_MARLINUI_U8GLIB`:

```cpp
u8g_dev_t u8g_dev_st7565_64128n_HAL_2x_sw_spi = { ..., U8G_COM_HAL_SW_SPI_FN };
u8g_dev_t u8g_dev_st7565_64128n_HAL_2x_hw_spi = { ..., U8G_COM_HAL_HW_SPI_FN };
```

`U8G_COM_HAL_HW_SPI_FN` always resolves. `U8G_COM_HAL_SW_SPI_FN` resolves only
when `FORCE_SOFT_SPI` is set, because the HAL guards it:

```cpp
#if ALL(HAS_MARLINUI_U8GLIB, FORCE_SOFT_SPI)     // u8g_com_stm32duino_swspi.cpp
```

Normally `--gc-sections` discards the unused `_sw_spi` struct along with its
relocation, so the missing symbol never surfaces. It surfaces as soon as
something actually selects that struct.

### Why the guard can't see the decision

For this display the choice is made in `marlinui_DOGM.h`:

```cpp
#elif IS_U8GLIB_ST7565_64128N
  #if (SMART_RAMPS && defined(__SAM3X8E__)) || (defined(DOGLCD_SCK) && (DOGLCD_SCK >= 0 && DOGLCD_SCK != SD_SCK_PIN)) || ...
    #define DOGM_FORCE_SOFT_SPI
  #endif
...
#if defined(DOGM_FORCE_SOFT_SPI) && !defined(FORCE_SOFT_SPI)
  #define FORCE_SOFT_SPI
#endif
```

`marlinui_DOGM.h` is a UI header. The HAL file includes only `MarlinConfig.h`,
which never reaches it, so `FORCE_SOFT_SPI` is undefined there even though the UI
translation unit has just defined it and picked the SW-SPI device. The two
translation units disagree, and the linker is where it shows up.

This is why the reporter's workarounds behave the way they do:

| Reporter's change | Why it changes the outcome |
|---|---|
| Add `#define FORCE_SOFT_SPI` to the config | Now in `MarlinConfig.h` scope, so the HAL compiles the function. Links. |
| Undefine `DOGLCD_MOSI` / `DOGLCD_SCK` | `DOGM_FORCE_SOFT_SPI` is never set, so the HW-SPI device is selected. Links. |

Only a user-set `FORCE_SOFT_SPI`, or one from a pins file, was ever visible to
the HAL. A derived one was not.

### Not a recent regression

The reporter bisected to "the first commit after the 2.1.2.7 release". That is
consistent with what is happening, but the cause is older than it looks.

2.1.2.7 builds this configuration because it does not contain these files at all
— it pulls `marlinfirmware/U8glib-HAL@0.5.4`, where the device tables and the
SW-SPI COM function live together in the library and are always compiled as a
pair. `bugfix-2.1.x` vendored them into Marlin (`🧑‍💻 Move U8G defines to HALs`,
Dec 2023; `🚸🐛 SW SPI Mode 3 for U8G on STM32` #27111, Jun 2024), and the
vendored COM function was given the `FORCE_SOFT_SPI` guard from its first commit
while the vendored device tables kept the library's unconditional form.

So the defect has been latent in `bugfix-2.1.x` since mid-2024 and has never been
in a release. Every `bugfix-2.1.x` commit after the 2.1.2.7 tag reproduces it,
which is what the bisect was showing. `🔧 Allow override DOGM FORCE_SOFT_SPI`
(`63ca8f0a42`), which renamed the flag to `DOGM_FORCE_SOFT_SPI`, is not the
cause — the failure reproduces identically on its parent.

### Fix 1 — the link error

Compile the SW-SPI COM function whenever the pins it needs are defined, instead
of when `FORCE_SOFT_SPI` happens to be visible:

```cpp
#if HAS_MARLINUI_U8GLIB && defined(DOGLCD_SCK) && defined(DOGLCD_MOSI) && defined(DOGLCD_A0) && defined(DOGLCD_CS)
```

This restores the contract the U8glib-HAL library provided: the COM function is
available wherever a device table can reference it, and `--gc-sections` drops it
when nothing does. Device selection stays entirely in `marlinui_DOGM.h`, which is
the only place that has the information to make it.

Applied to all four HALs that carry a vendored copy:

- `HAL/STM32/dogm/u8g_com_stm32duino_swspi.cpp`
- `HAL/STM32F1/u8g/u8g_com_stm32duino_swspi.cpp`
- `HAL/GD32_MFL/dogm/u8g_com_mfl_swspi.cpp`
- `HAL/HC32/u8g/u8g_com_HAL_HC32_sw_spi.cpp`

Guarding on the pins rather than on `FORCE_SOFT_SPI` also means no config can
reach the SW-SPI path without the pins that path writes to.

### Fix 2 — SW-SPI mode 0 clocks the wrong bit

The reporter's blank screen when forcing SW SPI is a second, independent bug.

`U8G_SPI_USE_MODE_3` is set only for `FYSETC_MINI_12864`, `MKS_MINI_12864` and
NATIVE_SIM ST7920 (`Conditionals-2-LCD.h:325-327`). VIKI2 is ST7565, so it takes
`swSpiTransfer_mode_0`, which on STM32 and GD32_MFL writes the clock before the
data:

```cpp
WRITE(DOGLCD_SCK, HIGH);      // rising edge - slave samples here
WRITE(DOGLCD_MOSI, state);    // ...but the bit is only presented now
```

In mode 0 the slave samples MOSI on the rising edge, so each edge latches the
*previous* bit; the first samples whatever MOSI held and the eighth is never
clocked in. Every other HAL has it the right way round — AVR
(`u8g_com_HAL_AVR_sw_spi.cpp:95-99`), STM32F1, HC32 and LPC1768 all set MOSI
first. The `mode_3` function in the same file is also correct, which is why the
FYSETC/MKS mini 12864 displays work.

This has been wrong since the file was added in #27111 and was never noticed,
because the mode-0 path could not link (above) for exactly the displays that
use it.

Fixed in the two affected HALs by putting MOSI first, matching the other four:

- `HAL/STM32/dogm/u8g_com_stm32duino_swspi.cpp`
- `HAL/GD32_MFL/dogm/u8g_com_mfl_swspi.cpp`

The two bugs were hiding each other: the mode-0 path could not link, so the
broken shifter behind it was never reached.

### Fix 3 — hardware SPI for a display on its own bus

This is the reporter's actual request, and the reason his third observation
looks so strange: boot splash then nothing on HW SPI, but a fully working LCD
once `SDSUPPORT` is off.

The u8g hardware-SPI driver uses the **global `SPI` object**, and Marlin's SD
init repoints that same object at the card:

```cpp
SPI.setMISO(SD_MISO_PIN);     // HAL_SPI.cpp:168-172
SPI.setMOSI(SD_MOSI_PIN);
SPI.setSCLK(SD_SCK_PIN);
SPI.begin();
```

The splash is drawn while `SPI` still has its default pins. `spiInit()` then
repoints it to the SD card and every later LCD write goes out on the card's
pins. Forcing SW SPI is Marlin's existing answer, and it is why 2.1.2.7 works
here — but it is a fallback, not the goal.

Given its own `SPIClass` instance the display keeps hardware SPI and is
unaffected by the SD card. `u8g_com_stm32duino_hw_spi.cpp` does that:

```cpp
static SPIClass lcdSPI(DOGLCD_MOSI, DOGLCD_MISO, DOGLCD_SCK);
```

Selected through `U8G_COM_HAL_HW_SPI_FN` in `LCD_defines.h` when the new
`HAS_DOGLCD_HW_SPI` is set; otherwise the U8glib-HAL shared-`SPI` version is
used exactly as before. The onboard SPI flash already works this way
(`libs/W25Qxx.cpp`), so the pattern is not new.

**How Marlin decides.** There is no portable compile-time way to ask whether a
pin is SPI-capable — the pin map is a runtime table — so the board has to say
so. Boards opt in by declaring their display header's SPI pins, and
`Conditionals-5-post.h` sets `HAS_DOGLCD_HW_SPI` when the configured DOGLCD pins
match them (or match the variant's `PIN_SPI_*`). If they match neither, nothing
changes and the display still falls back to SW SPI.

The MKS Robin Nano V3 family knew this already, but only in a branch this
reporter isn't using:

```cpp
#if SD_CONNECTION_IS(LCD)        // ...V3_common.h, before
  #define ENABLE_SPI1
  #define SD_SCK_PIN   EXP2_02_PIN   // PA5
  #define SD_MOSI_PIN  EXP2_06_PIN   // PA7
#endif
```

He runs `SD_CONNECTION_IS(ONBOARD)`, so the knowledge was thrown away. The pins
file now states it unconditionally:

```cpp
#define LCD_SPI_SCK_PIN   EXP2_02_PIN  // PA5
#define LCD_SPI_MISO_PIN  EXP2_01_PIN  // PA6
#define LCD_SPI_MOSI_PIN  EXP2_06_PIN  // PA7
```

`LCD_SPI_MISO_PIN` is not optional even though a display never drives MISO: the
STM32 core refuses to bring up an SPI peripheral whose MISO has no peripheral
mapping (`spi_com.c`: *"at least one SPI pin has no peripheral"*, then it
returns). Passing `NC` would leave the bus silently dead — the same class of
failure as the bug this PR started with.

Other boards opt in by adding those three defines. Nothing changes for boards
that don't.

### Configuring it

Both paths, in the same `opt_set`/`opt_add` form the reporter used.

**Hardware SPI** — DOGLCD pins on the EXP2 header, which is SPI1, while the SD
card stays on SPI3:

```
python .\buildroot\bin\opt_set MOTHERBOARD BOARD_MKS_ROBIN_NANO_V3_1
python .\buildroot\bin\opt_set LCD_CONTRAST_DEFAULT 210
python .\buildroot\bin\opt_add VIKI2 XYZ_HOLLOW_FRAME REVERSE_ENCODER_DIRECTION SDCARD_READONLY SDSUPPORT REINIT_NOISY_LCD

python .\buildroot\bin\opt_set DOGLCD_CS EXP2_07_PIN
python .\buildroot\bin\opt_set DOGLCD_A0 EXP1_04_PIN
python .\buildroot\bin\opt_set DOGLCD_MOSI EXP2_06_PIN
python .\buildroot\bin\opt_set DOGLCD_SCK EXP2_02_PIN
python .\buildroot\bin\opt_set LCD_RESET_PIN EXP1_03_PIN
```

That is the reporter's own configuration, unchanged. Because `DOGLCD_SCK` /
`DOGLCD_MOSI` now match `LCD_SPI_SCK_PIN` / `LCD_SPI_MOSI_PIN`,
`HAS_DOGLCD_HW_SPI` is set and the display gets SPI1 to itself. No new option to
set. Add `DOGLCD_SPI_SPEED` to change the 2.5 MHz default.

**Software SPI** — any two GPIOs, for a display not wired to a SPI header:

```
python .\buildroot\bin\opt_set DOGLCD_CS EXP2_07_PIN
python .\buildroot\bin\opt_set DOGLCD_A0 EXP1_04_PIN
python .\buildroot\bin\opt_set DOGLCD_MOSI PA2
python .\buildroot\bin\opt_set DOGLCD_SCK PA1
python .\buildroot\bin\opt_set LCD_RESET_PIN EXP1_03_PIN
```

The pins match no declared SPI header, so `marlinui_DOGM.h` forces SW SPI as it
always has — now linkable (Fix 1) and shifting bits correctly (Fix 2).

### Testing

The reporter's own configuration, verified by inspecting the linked objects
rather than just the exit status:

| Build | Before | After |
|---|---|---|
| Robin Nano V3.1 + VIKI2, DOGLCD on EXP2/SPI1 (#28569) | undefined reference | **SUCCESS, hardware SPI** |
| ...same, DOGLCD moved to arbitrary GPIOs (PA1/PA2) | undefined reference | **SUCCESS, software SPI** |
| Robin Nano V3.1 + REPRAP_DISCOUNT_FULL_GRAPHIC (ST7920) | SUCCESS | SUCCESS |
| Robin Nano V3.1 + FYSETC_MINI_12864_2_1 | SUCCESS | SUCCESS |
| Robin Nano V3.1 + MKS_MINI_12864 | SUCCESS | SUCCESS |
| Robin Nano V3.1, SD on the LCD header | SUCCESS | SUCCESS |
| HC32F460C_aquila_101 | SUCCESS | SUCCESS |
| GD32F103RC_aquila_mfl | SUCCESS | SUCCESS |
| mega2560 default config | SUCCESS | SUCCESS |

The first two rows are the point of the change, and `nm` confirms the split:

```
EXP2 pins:       U u8g_dev_st7565_64128n_HAL_2x_hw_spi   + u8g_com_HAL_STM32_hw_spi_fn
arbitrary GPIOs: U u8g_dev_st7565_64128n_HAL_2x_sw_spi   + u8g_com_HAL_STM32_sw_spi_fn
```

Two limits on what this table proves. It says nothing about Fix 2 — a bit-order
change is invisible to the compiler, so these builds pass either way. And on
GD32 the SW-SPI translation unit compiles to an empty object: no in-tree
`GD32_MFL` board defines `DOGLCD_CS`/`DOGLCD_A0`, so the guard is false and the
body is never reached. Substituting `MKS_MINI_12864` or `ZONESTAR_12864OLED`
fails on that board for those same missing pins, before and after this patch. So
the two GD32 edits are unexercised by any build I can construct - they are
textually identical to the STM32 ones, which are exercised, but that is the only
assurance behind them.

### Scope and testing limits

Everything here is verified by build and by reading the linked objects; **none
of it is tested on hardware** — I have no VIKI2 or Robin Nano V3.1.

- Fix 1 and the build results are certain.
- Fix 2 is a straightforward reading of SPI mode 0 against four other HALs that
  do it the other way round, but whether the display then produces a picture
  needs the bench.
- Fix 3 selects the right code path, provably. Whether SPI1 then drives that
  display correctly — clock polarity, the 2.5 MHz default over a ribbon cable,
  CS timing — has not been observed on hardware and should be confirmed before
  this is merged.

@kinsi55 — if you can build this branch and report back, the hardware-SPI path
is the part that most needs a second pair of eyes.

### CODE REVIEW

**Comment by kinsi55** [comment]
Thank you for the quick turnaround! I gave this PR a go, from what I can tell everything is resolved:

- Compilation works without forcing SWSPI
- The conditional defining `DOGM_FORCE_SOFT_SPI` is not hit
- Screen appears to be fully functional
- Out of Curiosity I've also attempted 5MHz for `DOGLCD_SPI_SPEED` which also works so the default appears to have a fair bit of safety margin.
- Changing SCK or MOSI pins hits the SWSPI conditional again (I have not tested this for function as I dont have a simple way right now to actually rewire to a different pin)

One thing I noticed is that removing the SD card is not automatically detected anymore - I can still go into the "Select from SD Card" menu despite having removed the SD. ~~*Inserting* the SD is detected and brings me to the file selector.~~ Is this a change in newer Marlin versions or is it a regression from this PR?

*Edit:* Seems like inserting the SD also isnt something that is reliably detected - I cannot replicate that finding.

**Comment by ellensp** [comment]
In Marlin/src/pins/stm32f4/pins_MKS_ROBIN_NANO_V3_common.h it has

```cpp
//
// Onboard SD card
//
#if SD_CONNECTION_IS(ONBOARD)
  #define ENABLE_SPI3
  #define SD_SS_PIN                         PC9
  #define SD_SCK_PIN                        PC10
  #define SD_MISO_PIN                       PC11
  #define SD_MOSI_PIN                       PC12
  #if ENABLED(NO_SD_HOST_DRIVE)
    #define SD_DETECT_PIN                   PD12  // Detect pin doesn't work with SD Host Drive
  #endif
#endif
```
So unless you enable NO_SD_HOST_DRIVE in Configuration_adv. h  It deactivates the  SD_DETECT_PIN 

added in https://github.com/Marlinfirmware/Marlin/commit/95fb1f4e1759d92ac8912d3ba88af154ef117e5b#diff-e099d1933b694d8ee7814a633fce89c11c0d6154414920be28372db9519ae4c9L221

**Comment by kinsi55** [comment]
You're right - Adding that restored the previous / expected function. Given that I think this might be good to merge, I have not spotted anything else yet 🎉

**Comment by thinkyhead** [comment]
We generally define pins for boards according to what their function will be in the Marlin build, but some pins such as fans and endstops are defined generally and can be referenced in configuration files when not used for their default function. We aim to make board pins defined as generally as possible so they can be used in any way.

When we define pins for LCD controllers we're usually asserting that the LCD is connected to those pins. Declaring them generally with no conditions implies these are silkscreened "LCD SPI" pins which are left open for general use. The configuration also allows for an SD card to be attached to the "LCD" SPI connector even when no LCD is present.

Anyway, we haven't fully worked out how we define SPI pins for boards. We expect board's hardware SPI pins to be defined as such by the platform or variant, so there are (sometimes) pins like `PIN_SPI_SCK`, `SCK1`, `MISO1`, etc. already defined. Some boards define `BOARD_SPI1_SCK_PIN` etc. as does the LPC1768 HAL's `SPI.h` file.

This PR is a good fix. It also presents a good opportunity to examine the overall situation and wrangle SPI pin definition and handling in Marlin so that we have a full accounting and a direct way to know which pins are hardware vs. software SPI. For now, if the name `LCD_SPI_SCK_PIN` is always meant to indicate hardware SPI then it will need an uglier name like `LCD_HW_SPI_SCK_PIN`.

**Comment by thisiskeithb** [comment]
I was wrangling LCD/SD SPI issues over in https://github.com/MarlinFirmware/Marlin/pull/28567 and came up with a solution there if you want to take a look.
