### ISSUE TITLE
[BUG] Compilation error when activating ESP3D_WIFISUPPORT option

### ISSUE THREAD

**Issue by GALes** [MarlinFirmware/Marlin#25768]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

An error is thrown when trying to compile the firmware with the ESP3D_WIFISUPPORT option activated, incorrect path to HAL folder. Tested on Windows 10 and Linux Mint 20.3. Compiled with Visual Studio Code and PIO. The error is present in the bugfix branch, the  2.1.x stable branch compiles with no errors

....
.pio/libdeps/mks_tinybee/ESP3DLib/src/espcom.cpp:25:52: fatal error: ../../../../../Marlin/src/HAL/HAL/ESP32/FlushableHardwareSerial.h: No such file or directory
compilation terminated.
...
========================== [FAILED] Took 7.40 seconds ==========================

### Bug Timeline

New issue on bugfix branch, working well on the 2.1.x stable branch

### Expected behavior

Compilation success

### Actual behavior

Archiving .pio/build/mks_tinybee/libFrameworkArduinoVariant.a
Indexing .pio/build/mks_tinybee/libFrameworkArduinoVariant.a
.pio/libdeps/mks_tinybee/ESP3DLib/src/espcom.cpp:25:52: fatal error: ../../../../../Marlin/src/HAL/HAL/ESP32/FlushableHardwareSerial.h: No such file or directory

compilation terminated.
Compiling .pio/build/mks_tinybee/FrameworkArduino/Esp.cpp.o
Compiling .pio/build/mks_tinybee/FrameworkArduino/FunctionalInterrupt.cpp.o
*** [.pio/build/mks_tinybee/libee1/ESP3DLib/espcom.cpp.o] Error 1
========================== [FAILED] Took 7.40 seconds ==========================

Environment    Status    Duration
-------------  --------  ------------
mks_tinybee    FAILED    00:00:07.398
==================== 1 failed, 0 succeeded in 00:00:07.398 ====================

[error_output.zip](https://github.com/MarlinFirmware/Marlin/files/11372984/error_output.zip)

### Steps to Reproduce

1. Configure Configuration.h and Configuration_adv.h to compile for the MKS TinyBee board with wifi support

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Custom

### Electronics

MKS TinyBee (ESP32) board, TMC2209_STANDALONE drivers, 

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[config_files.zip](https://github.com/MarlinFirmware/Marlin/files/11372950/config_files.zip)

**Comment by ellensp** [comment]
duplicate https://github.com/MarlinFirmware/Marlin/issues/25767
