### ISSUE TITLE
[BUG] (Auto Delta calibration no longer works on Anycubic Linear Plus)

### ISSUE THREAD

**Issue by OneOfEleven** [MarlinFirmware/Marlin#23309]
### Did you test the latest `bugfix-2.0.x` code?

Not yet, just doing so now.

### Bug Description

Auto delta calibration does not work.

### Bug Timeline

No idea

### Expected behavior

We expect it to complete the auto delta calibration routine much like v1.1.19 does.

### Actual behavior

Starts the auto delta calibration but stops after 4 central probes with the message ..

"Correct delta settings with M665 and M666"

### Steps to Reproduce

1) Upload newly compiled firmware
2) "M502"
3) "M500"
4) Reboot printer firmware
5) "G28" to home
6) "M111 S247" to enable full logging.
7) "G33" to start an auto delta calibration.

### Version of Marlin Firmware

v2.0.9.2 latest source

### Printer model

Anycubic Kossel Linear Plus

### Electronics

Stock/original board

### Add-ons

None

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Pronterface

### Additional information & file uploads

[config_log_files.zip](https://github.com/MarlinFirmware/Marlin/files/7727489/config_log_files.zip)

Using latest v2.0.9.2, firstly it does not compile using Arduino IDE 1.8.16 (see below).
To get it to compile we had to temporarily comment out line 148 in "language.h".

Anyway, auto delta calibration does not work.
It works fine using Marlin v1.1.19.
G29 bed levelling works, just not auto delta calibration (G33). 
There are no hardware faults, limit switches are all fine, Z-probe switch is fine.

It starts to probe OK, does a single center probe followed by 3 outter probes close around the center, at which point the probing stops with the following message ..

"Correct delta settings with M665 and M666"

========================
Compilation problem temporary fix is to comment out line 148 in "language.h"

In file included from C:\Projects\3D Printer\AnyCubic Kossel Linear Plus\Marlin-2.0.9.2\Marlin\src\lcd\extui\ftdi_eve_touch_ui\language\language.h:23:0,
                 from C:\Projects\3D Printer\AnyCubic Kossel Linear Plus\Marlin-2.0.9.2\Marlin\src\lcd\extui\ftdi_eve_touch_ui\language\language.cpp:25:
C:\Projects\3D Printer\AnyCubic Kossel Linear Plus\Marlin-2.0.9.2\Marlin\src\lcd\extui\ftdi_eve_touch_ui\language\language_en.h:148:24: error: redefinition of 'const char Language_en::MSG_MESH_VIEW []'
   PROGMEM Language_Str MSG_MESH_VIEW                = u8"View Mesh";
                        ^~~~~~~~~~~~~
In file included from C:\Projects\3D Printer\AnyCubic Kossel Linear Plus\Marlin-2.0.9.2\Marlin\src\core\language.h:563:0,
                 from C:\Projects\3D Printer\AnyCubic Kossel Linear Plus\Marlin-2.0.9.2\Marlin\src\inc\MarlinConfig.h:53,
                 from C:\Projects\3D Printer\AnyCubic Kossel Linear Plus\Marlin-2.0.9.2\Marlin\src\MarlinCore.h:24,
                 from C:\Projects\3D Printer\AnyCubic Kossel Linear Plus\Marlin-2.0.9.2\Marlin\src\lcd\extui\ftdi_eve_touch_ui\language\language.cpp:23:
C:\Projects\3D Printer\AnyCubic Kossel Linear Plus\Marlin-2.0.9.2\Marlin\src\lcd\language\language_en.h:160:8: note: 'const char Language_en::MSG_MESH_VIEW [10]' previously defined here
   LSTR MSG_MESH_VIEW                      = _UxGT("View Mesh");
        ^~~~~~~~~~~~~

========================

**Comment by sjasonsmith** [comment]
This has already been fixed in bugfix-2.0.x and verified by multiple people (myself included).

I’m closing this issue, but please reply if you still encounter problems with the bugfix branch.

**Comment by OneOfEleven** [comment]
> This has already been fixed in bugfix-2.0.x and verified by multiple people (myself included).
> 
> I’m closing this issue, but please reply if you still encounter problems with the bugfix branch.

Yes by all means close it @sjasonsmith, sorry about that, used the latest 2.0.9.2 instead of bugfix ver.

I'm running the bugfix one now and all seems good!

My bad.
