### ISSUE TITLE
#24761 [BUG] Cannot compile if EMERGENCY_PARSER is enabled, but SDSUPPORT is not

### ISSUE THREAD

**Issue by rondlh** [MarlinFirmware/Marlin#24774]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

#24761 causes problems, you cannot compile if EMERGENCY_PARSER is enabled, but SDSUPPORT is not.

### Bug Timeline

#24761

### Expected behavior

Be able to compile the Marlin source

### Actual behavior

Unable to compile Malrin

### Steps to Reproduce

1. Enable EMERGENCY_PARSER
2. Keep SDSUPPORT disable
3. Try to compile

### Version of Marlin Firmware

Latest bugfix (September 18th 2022)

### Printer model

Custom

### Electronics

MKS SGEN_L V2.0 (LPC1769)

### Add-ons

BTT TFT35 V3

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/9594241/Configuration_adv.zip)
The issues are caused by #24761

The addition of M524 in temperature.cpp is not guarded by SDSUPPORT.

But the addition in e_parser.cpp is guarded by SDSUPPORT
     #if ENABLED(SDSUPPORT)
       EmergencyParser::sd_abort_by_M524,
     #endif

This will cause compilation errors if SDSUPPORT is not enabled, but EMERGENCY_PARSER is enabled.

**Comment by ellensp** [comment]
Fixed in https://github.com/MarlinFirmware/Marlin/pull/24775
