### PR TITLE
ProUI Fixes

### LINKED ISSUE #24248: [BUG] DWIN ProUI does not compile with latest bugfix-2.0.x
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Using the stock configurations from:

Building *with* a BLTouch:
```
Marlin/src/lcd/e3v2/proui/dwin.cpp: In function 'float Tram(uint8_t)':
Marlin/src/lcd/e3v2/proui/dwin.cpp:2344:19: error: 'MESH_MIN_X' was not declared in this scope
 2344 |       LIMIT(xpos, MESH_MIN_X, MESH_MAX_X);
      |                   ^~~~~~~~~~
Marlin/src/lcd/e3v2/proui/dwin.cpp:2344:31: error: 'MESH_MAX_X' was not declared in this scope
 2344 |       LIMIT(xpos, MESH_MIN_X, MESH_MAX_X);
      |                               ^~~~~~~~~~
Marlin/src/lcd/e3v2/proui/dwin.cpp:2345:19: error: 'MESH_MIN_Y' was not declared in this scope
 2345 |       LIMIT(ypos, MESH_MIN_Y, MESH_MAX_Y);
      |                   ^~~~~~~~~~
Marlin/src/lcd/e3v2/proui/dwin.cpp:2345:31: error: 'MESH_MAX_Y' was not declared in this scope
 2345 |       LIMIT(ypos, MESH_MIN_Y, MESH_MAX_Y);
      |                               ^~~~~~~~~~
*** [.pio/build/STM32F103RE_creality/src/src/lcd/e3v2/proui/dwin.cpp.o] Error 1
```

Building *without* a BLTouch:
```
In file included from Marlin/src/lcd/e3v2/proui/../../../inc/MarlinConfigPre.h:37,
                 from Marlin/src/lcd/e3v2/proui/../../../inc/MarlinConfig.h:28,
                 from Marlin/src/lcd/e3v2/proui/dwin.cpp:30:
Marlin/src/lcd/e3v2/proui/dwin.cpp: In function 'void update_variable()':
Marlin/src/lcd/e3v2/proui/dwin.cpp:165:65: error: 'struct HMI_data_t' has no member named 'ManualZOffset'
  165 | #define BABY_Z_VAR TERN(HAS_BED_PROBE, probe.offset.z, HMI_data.ManualZOffset)
      |                                                                 ^~~~~~~~~~~~~
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:621:26: note: in definition of macro 'THIRD'
  621 | #define THIRD(a,b,c,...) c
      |                          ^
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:247:29: note: in expansion of macro '___TERN'
  247 | #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
      |                             ^~~~~~~
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:246:29: note: in expansion of macro '__TERN'
  246 | #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
      |                             ^~~~~~
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:242:29: note: in expansion of macro '_TERN'
  242 | #define TERN(O,A,B)         _TERN(_ENA_1(O),B,A)    // OPTION ? 'A' : 'B'
      |                             ^~~~~
Marlin/src/lcd/e3v2/proui/dwin.cpp:165:20: note: in expansion of macro 'TERN'
  165 | #define BABY_Z_VAR TERN(HAS_BED_PROBE, probe.offset.z, HMI_data.ManualZOffset)
      |                    ^~~~
Marlin/src/lcd/e3v2/proui/dwin.cpp:803:7: note: in expansion of macro 'BABY_Z_VAR'
  803 |   if (BABY_Z_VAR != _offset) {
      |       ^~~~~~~~~~
Marlin/src/lcd/e3v2/proui/dwin.cpp:165:65: error: 'struct HMI_data_t' has no member named 'ManualZOffset'
  165 | #define BABY_Z_VAR TERN(HAS_BED_PROBE, probe.offset.z, HMI_data.ManualZOffset)
      |                                                                 ^~~~~~~~~~~~~
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:621:26: note: in definition of macro 'THIRD'
  621 | #define THIRD(a,b,c,...) c
      |                          ^
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:247:29: note: in expansion of macro '___TERN'
  247 | #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
      |                             ^~~~~~~
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:246:29: note: in expansion of macro '__TERN'
  246 | #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
      |                             ^~~~~~
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:242:29: note: in expansion of macro '_TERN'
  242 | #define TERN(O,A,B)         _TERN(_ENA_1(O),B,A)    // OPTION ? 'A' : 'B'
      |                             ^~~~~
Marlin/src/lcd/e3v2/proui/dwin.cpp:165:20: note: in expansion of macro 'TERN'
  165 | #define BABY_Z_VAR TERN(HAS_BED_PROBE, probe.offset.z, HMI_data.ManualZOffset)
      |                    ^~~~
Marlin/src/lcd/e3v2/proui/dwin.cpp:804:15: note: in expansion of macro 'BABY_Z_VAR'
  804 |     _offset = BABY_Z_VAR;
      |               ^~~~~~~~~~
Marlin/src/lcd/e3v2/proui/dwin.cpp: In function 'void DWIN_Draw_Dashboard()':
Marlin/src/lcd/e3v2/proui/dwin.cpp:165:65: error: 'struct HMI_data_t' has no member named 'ManualZOffset'
  165 | #define BABY_Z_VAR TERN(HAS_BED_PROBE, probe.offset.z, HMI_data.ManualZOffset)
      |                                                                 ^~~~~~~~~~~~~
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:621:26: note: in definition of macro 'THIRD'
  621 | #define THIRD(a,b,c,...) c
      |                          ^
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:247:29: note: in expansion of macro '___TERN'
  247 | #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
      |                             ^~~~~~~
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:246:29: note: in expansion of macro '__TERN'
  246 | #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
      |                             ^~~~~~
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:242:29: note: in expansion of macro '_TERN'
  242 | #define TERN(O,A,B)         _TERN(_ENA_1(O),B,A)    // OPTION ? 'A' : 'B'
      |                             ^~~~~
Marlin/src/lcd/e3v2/proui/dwin.cpp:165:20: note: in expansion of macro 'TERN'
  165 | #define BABY_Z_VAR TERN(HAS_BED_PROBE, probe.offset.z, HMI_data.ManualZOffset)
      |                    ^~~~
Marlin/src/lcd/e3v2/proui/dwin.cpp:1037:115: note: in expansion of macro 'BABY_Z_VAR'
 1037 |   DWINUI::Draw_Signed_Float(DWIN_FONT_STAT, HMI_data.Indicator_Color,  HMI_data.Background_Color, 2, 2, 204, 417, BABY_Z_VAR);
      |                                                                                                                   ^~~~~~~~~~
Marlin/src/lcd/e3v2/proui/dwin.cpp: In function 'void SetZOffset()':
Marlin/src/lcd/e3v2/proui/dwin.cpp:165:65: error: 'struct HMI_data_t' has no member named 'ManualZOffset'
  165 | #define BABY_Z_VAR TERN(HAS_BED_PROBE, probe.offset.z, HMI_data.ManualZOffset)
      |                                                                 ^~~~~~~~~~~~~
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:621:26: note: in definition of macro 'THIRD'
  621 | #define THIRD(a,b,c,...) c
      |                          ^
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:247:29: note: in expansion of macro '___TERN'
  247 | #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
      |                             ^~~~~~~
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:246:29: note: in expansion of macro '__TERN'
  246 | #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
      |                             ^~~~~~
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:242:29: note: in expansion of macro '_TERN'
  242 | #define TERN(O,A,B)         _TERN(_ENA_1(O),B,A)    // OPTION ? 'A' : 'B'
      |                             ^~~~~
Marlin/src/lcd/e3v2/proui/dwin.cpp:165:20: note: in expansion of macro 'TERN'
  165 | #define BABY_Z_VAR TERN(HAS_BED_PROBE, probe.offset.z, HMI_data.ManualZOffset)
      |                    ^~~~
Marlin/src/lcd/e3v2/proui/dwin.cpp:2001:75: note: in expansion of macro 'BABY_Z_VAR'
 2001 |       babystep.accum = round(planner.settings.axis_steps_per_mm[Z_AXIS] * BABY_Z_VAR);
      |                                                                           ^~~~~~~~~~
In file included from Marlin/src/lcd/e3v2/proui/dwin.cpp:35:
Marlin/src/lcd/e3v2/proui/dwin.cpp: In function 'void Draw_Prepare_Menu()':
Marlin/src/lcd/e3v2/proui/dwin.cpp:165:65: error: 'struct HMI_data_t' has no member named 'ManualZOffset'
  165 | #define BABY_Z_VAR TERN(HAS_BED_PROBE, probe.offset.z, HMI_data.ManualZOffset)
      |                                                                 ^~~~~~~~~~~~~
Marlin/src/lcd/e3v2/proui/menus.h:69:62: note: in definition of macro 'EDIT_ITEM_F'
   69 | #define EDIT_ITEM_F(I,L,V...) MenuItemsAdd(I, GET_TEXT_F(L), V)
      |                                                              ^
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:248:29: note: in expansion of macro 'THIRD'
  248 | #define ___TERN(P,V...)     THIRD(P,V)              // If first argument has a comma, A. Else B.
      |                             ^~~~~
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:247:29: note: in expansion of macro '___TERN'
  247 | #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
      |                             ^~~~~~~
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:246:29: note: in expansion of macro '__TERN'
  246 | #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
      |                             ^~~~~~
Marlin/src/lcd/e3v2/proui/../../../inc/../core/macros.h:242:29: note: in expansion of macro '_TERN'
  242 | #define TERN(O,A,B)         _TERN(_ENA_1(O),B,A)    // OPTION ? 'A' : 'B'
      |                             ^~~~~
Marlin/src/lcd/e3v2/proui/dwin.cpp:165:20: note: in expansion of macro 'TERN'
  165 | #define BABY_Z_VAR TERN(HAS_BED_PROBE, probe.offset.z, HMI_data.ManualZOffset)
      |                    ^~~~
Marlin/src/lcd/e3v2/proui/dwin.cpp:2993:87: note: in expansion of macro 'BABY_Z_VAR'
 2993 |         EDIT_ITEM_F(ICON_Zoffset, MSG_ZPROBE_ZOFFSET, onDrawPFloat2Menu, SetZOffset, &BABY_Z_VAR);
      |                                                                                       ^~~~~~~~~~
compilation terminated due to -fmax-errors=5.
*** [.pio/build/STM32F103RE_creality/src/src/lcd/e3v2/proui/dwin.cpp.o] Error 1
Marlin/src/lcd/e3v2/proui/ubl_tools.cpp: In static member function 'static void UBLMeshToolsClass::manual_move(uint8_t, uint8_t, bool)':
Marlin/src/lcd/e3v2/proui/ubl_tools.cpp:125:44: error: 'bedlevel' was not declared in this scope
  125 |     current_position.z = goto_mesh_value ? bedlevel.z_values[mesh_x][mesh_y] : Z_CLEARANCE_BETWEEN_PROBES;
      |                                            ^~~~~~~~
Marlin/src/lcd/e3v2/proui/ubl_tools.cpp:137:44: error: 'bedlevel' was not declared in this scope
  137 |     current_position.z = goto_mesh_value ? bedlevel.z_values[mesh_x][mesh_y] : Z_CLEARANCE_BETWEEN_PROBES;
      |                                            ^~~~~~~~
Marlin/src/lcd/e3v2/proui/ubl_tools.cpp: In static member function 'static float UBLMeshToolsClass::get_max_value()':
Marlin/src/lcd/e3v2/proui/ubl_tools.cpp:146:13: error: 'x' was not declared in this scope
  146 |   GRID_LOOP(x, y) {
      |             ^
Marlin/src/lcd/e3v2/proui/ubl_tools.cpp:146:16: error: 'y' was not declared in this scope; did you mean 'yn'?
  146 |   GRID_LOOP(x, y) {
      |                ^
      |                yn
Marlin/src/lcd/e3v2/proui/ubl_tools.cpp:146:3: error: 'GRID_LOOP' was not declared in this scope
  146 |   GRID_LOOP(x, y) {
      |   ^~~~~~~~~
compilation terminated due to -fmax-errors=5.
*** [.pio/build/STM32F103RE_creality/src/src/lcd/e3v2/proui/ubl_tools.cpp.o] Error 1
```

### Bug Timeline

18/05/2022

### Expected behavior

.

### Actual behavior

.

### Steps to Reproduce

.

### Version of Marlin Firmware

bugfix-2.0.x

### Printer model

Ender 3 V2 + DWIN

### Electronics

_No response_

### Add-ons

_No response_

### Bed Leveling

_No response_

### Your Slicer

_No response_

### Host Software

_No response_

### Additional information & file uploads

_No response_

### PR DESCRIPTION
**Pull request by mriscoc**
Allow to compile ProUI without and with any mesh leveling system (Manual, ABL, UBL)
Some previous mandatory requisites are now optional features

Fix: https://github.com/MarlinFirmware/Marlin/issues/24248

### CODE REVIEW

**Review by CRCinAU — APPROVED** [review]
Seems to fix building issues if I grab this PR and put it in my build pipelines...

File: Marlin/src/lcd/e3v2/proui/dwin.cpp [hunk 1]
```diff
@@ -162,7 +162,27 @@
...
+  #endif
+  #ifndef MESH_MIN_Y
+    #define MESH_MIN_Y (_MAX(Y_MIN_BED + PROBING_MARGIN, Y_MIN_POS))
+  #endif
+  #ifndef MESH_MAX_X
+    #define MESH_MAX_X (_MIN(X_MAX_BED - (PROBING_MARGIN), X_MAX_POS))
+  #endif
+  #ifndef MESH_MAX_Y
+    #define MESH_MAX_Y (_MIN(Y_MAX_BED - (PROBING_MARGIN), Y_MAX_POS))
+  #endif
```
Comment (thinkyhead) [inline Marlin/src/lcd/e3v2/proui/dwin.cpp]: In ABL Bilinear these are variables, not constants, so it is dangerous to assume any constant value.
