### ISSUE TITLE
[BUG] Compile error latest bugfix 2.0.x on BTT SKR 1.1PRO 

### ISSUE THREAD

**Issue by arminth** [MarlinFirmware/Marlin#23226]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Compiler Error when compiling latest version:

```
Compiling .pio\build\BIGTREE_SKR_PRO\src\src\HAL\STM32\eeprom_sram.cpp.o
Compiling .pio\build\BIGTREE_SKR_PRO\src\src\HAL\STM32\eeprom_wired.cpp.o
Compiling .pio\build\BIGTREE_SKR_PRO\src\src\HAL\STM32\fast_pwm.cpp.o
Compiling .pio\build\BIGTREE_SKR_PRO\src\src\HAL\STM32\fastio.cpp.o
Compiling .pio\build\BIGTREE_SKR_PRO\src\src\HAL\STM32\msc_sd.cpp.o
Compiling .pio\build\BIGTREE_SKR_PRO\src\src\HAL\STM32\tft\gt911.cpp.o
Compiling .pio\build\BIGTREE_SKR_PRO\src\src\HAL\STM32\tft\tft_fsmc.cpp.o
Marlin\src\HAL\STM32\fast_pwm.cpp: In function 'void set_pwm_frequency(pin_t, int)':
Marlin\src\HAL\STM32\fast_pwm.cpp:74:36: error: 'Instance' was not declared in this scope
   74 |   uint32_t index = get_timer_index(Instance);
      |                                    ^~~~~~~~
Marlin\src\HAL\STM32\fast_pwm.cpp:77:16: error: 'TEMP_TIMER_NUM' was not declared in this scope; did you mean 'TIMER_NUM'?
   77 |   if (index == TEMP_TIMER_NUM || index == STEP_TIMER_NUM
      |                ^~~~~~~~~~~~~~
      |                TIMER_NUM
Marlin\src\HAL\STM32\fast_pwm.cpp:77:43: error: 'STEP_TIMER_NUM' was not declared in this scope; did you mean 'TIMER_NUM'?
   77 |   if (index == TEMP_TIMER_NUM || index == STEP_TIMER_NUM
      |                                           ^~~~~~~~~~~~~~
      |                                           TIMER_NUM
*** [.pio\build\BIGTREE_SKR_PRO\src\src\HAL\STM32\fast_pwm.cpp.o] Error 1
```

### Bug Timeline

new since a copuple of days

### Expected behavior

compile fine

### Actual behavior

compile error

### Steps to Reproduce

compile on BTT SKR 1.1 PRO

### Version of Marlin Firmware

2.0.x bugfix

### Printer model

Kossel Delta

### Electronics

BTT SKR 1.1 PRO

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by ellensp** [comment]
Duplicate of #23213
