### ISSUE TITLE
new Issue with STM32 compiles

### ISSUE THREAD

**Issue by jmdearras** [MarlinFirmware/Marlin#15085]
### Description

Library conflict of some sort:
```
Compiling .pioenvs\BIGTREE_SKR_MINI\lib35e\U8glib-HAL_ID1932\lib\u8g_com_arduino_parallel.c.o
In file included from C:\users\jimde\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/boards.h:38:0,
                 from C:\users\jimde\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/wirish.h:54,
                 from C:\users\jimde\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/Arduino.h:30,
                 from .piolibdeps\BIGTREE_SKR_MINI\U8glib-HAL_ID1932\src\lib\u8g_com_arduino_common.c:46:
C:\users\jimde\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/wirish_types.h:65:9: error: unknown type name 'bool'
 typedef bool boolean;
```
I have seen this before.
### Steps to Reproduce

0. update all libraries
1. pull latest marlin bugfix-2.0.x
2. replace the two files with the attached
3. compile

**Expected behavior:** [What you expect to happen]
good compile
**Actual behavior:** [What actually happens]
many errors in the C:\users\jimde\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/wirish_types.h
[config.zip](https://github.com/MarlinFirmware/Marlin/files/3552453/config.zip)

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by thinkyhead** [comment]
This is not something we can address in the Marlin code-base. Try deleting your `.pio` and `~/.platformio/.cache` folders before doing more builds. It may pass once the framework authors figure out that `bool` is only a C++ type and not a C type.

**Comment by jmdearras** [comment]
@thinkyhead  @thisiskeithb  > This is not something we can address in the Marlin code-base. Try deleting your `.pio` and `~/.platformio/.cache` folders before doing more builds. It may pass once the framework authors figure out that `bool` is only a C++ type and not a C type.

I did all that, and now get:
.piolibdeps\BIGTREE_SKR_MINI\TMCStepper_ID5513\src/TMCStepper.h:18:11: fatal error: SoftwareSerial.h: No such file or directory

i do not have any TMC steppers defined.

**Comment by jmdearras** [comment]
OK, commented out //#define SW_CAPABLE_PLATFORM defined(__AVR__) || defined(TARGET_LPC1768) || defined(ARDUINO_ARCH_ESP32) || defined(ARDUINO_ARCH_STM32F1) and it works.
in .piolibdeps\BIGTREE_SKR_MINI\TMCStepper_ID5513\src\TMCStepper.h  
"defined(ARDUINO_ARCH_STM32F1)" probably should not be in that define.

**Comment by thisiskeithb** [comment]
@jmdearras: Try grabbing a fresh copy and compile again. Some patches have been applied that should fix this issue.

**Comment by jmdearras** [comment]
@thisiskeithb yes.  I got a good compile with the SKR-MINI V1.1 for the first time with "stock" marlin!

**Comment by thisiskeithb** [comment]
It was working fine for quite a while when compiling for the SKR Mini. I know because I sent a board to @thinkyhead recently it compiled without issue 😄.

**Comment by jmdearras** [comment]
now if only someone could figure out support for the MKS_MINI_12864!

**Comment by tpruvot** [comment]
if you are not using this repo, will not help you :p btw, skr mini owner too

**Comment by jmdearras** [comment]
> if you are not using this repo, will not help you :p btw, skr mini owner too

@tpruvot I do not understand your reply?

**Comment by tpruvot** [comment]
the TMCStepper serial issue was "fixed" a week or two ago or so... i mean

**Comment by thisiskeithb** [comment]
> the TMCStepper serial issue was "fixed" a week or two ago or so... i mean

But this issue was due to recent changes made to U8glib-HAL.

**Comment by jmdearras** [comment]
I AM using the current marlin.  Turns out I had to delete my .platformio/.cache folder.  How does this address the MKS_MINI_12864 issue?
